### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by cdbkr** [webpack/webpack-dev-server#381] opened 2016-01-21 16:31 UTC
Hi, with version **1.14.1** I'm receiving this error:
```
Uncaught TypeError: Cannot read property 'replace' of null
```
I'm using an inline script in the index.html to load the .JS file (which is in the folder declared  by publicPath) and I enabled the hot module replacement to receive updates.

Using **version 1.14.0**, it works fine (so at the moment I am not updating the webpack-dev-server module to 1.14.1).

**Comment by matiss** [comment] 2016-01-22 11:00
I have the same situation as the OP. I also have a inline script which loads the bundle and I am getting the same error when I upgraded Webpack to `1.14.1`. Downgrade fixed the error, though.

**Comment by techird** [comment] 2016-01-26 12:40
Same problem, seems a problem with `1.14.1`, `1.14.0` is alright.

**Comment by reebalazs** [comment] 2016-01-27 13:47
I can confirm that it breaks when you have a script with no src tag. This is a showstopper if you have injected js into the html.

It breaks on this line: https://github.com/webpack/webpack-dev-server/blob/5b94506f0c47d7fd0bde8d215b6195450e71fc7e/client/index.js#L11

1.14.0 works for me too.

#372 is a duplicate.

**Comment by wedgex** [comment] 2016-02-05 20:22
I'm getting the same error, downgrading to 1.14.0 temporarily as a work around.

**Comment by Nebukam** [comment] 2016-02-20 05:46
Same issue happened to me. Downgraded as well, works like a charm with 1.14.0

**Comment by globexdesigns** [comment] 2016-03-02 02:16
FYI: This is happening when you have a `<script />` tag in your code that doesn't have a `src` attribute.

**Comment by adamhartford** [comment] 2016-03-16 00:55
I was able to work around this with a hack-ish change:

```javascript
<script>
    document.currentScript.src =''; // So that the script executes, but later has a src.

    // ... Do rest of work.   
</script>
```

**Comment by damonmcminn** [comment] 2016-03-19 09:27
I also have this issue. The sole `script` tag on my page contains a `src` attribute:

`<script src="bundle.js"></script>`

Downgrading to *1.14.0* solved the issue.

**Comment by marcelpanse** [comment] 2016-03-24 19:57
Same problem here because of the Google Tag Manager script in the index.html

**Comment by JustinMGaiam** [comment] 2016-05-26 22:23
This issue affected us as well.  Fixing it required setting webpack-dev-server to `1.14.0` in package.json and then the running `npm install` again.

**Comment by incleaf** [comment] 2016-05-27 09:50
Same problem with 1.14.0

**Comment by idoco** [comment] 2016-06-05 12:05
Just to point out for anyone else having the same issue - 
For me this issue occurred because of using the [Poper Blocker chrome extension](https://chrome.google.com/webstore/detail/poper-blocker/bkkbcggnhapdmkeljlodobbkopceiche). I didn't have no script tag without 'src' attribute in the page I was working on, so it was very confusing to understand that this extension injects a script tag (without an 'src' attribute) during the page loading.

I have disabled the extension until this issue will be fixed.

**Comment by adrianmc** [comment] 2016-06-05 18:08
@idoco I can confirm that the popup blocker extension is causing the error for me. Not sure why that is though.

**Comment by idoco** [comment] 2016-06-05 19:35
@adrianmc Yes, I think this is just because the extension injects a script tag with no 'src' attribute to the page which is the real root cause.

**Comment by damonmcminn** [comment] 2016-06-11 06:27
@idoco thanks!

My exact issue. Whitelisting the appropriate dev domains solves the issue.

**Comment by vutran** [comment] 2016-06-22 17:21
Also getting this problem with the similar script injections. The solution provided above (downgrading to 1.14.0) works for me.

**Comment by bhargav175** [comment] 2016-07-06 07:46
I had this error because of a 'defer' attribute in my script tag.

**Comment by kamono** [comment] 2016-07-27 17:29
I had this issue when the variable I used was equal to null. Just added a check to perform .replace if not null, and it works now. Hope this helps someone.

**Comment by SpaceK33z** [comment] 2016-08-21 14:36
Dupe of #117.

**Closed by SpaceK33z** 2016-08-21 14:36 UTC

**Comment by iorrah** [comment] 2016-10-13 20:38
The same issue happened to me. 

**Version details:**

```
DEBUG: -------------------------------
ember.debug.js:5197 DEBUG: Ember      : 1.11.0
ember.debug.js:5197 DEBUG: Ember Data : 1.0.0-beta.14.1
ember.debug.js:5197 DEBUG: jQuery     : 1.11.1
ember.debug.js:5197 DEBUG: -------------------------------
```

**Cause of the issue:**

It seems that adding attributes to Handlebars elements using inline `if` helpers **also** causes the issue (whether the property that you are using on your condition is `true`, `false`, `null` or `undefined`).

_my-component.hbs_

```
<button class="btn btn-solve-my-problems" {{action 'solveIt}} {{if isNotSolvable 'disabled'}}>
  Solve my problems!
</button>
```

_my-component.coffee_

```
isNotSolveble: (->
  if @get('somethingMeaningful') then true else null
).property('somethingMeaningful')
```

**The solution:**

Instead of using the inline `if` helper, I am just attributing the value of `isNotSolvable` to the `disabled` attribute (nothing was changed on the `my-component.coffee` file).

_my-component.hbs_

```
<button class="btn btn-solve-my-problems" {{action 'solveIt}} disabled="{{isNotSolvable}}">
  Solve my problems!
</button>
```

PS.: the `null` being returned from the method has to do with the manipulation of the `disabled` attribute. It has nothing to do with the issue reported on this thread. It only reflects my scenario and how I've solved the issue. More details [here](http://stackoverflow.com/a/3557315).

**Comment by lovemyliwu** [comment] 2016-11-24 04:19
just for somebody rush into this issue:

i missed there is no correct entry in webpack config file after i git check out other branch

the webpack still watch old entry

**Comment by maxifjaved** [comment] 2017-01-06 20:09
faced the same issue. I just clear the cache data, it works.

**Comment by RaycatRakittra** [comment] 2017-01-31 20:31
I ran into the same error on webpack@1.13.x, 1.14.0, and 2.2.1. I thought it was a malformed config, a bad component, a strange caching issue. In my case, the error was alleviated by **running the app in an incognito window**. This might overlap with a browser caching issue but I think the problem were the **extensions injecting <script>s** after all. Just reiterating for the tl;dr folks.

**Comment by charlest7** [comment] 2018-05-22 08:28
yeah
