### ISSUE TITLE
Should work with terminal with 80 columns

### ISSUE THREAD

**Issue by pickfire** [webpack/webpack-dev-server#2436] opened 2020-02-23 14:26 UTC
- Operating System: Linux arch 5.5.4-zen1-1-zen #1 ZEN SMP PREEMPT Sat, 15 Feb 2020 00:40:48 +0000 x86_64 GNU/Linux
- Node Version: v12.16.1
- NPM Version: 6.13.7
- webpack Version: ^3.12.0
- webpack-dev-server Version: ^2.9.1
- Browser: firefox-developer-edition 74.0b4-1

- [x] This is a **bug**
- [x] This is a **modification** request

### Code

No code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior

Should not keep printing newline for each build information and work well for terminal width 80. Like
```
 68% building modules 1106/1135 modules 29 active ...e/components/Form/ListOfDocuments.vue
```

### Actual Behavior

Keeps printing the status in a newline when the terminal width is less than 90
```
 68% building modules 1540/1592 modules 52 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1541/1592 modules 51 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1542/1592 modules 50 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1543/1592 modules 49 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1544/1592 modules 48 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1545/1592 modules 47 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1546/1592 modules 46 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1547/1592 modules 45 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1548/1592 modules 44 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1549/1592 modules 43 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1550/1592 modules 42 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1551/1592 modules 41 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1552/1592 modules 40 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1553/1592 modules 39 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1554/1592 modules 38 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1555/1592 modules 37 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1556/1592 modules 36 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1557/1592 modules 35 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1558/1592 modules 34 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1559/1592 modules 33 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1560/1592 modules 32 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1561/1592 modules 31 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1562/1592 modules 30 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1563/1592 modules 29 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1564/1592 modules 28 active ...sets/icons/flag-icon-css/flags/es.
 68% building modules 1565/1592 modules 27 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1566/1592 modules 26 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1567/1592 modules 25 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1568/1592 modules 24 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1569/1592 modules 23 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1570/1592 modules 22 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1571/1592 modules 21 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1572/1592 modules 20 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1573/1592 modules 19 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1574/1592 modules 18 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1575/1592 modules 17 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1576/1592 modules 16 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1577/1592 modules 15 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1578/1592 modules 14 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1579/1592 modules 13 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1580/1592 modules 12 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1581/1592 modules 11 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1582/1592 modules 10 active ...sets/icons/flag-icon-css/flags/es.
 69% building modules 1583/1592 modules 9 active ...sets/icons/flag-icon-css/flags/es.s
 69% building modules 1584/1592 modules 8 active ...sets/icons/flag-icon-css/flags/es.s
 69% building modules 1585/1592 modules 7 active ...sets/icons/flag-icon-css/flags/es.s
 69% building modules 1586/1592 modules 6 active ...sets/icons/flag-icon-css/flags/es.s
 69% building modules 1587/1592 modules 5 active ...sets/icons/flag-icon-css/flags/es.s
 69% building modules 1588/1592 modules 4 active ...sets/icons/flag-icon-css/flags/es.s
 69% building modules 1589/1592 modules 3 active ...sets/icons/flag-icon-css/flags/es.s
 69% building modules 1590/1592 modules 2 active ...sets/icons/flag-icon-css/flags/es.s
 69% building modules 1591/1592 modules 1 active ...sets/icons/flag-icon-css/flags/es.s
 94% asset optimization
```

### For Bugs; How can we reproduce the behavior?

Just reduce the terminal width to less than 90 or 80. 80 should be the minimum support terminal width, not all the devices are full HD with 21 inch display, it will be best to let it work with smaller size terminal (80 columns width).

### For Features; What is the motivation and/or use-case for the feature?

Work will with different terminals, less weird behavior.

**Comment by evilebottnawi** [comment] 2020-04-15 10:43
It is out from webpack, duplicate of #9769, please provide minimum reproducible test repo/steps in https://github.com/webpack/webpack/issues/9769, we can't reproduce

**Closed by evilebottnawi** 2020-04-15 10:43 UTC
