### ISSUE TITLE
Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by chenjiajing23** [webpack/webpack-dev-server#2778] opened 2020-10-18 07:18 UTC
- Operating System:mac 10.15.17
- Node Version:v14.13.1
- NPM Version:6.14.8
- webpack Version:5.1.3
- webpack-dev-server Version:3.11.0
- Browser:

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const path = require('path');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  mode: 'development',
  entry: {
    app: './src/index.js',
    print: './src/print.js',
  },
  devtool: 'cheap-source-map',
  devServer: {
    contentBase: './dist',
  },
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader',
        ],
      },
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: [
          'file-loader',
        ],
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/,
        use: [
          'file-loader',
        ],
      },
    ],
  },
  plugins: [
    new CleanWebpackPlugin({ cleanStaleWebpackAssets: false }),
    new HtmlWebpackPlugin({
      title: '开发环境',
      inject: true,
      template: path.resolve(__dirname, './index.ejs')
    }),
  ]
};
```

```js
Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /Users/chenjiajing/Desktop/chenjiajing/git-hub/webpack-demo/node_modules/webpack-dev-server/bin/webpack-dev-server.js
```
![image](https://user-images.githubusercontent.com/41351722/96361113-997e0f80-1155-11eb-921e-e99ada1195ee.png)

**Comment by ankurk91** [comment] 2020-10-18 08:00
Duplicate of https://github.com/webpack/webpack-dev-server/issues/2759

**Closed** 2020-10-19 12:07 UTC
