### ISSUE TITLE
Page does a full reload with hmr enabled

### ISSUE THREAD

**Issue by GiancarlosIO** [webpack/webpack-dev-server#1287] opened 2018-01-21 02:18 UTC
* Operating System:
* Node Version:  8.9.0
* NPM Version: 5.5.4
* webpack Version: 3.10.0
* webpack-dev-server Version: 2.11.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

webpack.config.js
![screenshot from 2018-01-20 21 23 53](https://user-images.githubusercontent.com/17274950/35190126-3e3de4bc-fe28-11e7-83e1-c3f45dad38c8.png)

index.js
![screenshot from 2018-01-20 21 24 53](https://user-images.githubusercontent.com/17274950/35190131-5f02a48a-fe28-11e7-8fcf-5fffa95e98b1.png)

server.js
![screenshot from 2018-01-20 21 24 23](https://user-images.githubusercontent.com/17274950/35190127-4e3bd356-fe28-11e7-80af-07da6034a625.png)

and in my index.html i have this script tag
`<script src="http://localhost:4000/client/dist/app.min.js"></script>`

### Expected Behavior
HMR should works

### Actual Behavior
Page does a full reload when i use a index.html served from node.js
![screenshot from 2018-01-20 21 16 41](https://user-images.githubusercontent.com/17274950/35190086-6de0b0ce-fe27-11e7-85d1-4e7bec3596bc.png)

### For Bugs; How can we reproduce the behavior?
git clone https://github.com/GiancarlosIO/node-rgr-app
npm install && npm server:watch && npm client:watch
Open http://localhost:3000 and edit ./client/print.js — hmr not work, Full page reload instead of module reload

**Comment by byzyk** [comment] 2018-01-22 05:24
Please check if this PR #1276 fixes an issue for you.

**Comment by haegul** [comment] 2018-02-22 03:17
#1315 I have a same issue. It works when I matches 'public path'.

**Comment by GiancarlosIO** [comment] 2018-02-22 14:04
@haegul what do you mean with 'matches publicPath'? :thinking: 
my devServer and output objects have the same publicPath :thinking:

**Comment by evilebottnawi** [comment] 2019-02-21 16:29
Reproducible test repo doesn't work, also you use outdated version of `webpack-dev-server`, please update. Closing issue due can't reproduce, anyway feel free to feedback. If somebody can create working reproducible test repo with latest version of `webpack-dev-server` i will reopen issue and fix problem, thanks!

**Closed by evilebottnawi** 2019-02-21 16:29 UTC
