### ISSUE TITLE
"Error occured while trying to proxy" with server-side rendering

### ISSUE THREAD

**Issue by pybuche** [webpack/webpack-dev-server#1455] opened 2018-08-08 12:59 UTC
* Operating System: OSX 10
* Node Version: 9.11.2
* NPM Version: 5.6.0
* webpack Version: 4.16.3
* webpack-dev-server Version: 3.1.5 

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
const path = require('path');
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const ErrorOverlayPlugin = require('error-overlay-webpack-plugin');


const isProd = process.argv.slice(-1)[0] === 'production';

const outPath = path.resolve(__dirname, 'public/dist');
const publicPath = '/public/dist/';

const common = {
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader'
                }
            },
            {
                test: /\.woff2?$/,
                loader: 'url-loader',
                options: {
                    name: 'fonts/[name].[ext]',
                    limit: 1000,
                },
            },
        ],
    },

    resolve: {
        alias: {
            app: path.resolve(__dirname, 'app'),
            test: path.resolve(__dirname, 'test'),
        },
    },

    optimization: {
        minimizer: [
            new UglifyJsPlugin({
                cache: true,
                parallel: true,
                sourceMap: true,
            }),
        ],
    },
};

const configs = {
    client: {
        entry: [
            'babel-polyfill',
            'react-hot-loader/patch',
            'webpack-dev-server/client?http://localhost:8080',
            'webpack/hot/only-dev-server',
            './app/components'
        ],
        output: {
            publicPath,
            path: outPath,
            filename: 'client.js',
        },
        devtool: isProd ? 'source-map' : 'eval-source-map',
        devServer: {
            publicPath,
            contentBase: outPath,
            proxy: {
                '*': {
                    target: 'http://localhost:8000',
                    secure: false,
                },
            },
        },
        plugins: isProd ? [] : [
            new ErrorOverlayPlugin(),
            new webpack.HotModuleReplacementPlugin(),
        ]
    },

    server: {
        target: 'node',
        entry: ['babel-polyfill', './app/server'],
        output: {
            path: outPath,
            publicPath,
            filename: 'server.js',
            libraryTarget: 'commonjs2'
        },
        devtool: false,
        node: { __dirname: true },
        externals: [ nodeExternals() ],
    },
};

module.exports = [
    Object.assign({}, common, configs.client),
    Object.assign({}, common, configs.server),
];
```

```js
  // app/server/app.js
import express from 'express';
import cookieParser from 'cookie-parser';

import config from './config';
import { handleRender } from './render';


const app = express();

const publicDir = config.get('server.publicPath');

app.use('/public', express.static(publicDir));

app.use(cookieParser());
app.use(handleRender);

export default app;
```

```js
// app/components/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import { Provider } from 'react-redux';

import store from 'app/redux/store';

import App from './App';

const html = (
    <Provider store={store}>
        <BrowserRouter>
            <App />
        </BrowserRouter>
    </Provider>
);

if (window.ssr) {
    ReactDOM.hydrate(html, document.getElementById('root'));
} else {
    ReactDOM.render(html, document.getElementById('root'));
}
```

```js
// app/components/App.js
import _ from 'lodash';
import React from 'react';
import { Route, Switch } from 'react-router-dom';
import { hot } from 'react-hot-loader'
import { ThemeProvider } from 'styled-components';

import theme from 'app/assets/style/theme';
import Head from 'app/components/html/Head';

const App = () => (
    <ThemeProvider theme={theme}>
        <React.Fragment>
            <Head />
            <Switch>
                {* my routes... *}
            </Switch>
        </React.Fragment>
    </ThemeProvider>
);

export default hot(module)(App);
```

### Expected Behavior
I tried to integrate dev server & hot reloading for my server-side rendering React app.
The expected behavior would be to have the HMR working on every file change, when running these commands to launch the dev app:

```shell
// Webpack client & server
TARGET=client webpack-dev-server --mode development & TARGET=server webpack --mode development --watch
// Launch express server
nodemon ./public/dist/server.js
```

### Actual Behavior
Currently, it doesn't reload at all. I tried so many combinations, I faced two quite similar behaviors, when a file is updated:

1. The HMR module is triggered and I got a white screen with the following error:
```
Error occured while trying to proxy to: localhost:8080/
```
2. The HMR module is triggered, updates the view, but I have the same error as above in my Chrome console. After that, any file update does nothing. 

### For Bugs; How can we reproduce the behavior?
With the above code snippets, you should be able to reproduce.
I've found a lot of thread about this subject, telling to change the proxy wildcard to a double one or other similar ideas, but none of them ever worked...

Thanks!

**Comment by evilebottnawi** [comment] 2018-08-08 13:01
@pybuche this messages mean proxy can't have access to proxy url, maybe you have invalid configuration for proxy or somebody blocked you request (example firewall)

**Comment by pybuche** [comment] 2018-08-08 13:10
@evilebottnawi thanks for you quick answer!
I understand what you are saying, but I'm working on a personnal internet connection without any security, I'm on a last-generation Macbook without firewall enabled so I don't see what could cause my requests to be blocked...

Is there any configuration on my express server to enable webpack-dev-server to proxy it correctly?

What is weird also is that I sometimes manage to have one good refresh, so the server has actually been reached at least once correctly...

**Comment by pybuche** [comment] 2018-08-28 15:37
Anyone encountered the problem?

**Comment by evilebottnawi** [comment] 2018-10-18 09:43
@pybuche problem still exists? If yes, can you create minimum reproducible test repo?

**Comment by pybuche** [comment] 2018-10-18 12:36
Indeed, problem still exists.
I'll try to do that asap, thanks for looking into it.

**Comment by evilebottnawi** [comment] 2018-10-23 11:28
@pybuche you `webpack` configuration is insane, please read documentation before setup webpack or ask other peoples on `gitter` or `stackoverflow` how do this in right way. 

Problems:
1. `[HPM] Error occurred while trying to proxy request / from localhost:8080 to http://localhost:8000 (ECONNREFUSED)` is not related to `HMR`. This error means backend server can't response your request - he is not starting/working or already stopped due errors in `backend` server. In your case `webpack-dev-server` is async and when you run `nodemon` `server.js` script not yet created.
2. First you should build `server` (`server` name configuration) when run `server` when run `client`. You need custom start script for this. Running `webpack-dev-server` start `client` and `server`. `nodemon` run server again. I.e. you have 2 server and one client.
3. Don't add `webpack-dev-server/client?http://localhost:8080`. `webpack-dev-server` do this https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/addEntries.js#L23. Now you have two client scripts, it is invalid.
4. Don't mess `webpack-dev-server --mode development & webpack --mode development --watch`, why your start `webpack-dev-server` and `watch` together :confused: Just run `webpack-dev-server --mode development`.
5. Don't run `babel-node` in `nodemon` (see `package.json`), you already using `babel-loader` for `server` entry. Otherwise you run your code throw `babel` twice.

Note:
1. Don't find anything in docs what says you need include `react-hot-loader/patch` in entry.
2. Update `webpack-cli` and `babel` (a lot of big bugs were fixed).
3. Add `target: 'web'` to client to avoid misleading.

Example of same configuration https://github.com/kriasoft/react-starter-kit. You can investigate how it is work and rework you code base, sorry we can't do this for you.

I close this issue, because your problems not related to `webpack-dev-server`, you have invalid configuration and script order.

**Closed by evilebottnawi** 2018-10-23 11:28 UTC

**Comment by truongvinhtrinh** [comment] 2020-03-21 14:55
I got same problem today, but have had this help me:
https://developerhandbook.com/webpack/how-to-add-hot-module-reloading-to-a-react-app/


> Anyone encountered the problem?

**Comment by yinsang** [comment] 2020-12-23 02:02
May be too may files of HRM.
I install * clean-webpack-plugin * to webpack.base.js , then error goes away.
```

const { CleanWebpackPlugin } = require('clean-webpack-plugin');
plugins: [

    new CleanWebpackPlugin(),
...
]

```
