### ISSUE TITLE
Error overlay gets stuck on first failed compilation

### ISSUE THREAD

**Issue by ludovicofischer** [webpack/webpack-dev-server#824] opened 2017-03-01 11:37 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
When a change to a file to solve a compilation error introduces a different compilation error, the error overlay keeps showing the first error, even if the console output correctly reports the new error.

**If the current behavior is a bug, please provide the steps to reproduce.**

From the `webpack.config.js` entry point, import an ES6 module containing a syntax error. The error overlay displays the error. Change the imported module to contain a different syntax error. Now the error overlay keeps displaying the old error.

**What is the expected behavior?**
The error overlay should display the new error.

**Please mention your webpack and Operating System version.**
webpack 2.2.1, Fedora 25.

**Comment by SpaceK33z** [comment] 2017-03-01 14:30
Please ensure you are on the latest version of webpack dev server. Something like this was fixed in the latest version.

**Comment by ludovicofischer** [comment] 2017-03-01 15:46
I’m using 2.4.1, which should be the latest. Is [this](https://github.com/webpack/webpack-dev-server/commit/3cb79bd39489d12a2df9896ce204b8de15e636f4) the commit that should fix the issue?

**Comment by SpaceK33z** [comment] 2017-03-01 17:57
Yes. Can you reproduce it using [this example](https://github.com/webpack/webpack-dev-server/tree/master/examples/overlay) (clone the repo, `npm i` and read the instructions in the README of the example)?

**Comment by ludovicofischer** [comment] 2017-03-01 18:49
I’ll try. Do you think it could be related to using node 7.6 intead of 6 to run `webpack-dev-server`?

**Comment by ludovicofischer** [comment] 2017-03-01 19:04
I can’t reproduce the problem with the simple setup in the repository, but it keeps happening in my own project. 
Here is my webpack config: https://gist.github.com/ludovicofischer/a44babb411341937868fccc3d768a726. I run i`webpack-dev-server` with this `npm` script:

```
NODE_ENV=development webpack-dev-server --open"
```
Could `eslint-loader` interfere with proper reloading? I notice other strange things, like sometimes the error overlay disappears but old page stays (the page does not seem to reload) and some error messages are missing completely.

**Comment by SpaceK33z** [comment] 2017-03-11 14:45
@ludovicofischer do you also have the issue when using `enforce: "pre"` (see [eslint-loader readme](https://github.com/MoOx/eslint-loader))?

**Comment by ludovicofischer** [comment] 2017-03-11 21:30
I tested `enforce: pre` and it doe not change anything. I still cannot reproduce the issue reliably. I tried repeating exactly the same edits and one the overlay updates and another time it gets stuck.

**Comment by shellscape** [comment] 2017-08-09 00:36
Pruning due to age, inactivity.

**Closed by shellscape** 2017-08-09 00:36 UTC
Labels: question
