### ISSUE TITLE
Changes of files we shouldn't care about trigger recompilations

### ISSUE THREAD

**Issue by tremby** [webpack/webpack-dev-server#719] opened 2016-12-20 23:18 UTC
I *think* this is a bug.

I'm using webpack-dev-server (the executable) on a VM, and because of filesystem weirdness, that means I need to enable `--watch-poll` (not sure if this is relevant). In full, I'm running `webpack-dev-server --host 0.0.0.0 --progress --watch-poll`.

It's finding changes correctly and recompiling. But it's also noticing changes when files it shouldn't care about change. In particular, vim's swap files, which are of the form `.somefilename.extension.swp` (which would correspond to the file `somefilename.extension`). The symptom is that when I make any change to a file in vim, even without saving it yet, webpack-dev-server thinks something has changed and starts recompiling. (If I switch off the swap files in vim (`:set noswapfile`), these extra recompilations cease, so I know it's the swap files.)

All of my loader configurations have `test`s set with regexes ending in a file extension and then `$`, so none of these `.swp` files should be considered. For example, I have `test: /\.jsx?$/` for my JSX loader, and this couldn't be matching a file called `.index.jsx.swp`.

I've tried adding `exclude: /\.swp$/` to the configurations and this didn't make a difference.

My current full configuration is at https://gist.github.com/tremby/1ed5ef73f111dcc6223b6718dd901673 in case it's informative.

I'm using webpack 1.14.0 and webpack-dev-server 1.16.2 on an Ubuntu 16.04 VM running node 6.9.1, in Virtualbox on Mac OSX.

Apologies if I've just misconfigured something.

**Comment by SpaceK33z** [comment] 2016-12-20 23:47
You could try to ignore those files from watch mode by using [`watchOptions.ignored`](https://webpack.js.org/configuration/watch/#watchoptions-ignored).

**Comment by tremby** [comment] 2016-12-20 23:55
I just tried that: I added the following to my `config` object:

```js
watchOptions: {
  ignored: /\.sw[pon]$/,
},
```

and after restarting the server changes to the swap files still trigger rebuilds.

**Comment by SpaceK33z** [comment] 2016-12-22 11:06
Do you use `require.context()` somewhere in your app?

**Comment by SpaceK33z** [comment] 2016-12-22 11:12
I tried reproducing this by using webpack-dev-server with `--watch-poll` and opening the entry file in vim. I verified that it created a `.swp` file, but it didn't trigger any change. So I think you either use `require.context()`, or something else that blindly includes all dotfiles.

I'd suggest to first try to change your entry file by removing all code and only placing a simple `console.log('hi')` in it. Check if it still happens after that. If it still happens, try to remove as much as possible from your webpack config to see what introduces the error.

**Comment by tremby** [comment] 2016-12-23 08:37
The codebase doesn't use `require.context()` to my knowledge. I'll double check when I'm in the office again. I'll do as you suggest too and report back.

**Comment by tremby** [comment] 2017-01-09 22:27
I grepped the entire working directory for require.context and the only hits were in node_modules/webpack/lib/dependencies.

But for the life of me I can no longer reproduce this. I have no idea what if anything has changed, other than I know the host machine (and VM obviously) have been rebooted. I'll reopen if I ever see this again.

Sorry for the noise... :(

**Comment by tremby** [comment] 2017-01-09 22:41
Oh, I found it again. What I hadn't realized was that it's only changes to arbitrary files in a particular directory which are being picked up.

The React module in this particular directory has this line:

```js
var svg = require(`./${this.props.icon}.svg`);
```

If I comment this line out, webpack-dev-server stops recompiling when swap files change. If I uncomment it again, it starts recompiling when swap files change again.

Any idea why?

**Comment by SpaceK33z** [comment] 2017-01-09 23:42
I don't know out the top of my head, but you should ask this on StackOverflow. this is not a specific issue with webpack-dev-server...

**Comment by tremby** [comment] 2017-01-10 00:06
It's not? webpack-dev-server (or one of its dependencies -- which?) is watching files and deciding to recompile.

**Comment by SpaceK33z** [comment] 2017-01-10 00:11
webpack does all the compiling, not webpack-dev-server.

**Comment by tremby** [comment] 2017-01-10 00:22
Including the watching of files? Sorry if I'm in totally the wrong place here.

**Comment by SpaceK33z** [comment] 2017-01-10 08:29
Jup. I advise to first ask this on StackOverflow though, you'll probably get an answer quicker then.

**Comment by bjakubiak** [comment] 2017-01-21 05:16
There is workaround by configuring vim itself: http://stackoverflow.com/questions/40624078/disable-webpacks-file-watching-for-vim-swp-files

Maybe webpack-dev-server just reads what libraries search for. For me all lines importing anything from angular2 cause reacting for vim swap files behaviour (from typescript *.ts files):
```
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
```

**Comment by tremby** [comment] 2017-01-21 05:35
I'm aware of the workaround, but I'd rather not have to use it.

I posted before about the one line I can change which alters the behaviour
for me. Could that be explained by what you just suggested?

**Comment by bjakubiak** [comment] 2017-01-21 14:37
Just guessing, but maybe webpack cannot resolve the module name before compiling and searches for every file? And something similar may exist inside angular2 libraries.

**Comment by tremby** [comment] 2017-01-21 16:22
That could definitely be right. I wonder if I can rewrite that somehow to
get around it...

**Comment by SpaceK33z** [comment] 2017-02-18 18:08
I'm going to close this since this is an issue in webpack; webpack-dev-server essentially does the same as `webpack --watch`, so I can't fix this here.

**Closed by SpaceK33z** 2017-02-18 18:08 UTC
