### ISSUE TITLE
CLI port config can not override devServer.port config

### ISSUE THREAD

**Issue by Aqours** [webpack/webpack-dev-server#2488] opened 2020-03-30 07:54 UTC
- Operating System: macOS 10.15.4
- Node Version: 12.14.0
- NPM Version: 6.13.4
- webpack Version: 4.41.2
- webpack-dev-server Version: 3.9.0
- Browser: Chrome 80

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
n/a

```js
// webpack.config.js
{
        devServer: {
            compress: true,
            overlay: true,
            host: '127.0.0.1',
            port: 80,
            openPage: './index.html',
            headers: {
                'X-Custom-Server': 'webpack-dev-server',
            },
        },
}
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
--port 8080(CLI param) can override devServer.port config

### Actual Behavior
--port 8080 can not override devServer.port config

### For Bugs; How can we reproduce the behavior?
1. Using webpack.config.js(partial) to create a mini repo
2. run `npx webpack-dev-server --open --hot --mode=development --port 8080`
3. log errors because of devServer.port(80) need super permission
-----
I can override devServer.openPage config via add `--open-page "/diff.html"` correctly.

**Comment by evilebottnawi** [comment] 2020-03-31 10:47
Yes, it is bug, it will be fixed in next version, we can't do it for current version because it is breaking change

**Comment by hiroppy** [comment] 2020-07-27 05:47
I checked this issue and I wasn't able to reproduce it on v4.

**Comment by evilebottnawi** [comment] 2020-07-27 12:55
@hiroppy Yep, let's close

**Closed by evilebottnawi** 2020-07-27 12:55 UTC
