### ISSUE TITLE
Nothing is exported using UMD

### ISSUE THREAD

**Issue by lexkrstn** [webpack/webpack-dev-server#2379] opened 2019-12-30 11:24 UTC
When opening in browser my UMD library I'm getting the following error in the browser's console:
> (index):111 Uncaught ReferenceError: %LIBRARY_NAME% is not defined

Whereas when I open it without webpack-dev-server (I mean just starting `http-server` at *docs* directory) everything works as expected.

Looking through the sources, I found that devServer's build version of my library, unlike the regular one, returns checkDeferredModules() which apparently doesn't return the main module's exports.

The output of my library is configured like this:
```javascript
output: {
  library: {
    amd: 'hall-plan',
    commonjs: 'hall-plan',
    root: 'HallPlan',
  },
  libraryTarget: 'umd',
  libraryExport: 'default',
  filename: `[name]${DEBUG ? '' : '.min'}.js`,
  path: path.join(__dirname, 'dist'),
},
```
and devServer:
```js
devServer: {
  contentBase: [
    path.join(__dirname, 'docs'),
    path.join(__dirname, 'dist'),
  ],
},
```
Also an interesting thing happens when I specify the port of devServer to any other than 8080. I got an additional error just before the one described above:
>  Uncaught TypeError: Cannot read property 'default' of undefined

Which happens here:
```js
/***/ 0:
/*!*****************************************************************************!*\
  !*** multi (webpack)-dev-server/client?http://localhost:8081 ./src/main.ts ***!
  \*****************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

__webpack_require__(/*! C:\Users\lexkr\Workspace\hall-plan\node_modules\webpack-dev-server\client\index.js?http://localhost:8081 */"./node_modules/webpack-dev-server/client/index.js?http://localhost:8081");
module.exports = __webpack_require__(/*! ./src/main.ts */"./src/main.ts");


/***/ })

/******/ })["default"];      // <----------- HERE
```

**Comment by evilebottnawi** [comment] 2019-12-30 11:30
Please format your issue using issue template

**Comment by evilebottnawi** [comment] 2020-01-31 14:39
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Feel free to open new issue with reproducible test repo, thanks

**Closed by evilebottnawi** 2020-01-31 14:39 UTC

**Comment by GeoffZhu** [comment] 2021-02-24 03:27
Useful for me, https://github.com/webpack/webpack-dev-server/issues/2484

**Comment by GeoffZhu** [comment] 2021-02-24 03:27
Useful for me, https://github.com/webpack/webpack-dev-server/issues/2484
