### ISSUE TITLE
2.10.0 IE11 Invalid character

### ISSUE THREAD

**Issue by luisbelloch** [webpack/webpack-dev-server#1269] opened 2018-01-09 17:38 UTC
* Operating System: High Sierra (Server), Windows 10+IE11 (Client)
* Node Version: 9.3
* NPM Version: 5.6
* webpack Version: 3.10.0 5291b875078cf2abf42bdd23afe3f8f96c17d725
* webpack-dev-server Version: 2.10.1 a9768375346e62155860fe3cef3d4d641b24273e

- [X] This is a **bug**
- [ ] This is a **modification** request

Same issue as #1265 and #1084 

### Code

```
    devServer: {
      port: 9000,
      contentBase: './dist',
      stats: 'errors-only',
      overlay: true,
      proxy: {
        '/api': {
          target: 'http://localhost:8080',
          pathRewrite: { '^/api': '' },
          ws: true
        }
      }
    }
```

### Expected Behavior

Page is opened in IE11.

### Actual Behavior

IE11 complains about invalid backtick. Source inspector shows the backticks in `sendMsg` function:

```
    self.postMessage({
      type: `webpack${type}`,
      data
    }, '*');
```

### For Bugs; How can we reproduce the behavior?

Load up any page via webpack-dev-server in IE11.

**Comment by shellscape** [comment] 2018-01-09 17:49
@luisbelloch please search before opening new issues. duplicate of #1268.

**Closed by shellscape** 2018-01-09 17:49 UTC

**Comment by luisbelloch** [comment] 2018-01-09 18:07
That was... 2 hours ago 😅 

Sorry, didn't notice.
