### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by chrismcv** [webpack/webpack-dev-server#424] opened 2016-03-11 09:51 UTC
Hi, 

I'm using the following configuration, and running `webpack-dev-server --content-base public`
```
  proxy: {
    '/api/*': {
      target: 'http://localhost:4907',
      rewrite: function(req) {
        console.log(req)
        req.url = req.url.replace(/^\/api/, '');
      }
    }
  },
```

All requests e.g. `/api/user/current` have a 404 response, and my `console.log` never fires.  Is there some other part of the config that I'd need to change?

Thanks, 
Chris

**Comment by paulvanbladel** [comment] 2016-03-21 06:20
Yep, I confirm that proxy is not working.

**Comment by sokra** [comment] 2016-03-25 08:57
there is no `rewrite` option.

See options here: https://www.npmjs.com/package/http-proxy-middleware

**Comment by cwhenderson20** [comment] 2016-03-26 07:01
I am also experiencing this issue and am not using any kind of rewrites, just a simple:
```js
proxy: {
  '/api/*': {
    target: 'http://localhost:4001'
  }
}
```

Similarly to @chrismcv, I get a 404 for `/api` routes and the server to which I am proxying never receives the request.

**Comment by robertjmason** [comment] 2016-04-10 04:50
For those committed to Webpack 2 beta but need request proxying with your HMR, if you install webpack-dev-server@1.14.1 and swap in 2.0.0 beta's `reloadApp()` in `/client/index.js`, it ships the `webpackHotUpdate` messages via EventEmitter and world peace ensues. It's just a workaround/bandaid, but it's a relatively painless one: [gist](https://gist.github.com/robertjmason/826c9b114e4e25c94a5fe7d411bdad3c#file-index-js-L91)

**Comment by denglingbo** [comment] 2016-05-05 07:27
http how to proxy https?

http://page.com/
ajax: https://xxxxx

**Comment by lhecker** [comment] 2016-05-22 16:13
As @sokra already mentioned the [`pathRewrite` option](https://github.com/chimurai/http-proxy-middleware#http-proxy-middleware-options) can now be used for this.

It would be cool, @sokra, if this could be mentioned in the docs somewhere. :blush:

**Comment by tomascharad** [comment] 2016-06-07 03:46
Hi, I'm getting a 502 Bad Gateway error while using webpack 2 beta and webpack-dev-server with HMR while trying to proxy.
Any clues on this?

**Comment by tomascharad** [comment] 2016-06-07 04:29
Was caused by a Rails problem, not webpack. Sorry. 
(if someone is using Rails 5.rc you should change localhost:3000 to [::1]:3000 in the meantime).

**Comment by Romathonat** [comment] 2016-07-21 08:34
I had an error with ajax call too : when I made request to my backend, there was a 404 error and the proxy did not seem to work. In fact, it was because the matched pattern is reuse in the redirection : you can delete it that way : 

``` js
proxy: {
     '/api/**': {
        target: 'http://localhost:8080/',
        rewrite: function(req) {
          req.url = req.url.replace(/^\/api/, '');
        },
        changeOrigin: true
     }
  }
```

So, that way my calls to http://localhost:3000/api/** are redirected to http://localhost:8080/, and not http://localhost:8080/api

**Comment by SpaceK33z** [comment] 2016-08-25 08:47
@chrismcv, were you able to solve your issues with the answers provided above?

**Comment by westor21** [comment] 2016-08-31 11:33
For me before angular2 rc.5 this worked:

proxy: {
  '/api*': {
    target: 'http://localhost:5001'
  }
}

Now I got also 404 errors for all of my services.

I removed the * and that fixed it:
proxy: {
  '/api': {
    target: 'http://localhost:5001'
  }
}

**Comment by SpaceK33z** [comment] 2016-09-03 14:47
`pathRewrite` is documented now in the docs, so closing this issue.

If your proxy still doesn't work, but worked in old versions of 1.x, try to add `secure: false`. I've seen that help sometimes.

**Closed by SpaceK33z** 2016-09-03 14:47 UTC
Labels: Needs Response From Author

**Comment by johnhamm** [comment] 2017-01-10 01:12
Just incase anyone else is running into this issue - the PHP standalone server also requires "[::1]" instead of ```
"localhost"... i.e. proxy: [
            {
                path: '**',
                target: 'http://[::1]:3000',
                secure: false
            }
        ]
```

**Comment by jellyfish-tom** [comment] 2017-07-20 09:33
above solution works on OS X, hitting java server running on 8081, from webpack on 9000. 
Thanks!

**Comment by Karl-Gustav** [comment] 2017-10-02 06:44
We got 404 from azure api servers, and we solved it by  adding `changeOrigin: true` to our proxy config. 

    "/api": {
        target: "https://devapi.example.com",
        secure: false,
        changeOrigin: true
    }

**Comment by tindn** [comment] 2018-01-10 17:21
@karl-gustav just spent 3 hours debugging the 404 error. Your comment saved me potentially more hours. Researching back at the [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware#options) docs, I found the tip `Set the option changeOrigin to true for name-based virtual hosted sites.`, and setting this option to true would `changes the origin of the host header to the target URL`. 

I still don't fully understand the reason for this. Would appreciate any help.

**Comment by karl-gustav** [comment] 2018-01-10 17:36
@tindn I’m afraid we won’t be much help here, we just tried stuff until it worked :-(

**Comment by nimatullah** [comment] 2018-12-30 11:43
I have same issue. All above advice does not work

**Comment by NodiraIbrogimova** [comment] 2019-02-13 05:00
I tried all options above in my vuejs app, but none of them seem to work. 
In **webpack.config.js** I added the following:
```
devServer: {
    historyApiFallback: true,
    // noInfo: false,
    // overlay: false, 
    proxy: {
      '/accountApi': {
        target: 'http://someapiurl.net/',
        secure: false,
        changeOrigin: true,
        pathRewrite: {
          '^/accountApi' : ''
        }
      }
    }
  }
```
and writing POST request in one of the components as: 
```
  axios
        .post(`/accountApi/api/users/....`, {
          current_password: this.currentPassword,
          password: this.newPassword_1,
          password_confirmation: this.newPassword_2
        })
        .then(response => {
          ....
        })
```
But, this seems not to work, as long as I'm getting the error :
**The requested URL /accountApi/api/users/... was not found on this server.**

Anybody can help me to figure out what's wrong here, please?

**Comment by jcarenza** [comment] 2020-06-11 15:28
@NodiraIbrogimova this worked for me:
```
devServer: {
    proxy: {
        "/api": {
            target: "http://localhost:5000",
            pathRewrite: (req) => req.replace(/^\/api/, "")
        }
    }
}
```

**Comment by StefanLobbenmeierObjego** [comment] 2024-11-06 13:48
Ran into this issue after upgrading nx and angular to their latest versions, something changed and the asterisk is no longer a wildcard but a literal, after removing the asterisks it worked again
