### ISSUE TITLE
#iframe {z-index: -1;}

### ISSUE THREAD

**Issue by andrey-aleshkov** [webpack/webpack-dev-server#559] opened 2016-08-22 16:44 UTC
Hi there! I've just updated webpack-dev-server and got 
`#iframe {
...
z-index: -1;
}`

So now my app became completely unreachable for mouse and touches. If I remove "z-index: -1;" in the inspector everything works fine. What I'm doing wrong? Thank you.

**Comment by SpaceK33z** [comment] 2016-08-22 17:45
This was added in #380. Can you share a screenshot of what is happening?

**Comment by shkumbini** [comment] 2016-08-22 19:45
Confirmed, this is happening on my project too.

**Comment by craigklem** [comment] 2016-08-23 14:40
Seeing the same thing. Confirmed that this happens in Chrome and Firefox on Windows 7. No mouse events in iframe, no rollovers, click, nothing. Keys seem to work.

**Comment by SpaceK33z** [comment] 2016-08-23 19:54
I removed `z-index: -1` again with 1a19c2d5bb6124469229a910eb002d4b988bde59.

**Comment by MartinMuzatko** [comment] 2016-08-26 17:28
Thanks for fixing this!

**Comment by erfangc** [comment] 2016-08-28 00:54
👍  Appreciating fixing this in `#master`! Since this is a pretty show-stopping bug is there plan to release a bugfix patch to the 1.x line  from which the bug emerged?

**Comment by SpaceK33z** [comment] 2016-09-02 10:58
Fix released in `1.15.1` and `2.1.0-beta.2`.

**Closed by SpaceK33z** 2016-09-02 10:58 UTC
