### ISSUE TITLE
Hot reload don't work if parent path contain `[]`

### ISSUE THREAD

**Issue by eromoe** [webpack/webpack-dev-server#526] opened 2016-07-11 01:11 UTC
If you work path contain `[]`, hot reload wouldn't work, such as `E:\[sync]`,
Once remove `[]` work fine.

I add `[` just want to make this folder place at top(order by name, `[` is before alphabet) , just easy to find.

PS: I found a lot node module has similar problem.

**Comment by SpaceK33z** [comment] 2016-09-03 14:28
Dupe of #188. See reason as for why it's closed over there.

**Closed by SpaceK33z** 2016-09-03 14:28 UTC
Labels: bug
