### ISSUE TITLE
Backport ecf49a8 "Don't reload app upon proxy errors." and release of 1.14.2?

### ISSUE THREAD

**Issue by Mischi** [webpack/webpack-dev-server#498] opened 2016-06-03 19:21 UTC
Hi @sokra,

we use the proxy functionality of webpack-dev-server extensively. Not all of our proxy targets are running all the time which isn't strictly necessary for our usecase except that we stumble over the bug fixed in https://github.com/webpack/webpack-dev-server/commit/a233ecf0eaf5364cc057b436306281b3c5cb1b19, in case proxy targets are not up and running.

As we are currently locked to webpack-1 we are not able to benefit from the bugfix yet. Therefore we would be very thankful if you could release a new bugfix release 1.14.2 which incorporates https://github.com/webpack/webpack-dev-server/commit/a233ecf0eaf5364cc057b436306281b3c5cb1b19.

I've created a webpack-dev-server-1 branch over https://github.com/Mischi/webpack-dev-server/tree/webpack-dev-server-1. Can you push that branch into your repository and publish a new npm release?

As an alternative we may publish a new npm release from my branch into our corporate npm repository but we would definitively would favor a official package from the public repository.

Yours sincerely,
Fabian 

/CC @davidreher

**Comment by Mischi** [comment] 2016-06-06 10:53
If you consider releasing 1.14.2 from my webpack-dev-server-1, i would like to backport #499 (after you have merged it) as well.

Do you know any other commits which my be worth backporting?

**Comment by Mischi** [comment] 2016-06-06 15:37
https://github.com/Mischi/webpack-dev-server/tree/webpack-dev-server-1 now includes #449 too.

**Comment by SpaceK33z** [comment] 2016-08-21 14:21
Dupe of #363. Working on it, so it won't take long.

**Closed by SpaceK33z** 2016-08-21 14:21 UTC
