### ISSUE TITLE
[BUG] in multiple configs runs just first config, but should all

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [webpack/webpack-dev-server#2737] opened 2020-09-13 14:25 UTC
webpack.config.js:

```js
const path = require('path')


module.exports = [
  {
    entry: path.resolve(__dirname, './app_one/index.js'),
    output: {
      path: path.resolve(__dirname, './build/app_one/')
    },
    devServer: {
      contentBase: path.resolve(__dirname, './build/app_one/'),
      port: 81,
    }
  },

  {
    entry: path.resolve(__dirname, './app_two/index.js'),
    output: {
      path: path.resolve(__dirname, './build/app_two/')
    },
    devServer: {
      contentBase: path.resolve(__dirname, './build/app_two/'),
      port: 82,
    }
  },
]
```

bash:
```bash
$ webpack-dev-server
```

It run just `app_one` on 81 port, app_two not runned, is bug

**Comment by evilebottnawi** [comment] 2020-09-14 11:41
Duplicate of #2355, same problems

**Closed by evilebottnawi** 2020-09-14 11:41 UTC
