### ISSUE TITLE
deep linking with contentBase gives a problematic side effect.

### ISSUE THREAD

**Issue by Foxandxss** [webpack/webpack-dev-server#640] opened 2016-10-07 16:32 UTC
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
webpack: 2 beta 25
webpack-dev-server: 2 beta 8

**Please tell us about your environment:**
macOS Sierra
Running via NPM script (AKA CLI)

**Current behavior:**

Loading a path (that is not root) directly (say `localhost:8080/about`) or refreshing it, will render the `index.html` as expected but the html webpack plugin will never inject the script tags with the bundle.

**Expected/desired behavior:**

Loading the `localhost:8080/about` should render the `index.html` and have all the scripts injected into it.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration. Be sure to specify how you are running the server.** 

If you want to reproduce it, clone this [starter](https://github.com/preboot/angular2-webpack), install the dependencies, run `npm start`, go to /about and refresh it.

* **What is the expected behavior?**

It should render the about page and not the index.html with the Loading... part.

I was unsure whether this is a bug at dev-server or html webpack plugin, but since the plugin is able to inject the stuff in the root path (or after a bundle) I think the bug relies on the dev server.

If you check the devServer config, you can see:

```
  config.devServer = {
    contentBase: './src/public',
    historyApiFallback: true,
    quiet: true,
    stats: 'minimal' // none (or false), errors-only, minimal, normal (or true) and verbose
  };
```

If I remove the `contentBase` (and move the index.html) it works.

I am using the `contentBase` to serve also the assets, so all the images can be loaded directly from there.

I could potentially remove the `contentBase` and fix things around but this is definitely a bug.

**Comment by SpaceK33z** [comment] 2016-10-07 18:09
I think the problem is that when using `historyApiFallback`, it will prefer the files from `contentBase` above the webpack in-memory files.

Previously this was not the case, I think it was changed in beta 8. Could you check if beta 7 works for you?

**Comment by Foxandxss** [comment] 2016-10-07 20:58
Doesn't work with beta 7 and according to #642 happens from beta 6

**Comment by SpaceK33z** [comment] 2016-10-08 08:44
This is actually a very problematic issue. Every change here seems to break someone's setup, but we're getting there by adding more tests. For previous struggles, see #625, #627 and the "final" fix in cb1b32fa6c57ec3ae9d16be129279df9448cb29f.

I've added a failing test in the branch `historyapifallback-struggles`. If all tests succeed, this issue is solved. If anyone wants to take stab at it, please do. It is very important to *not* change the existing tests.

**Comment by cebor** [comment] 2016-10-10 15:54
A workaround is renaming the `index.html` -> `index.tmp`. 

```
new HtmlWebpackPlugin({
  template: './src/index.tmpl',
  chunksSortMode: 'dependency'
}),
```

So the template does not get interpreted as index in the contentBase path.

**Comment by SpaceK33z** [comment] 2016-10-11 19:11
This should be fixed with `2.1.0-beta.9`. Would appreciate a confirmation.

**Closed by SpaceK33z** 2016-10-11 19:11 UTC

**Comment by cebor** [comment] 2016-10-12 16:46
works for me, thanks!

**Comment by Foxandxss** [comment] 2016-10-12 16:55
Works for me too.

**Comment by WillooWisp** [comment] 2016-10-17 19:47
Works!
