### ISSUE TITLE
Old chunks kept in memory after reload if hashes used

### ISSUE THREAD

**Issue by jacek213** [webpack/webpack-dev-server#892] opened 2017-04-26 08:46 UTC
I use `webpack-dev-server v2.4.2` with following configuration

        output: {
            path: path.join(__dirname, '/dist'),
            filename: '[name].[hash].js'
        },
        devServer: {
            contentBase: './dist',
            port: PORT,
            host: HOST,
            historyApiFallback: true
        }

Started with params: `$ webpack-dev-server --inline --hot --progress --open`

From what I've noticed, after hot reload or page refresh new assets are generated, but old ones are still kept in memory and available. So if my build constists of 5 chunks, after working on a project for a couple of minutes, the number of chunks kept in memory raises to three digit number. Is there a way to get around that?

**Comment by akatechis** [comment] 2017-05-12 22:03
I have a similar issue. I'm not really using hot reloading, just manually refreshing my browser, and I still run into the issue where WDS is serving cached files, for several minutes after I've saved and recompiled my app.

My config looks like
 ```
output: {
  filename: `[name]${DEVELOPMENT_MODE ? "" : ".[chunkhash]"}.js`,
  path: path.resolve(__dirname, "dist"),
},
devServer: {
  contentBase: path.join(__dirname, "dist"),
  publicPath: "http://localhost:9000/",
  compress: true,
  inline: false,
  port: 9000
}
```

**Comment by shellscape** [comment] 2017-08-30 04:53
@jacek213 @akatechis have you tried v2.7.1 with the latest webpack?

**Comment by akatechis** [comment] 2017-08-30 14:41
Will give it a shot with WDS@2.7.1 and Webpack@2.7.0 and let you know how it works out. I haven't been able to reliably reproduce the issue that I'm seeing (and to be quite honest, I'm not 100% certain the behavior I see is that exact same as described by this issue), but will keep you updated.

**Comment by shellscape** [comment] 2017-09-20 11:58
@akatechis any updates? we're going through issues that have become stale and would like to keep this open if it's still an issue.

**Comment by akatechis** [comment] 2017-09-20 14:57
I have not seen this in a while. It seems to have been fixed. I have no problem closing this out, and opening a new issue if I come across this issue again in the future.

Thanks!

**Comment by shellscape** [comment] 2017-09-20 15:34
Thanks for following up!

**Closed by shellscape** 2017-09-20 15:34 UTC
Labels: bug, S5: Regression
