### ISSUE TITLE
Hot  No more work

### ISSUE THREAD

**Issue by promiseLC** [webpack/webpack-dev-server#4291] opened 2022-02-16 03:41 UTC
### Bug report

I configured devServer, but I didn't get the result I wanted
### Actual Behavior

I modified the listening file, but there was no hot module replacement or even refreshing the page
### Expected Behavior

The listening file should be modified. The content I modified will change and the page will not be refreshed
### How Do We Reproduce?
https://github.com/promiseLC/webpack5.git

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

<img width="824" alt="image" src="https://user-images.githubusercontent.com/56290517/154191893-c9926d17-0c38-493f-aa4c-e1607b03dfb1.png">

<img width="694" alt="image" src="https://user-images.githubusercontent.com/56290517/154191798-419939e5-6a0b-4954-9946-442c64777828.png">

**Comment by alexander-akait** [comment] 2022-02-16 11:59
You set `client: false`, so not HMR reload logic will be in your application, expected

**Closed by alexander-akait** 2022-02-16 11:59 UTC

**Comment by promiseLC** [comment] 2022-02-17 03:47
GET http://localhost:8080/runtime.7d943879cbb471711727.hot-update.json 404 (Not Found)

error

**Comment by snitin315** [comment] 2022-02-17 03:53
@promiseLC remove `client: false` from your configuration for HMR to work.

@alexander-akait maybe we can log warning if we have `client: false` along with `hot: true` in config?

**Comment by promiseLC** [comment] 2022-02-17 03:56
i delete client: false , HRM is work ,but it not normal , is Refresh page

**Comment by promiseLC** [comment] 2022-02-17 04:01
Error reporting information  http://localhost:8080/runtime.7d943879cbb471711727.hot-update.json 404 (Not Found) , i think
 publicPath  problem
<img width="489" alt="截屏2022-02-17 12 00 16" src="https://user-images.githubusercontent.com/56290517/154402728-ea9219c3-3525-482d-832a-2e77ea8999f7.png">

**Comment by promiseLC** [comment] 2022-02-17 07:00
@alexander-akait   I found that opening HRM cannot open output Clean: true, otherwise HRM will fail. I don't know if it's a problem with my code. You can check whether it's a problem  , I wonder if this has anything to do with #1385

**Comment by alexander-akait** [comment] 2022-02-17 10:28
Sorry I can't reproduce your problem, do you use MacOS?

**Comment by promiseLC** [comment] 2022-02-17 11:38
@alexander-akait Yes, I use MacOS. You can pull my code and try it. Now I modify it to the stage of HRM failure. Is there a reason?   https://github.com/promiseLC/webpack5.git
