### ISSUE TITLE
2.0 Peer dependency does not cover webpack 2.1.0-beta.5

### ISSUE THREAD

**Issue by calebmer** [webpack/webpack-dev-server#461] opened 2016-04-22 23:30 UTC
Could the next release of `webpack-dev-server` 2 update its peer dependency to include webpack `2.1.0-beta.5`?

**Comment by jgoux** [comment] 2016-05-03 09:43
A release would be great. There are a lot of fixes done since the last one. :+1:

**Comment by SpaceK33z** [comment] 2016-08-21 14:22
Dupe of #363. Working on it!

**Closed by SpaceK33z** 2016-08-21 14:22 UTC
