### ISSUE TITLE
"lazy" mode does not seem to work in the latest webpack-dev-server

### ISSUE THREAD

**Issue by sergebat** [webpack/webpack-dev-server#1323] opened 2018-02-26 13:36 UTC
* Operating System: Windows 10 (crosschecked on Ubuntu 17.10)
* Node Version: 8.4.0
* NPM Version: 5.6.0
* webpack Version: 4.0.0 (first spotted on 3.x)
* webpack-dev-server Version: 3.0.0 (first spotted on 2.x)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/sergebat/test-webpack-lazymode
```js
'use strict';

module.exports = {
  entry: './app.js',
  mode: "development",
  output: {
    filename: "bundle.js"
  },
  devServer: {
    lazy: true,
    inline: false,
    filename: "bundle.js"
  }
};
```

### Expected Behavior

http://localhost:8080/bundle.js should return bundle in Lazy mode when loaded in browser. 

### Actual Behavior

Browser displays: "Cannot GET /bundle.js". 

If lazy: true is removed, bundle.js returns fine. 

I tried http://localhost:8080/dist/bundle.js, tried removing optional filename in devServer, tried removing inline: false. Neither of these options worked for me. 

### For Bugs; How can we reproduce the behavior?

Sync repo at https://github.com/sergebat/test-webpack-lazymode, then:
```
npx webpack-dev-server
```
and open bundle in browser.

**Comment by scottsword** [comment] 2018-03-02 16:22
I'm not running in lazy mode, but I have found that if I set `inline: false` that I appear to get a jQuery deferred error. If I remove `inline: false` and go with the default everything works fine. This is unfortunate however, because I'm requesting an asset from webpack-dev-server for another app, if I don't set `inline: false` it reloads the whole page for my non-webpack app.

Here is the error:
```
jQuery.Deferred exception: n(...) is not a function TypeError: n(...) is not a function
    at HTMLDocument.<anonymous> (https://localhost:8080/__webpack_dev_server__/live.bundle.js:1:163209)
    at c (https://localhost:8080/__webpack_dev_server__/live.bundle.js:1:105849)
    at l (https://localhost:8080/__webpack_dev_server__/live.bundle.js:1:106151) undefined
T.Deferred.exceptionHook @ live.bundle.js:1
```

**Comment by SpaceK33z** [comment] 2018-03-02 16:43
@scottsword this will be fixed in next release (fixed in #1329)

**Comment by SpaceK33z** [comment] 2018-03-02 17:03
@sergebat, webpack-dev-server only passes the `lazy` option to webpack-dev-middleware; so I think the issue is in that package.

**Comment by sergebat** [comment] 2018-03-02 17:10
@SpaceK33z thanks. I'll try to reproduce with raw 'webpack-dev-middleware' over weekend, and if it occurs there, will create and link issue there.

**Comment by scottsword** [comment] 2018-03-02 19:06
@SpaceK33z thanks man, I saw that someone added a fix for it yesterday, just hasn't made its way out.  For posterity, the I encountered was different than OP's and was fixed with this commit - https://github.com/webpack/webpack-dev-server/commit/f2db057ac105ec945f0e62dba64441c4ccfde59c

**Comment by sergebat** [comment] 2018-03-04 19:11
@SpaceK33z interestingly enough, things seem work fine on webpack-dev-middleware:
https://github.com/sergebat/test-webpack-lazymode/blob/master/testmw.js

File above works fine on Ubuntu `node testmw.js` for me (not on Windows, as things seem to be broken there the hard way, but that's another issue I guess https://github.com/webpack/webpack-dev-middleware/issues/270)

At the same time, `node_modules/.bin/webpack-dev-server` displays "Cannot GET /bundle.js" for me on Ubuntu. 

In case it helps someone diagnose the issue, it starts to work if path is explicitly and incorrectly specified like this:
```
'use strict';

module.exports = {
  entry: './app.js',
  mode: "development",
  output: {
    filename: "bundle.js",
    path: "/" // <- :) 
  },
  devServer: {
    lazy: true
  }
};
```

**Comment by SpaceK33z** [comment] 2018-03-04 19:57
Thanks for figuring this out.

**Comment by ArnaudD** [comment] 2018-11-04 00:16
Setting the `filename` option fixed the problem in my case : 

```
devServer: {
  lazy: true,
  filename: 'index.html',
}
```

**Comment by NafaaBout** [comment] 2019-01-14 09:54
this is still the issue, I tried all the above-mentioned solutions and no one works. I'm just following the guides and I just tried to play with the different options when I reached the [Development](https://webpack.js.org/guides/development/) section.

```
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const WebpackManifestPlugin = require('webpack-manifest-plugin');

const distFolder = path.resolve(__dirname, 'dist');
const filename = 'bundle.js';

module.exports = {
  mode: 'development',
  entry: {
    app: './src/index.js',
    print: './src/print.js'
 },

  plugins: [
    new CleanWebpackPlugin(distFolder),

    new HtmlWebpackPlugin({
      title: 'Hello from Output Management'
    })
  ],

  devtool: 'inline-source-map',

  devServer: {
    open: true,
    contentBase: distFolder,
    port: 8008,
    compress: true
  },
  output: {
    filename: filename,
    path: distFolder
  }
}
```

**Comment by notiv-nt** [comment] 2019-05-23 20:57
Oooooooookey. i found it

## public/index.html
```
<script src="/bundle.js"></script>
```

## src/index.js
```
console.log('works');
```

## webpack.config.js
```
const path = require('path');

module.exports = {
  entry: './src/index.js',

  devServer: {
    contentBase: path.resolve(__dirname, 'public'),
  },

  output: {
    filename: 'bundle.js',
    // production
    // path: path.resolve('./dist'),
    // dev
    path: '/',
  },
};
```

## package.json
```
{
  "dependencies": {
    "webpack": "^4.32.2",
    "webpack-dev-server": "^3.4.1",
    "html-webpack-plugin": "^3.2.0",
    "webpack-cli": "^3.3.2"
  },
  "scripts": {
    "start": "webpack-dev-server --config webpack.config.js --lazy",
    "build": "webpack --config webpack.config.js"
  }
}
```

**Comment by evilebottnawi** [comment] 2019-05-24 10:32
So problem already solved? If not please create actual minimum reproducible test repo, thanks

**Comment by notiv-nt** [comment] 2019-05-24 10:46
it doesnt work with HtmlWebpackPlugin, but should

**Comment by evilebottnawi** [comment] 2019-05-24 11:21
@notiv-nt Speciously? __If not please create actual minimum reproducible test repo, thanks__

**Comment by notiv-nt** [comment] 2019-05-24 11:29
@evilebottnawi https://github.com/notiv-nt/webpack-lazy

**Comment by evilebottnawi** [comment] 2019-05-24 11:29
Thanks

**Comment by notiv-nt** [comment] 2019-05-24 11:31
#1: Why?
```
output: {
  // Production
  // path: path.resolve('./dist'),
  // Dev, yarn build throws an error
  path: '/',
},
```

#2:
dev-server should run plugins on start

**Comment by evilebottnawi** [comment] 2019-05-24 12:17
What you mean? Please clarify

**Comment by notiv-nt** [comment] 2019-05-24 12:19
1. output.path — absolute path
https://webpack.js.org/configuration/output#outputpath

2. htmlwebpackplugin does not work in webpack-dev-server

**Comment by GiancarlosIO** [comment] 2019-10-09 21:51
👀

**Comment by evilebottnawi** [comment] 2019-12-18 09:31
Lazy was removed from webpack-dev-middleware due incompatibility with webpack and will be removed in next release

**Closed by evilebottnawi** 2019-12-18 09:31 UTC
Labels: severity: 3 (broken), status: approved

**Comment by soryy708** [comment] 2021-08-20 03:14
> 
> 
> Lazy was removed from webpack-dev-middleware due incompatibility with webpack and will be removed in next release

Cool. Is there a migration guide?

**Comment by anshumanv** [comment] 2021-08-20 04:51
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
