### ISSUE TITLE
Webpack dev  server is not serving the latest compiled code

### ISSUE THREAD

**Issue by jorawarsingh** [webpack/webpack-dev-server#875] opened 2017-04-16 12:41 UTC
**bug**

**What is the current behavior?**
Webpack-dev-server is not updating the browser with latest built code

Webpack configuration

```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require("webpack");
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const ngtools = require('@ngtools/webpack');
var BrowserSyncPlugin = require('browser-sync-webpack-plugin');

module.exports = function (env) {
    const config = {
        entry: {
            polyfill: './src/polyfills.ts',
            vendor: './src/vendors.ts',
            main: './src/main.aot.ts'
        },
        resolve: {
            extensions: [".js", ".json", ".ts"]
        },
        output: {
            filename: '[name].js',
            path: path.resolve('dist')
        },
        module: {
            rules: [
                {
                    test: /\.ts?$/,
                    use: '@ngtools/webpack'
                },
                {
                    test: /\.css$/,
                    //exclude:'node_modules',
                    include: path.resolve(process.cwd(), 'src', 'app'),
                    use: ['to-string-loader', 'css-loader']
                }
            ]
        },
        plugins: [
            new HtmlWebpackPlugin({
                template: "./src/index.html"
            }),
            new ExtractTextPlugin("styles.css"),
            new webpack.ContextReplacementPlugin(
                /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
                __dirname
            ),
            new webpack.HotModuleReplacementPlugin()
        ],
        devtool: "source-map",
        target: "web",
        stats: "errors-only",
        devServer: {
            contentBase: path.join(__dirname, "dist"),
            compress: true,
            port: 8080,
            clientLogLevel: "none",
            historyApiFallback: true,
            watchContentBase: true
        }
    };
    return config;
};
```
for serve the application through npm script
`"start": "webpack-dev-server --progress --color --env.development --config tools/webpack.js"`

**What is the expected behavior?**
It should always serve the latest compiled code.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**

 "webpack": "2.2.1",
"webpack-dev-server": "2.4.2",

Every time i change a file i can see in console that webpack is compiling and browser is refreshing but output in browser is same as last compiled code

**UPDATE**

this is re-producible only when you use @ngtools/webpack plugin otherwise using ts-loader works just fine.

**Comment by HauntedSmores** [comment] 2017-04-23 22:54
I made an issue (#855) about this as well. Are you on windows?

**Comment by jorawarsingh** [comment] 2017-04-27 10:46
@HauntedSmores  Yes i am on window!

**Comment by xiiiAtCn** [comment] 2017-04-30 06:49
I met this issue as well. My version is 2.4.4 in windows

**Comment by oller** [comment] 2017-05-03 11:30
+1 for this issue,  I'm on a mac, don't think it's a windows specific issue.

**Comment by slaymaker1907** [comment] 2017-07-02 04:38
I am using webpack 3 and also have this issue on Windows.

**Comment by florian-g-** [comment] 2017-07-03 15:38
Same here with Linux Mint
"webpack": "^3.0.0"
 "webpack-dev-server": "^2.5.0"

**Comment by Andrew-Lahikainen** [comment] 2017-07-16 23:49
Same, Windows 10:
webpack 2.6.0
webpack-dev-server: 2.4.5

**Comment by JBouman** [comment] 2017-07-28 09:52
Also problems here,
Windows 10
webpack 3.4.1
webpack-dev-server: 2.4.5

**Comment by JesseSingleton** [comment] 2017-07-29 15:27
Having this issue too:
Windows 10 
Webpack 3.41
webpack-dev-server: 2.4.5

**Comment by donnysim** [comment] 2017-07-30 09:13
I'm having kind of the same issue, but mine is it serves latest compiled code at the start, but after some time it revert back to who knows how old compiled code until you restart the dev server, and the it just repeats.

Windows 10
Webpack 3.4.1
webpack-dev-server: 2.6.1

**Comment by MichaelZalla** [comment] 2017-08-05 06:28
I'm getting the same behavior. Initial compilation succeeds and all bundles load in the browser. Any subsequent change is (ostensibly) compiled by Webpack but is not available in the browser.

macOS 10.12.5
Webpack 3.4.1
webpack-dev-server 2.6.1
ts-loader 2.3.2
typescript 2.4.2

```
webpack: Compiled successfully.
webpack: Compiling...
Hash: 4c58a816563875a772dd
Version: webpack 3.4.1
Time: 1830ms
                               Asset      Size  Chunks                    Chunk Names
                       app.bundle.js    568 kB       0  [emitted]  [big]  app
                    vendor.bundle.js   5.37 MB       3  [emitted]  [big]  vendor
0.9bb86568f99493e5e6b1.hot-update.js   19.3 kB       0  [emitted]         app
9bb86568f99493e5e6b1.hot-update.json  43 bytes          [emitted]         
 [209] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {3} [built]
 [246] ./src/ts/app/.../foo.ts 7 kB {0} [built]
    + 300 hidden modules
webpack: Compiled successfully.
webpack: Compiling...
Hash: f7a6e2addadcc8d90ea0
Version: webpack 3.4.1
Time: 1618ms
                               Asset      Size  Chunks                    Chunk Names
                       app.bundle.js    568 kB       0  [emitted]  [big]  app
                    vendor.bundle.js   5.37 MB       3  [emitted]  [big]  vendor
0.4c58a816563875a772dd.hot-update.js   19.3 kB       0  [emitted]         app
4c58a816563875a772dd.hot-update.json  43 bytes          [emitted]         
 [209] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {3} [built]
 [246] ./src/ts/app/.../foo.ts 7 kB {0} [built]
    + 300 hidden modules
webpack: Compiled successfully.
```

**Comment by xusai2014** [comment] 2017-08-18 15:25
I have the same problem . Couldn't auto compile when some files are changed.

**Comment by shellscape** [comment] 2017-08-18 15:39
Folks, please don't follow up with "same" or "me too" comments unless you have additional info, aside from your environment/os, to add to the original issue. Please use the _reaction_ button to add a 👍 to the original post. 

That said, we'd happily review a pull request for this issue.

**Comment by Nexxado** [comment] 2017-08-26 13:30
I had the same issue, the culprit was [webpack-chunk-hash](https://github.com/alexindigo/webpack-chunk-hash).
Removing it from my webpack config solved the problem.

---

**My Packages:**
```json
"devDependencies": {
    "@types/facebook-js-sdk": "^2.8.3",
    "@types/node": "^8.0.25",
    "angular2-template-loader": "^0.6.2",
    "autoprefixer": "^7.1.2",
    "awesome-typescript-loader": "^3.0.4-rc.2",
    "codelyzer": "^3.1.2",
    "css-loader": "^0.28.5",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^2.28.0",
    "image-webpack-loader": "^3.2.0",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "node-sass": "^4.5.0",
    "postcss-flexbugs-fixes": "^3.2.0",
    "postcss-load-config": "^1.2.0",
    "postcss-loader": "^2.0.6",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "sass-loader": "^6.0.0",
    "script-ext-html-webpack-plugin": "^1.8.5",
    "style-loader": "^0.18.2",
    "tslint": "^5.7.0",
    "tslint-loader": "^3.4.2",
    "typescript": "^2.5.1",
    "webpack": "^3.5.5",
    "webpack-dev-server": "^2.7.1",
    "webpack-merge": "^4.1.0"
  },
  "dependencies": {
    "@angular/common": "^4.3.6",
    "@angular/compiler": "^4.3.6",
    "@angular/core": "^4.3.6",
    "@angular/forms": "^4.3.6",
    "@angular/http": "^4.3.6",
    "@angular/platform-browser": "^4.3.6",
    "@angular/platform-browser-dynamic": "^4.3.6",
    "@angular/router": "^4.3.6",
    "core-js": "^2.5.0",
    "rxjs": "^5.4.3",
    "zone.js": "^0.8.17"
  }
```

**Webpack config:**
```JS
module.exports = {
    entry: {
        'polyfills': './src/polyfills.ts',
        'vendor': './src/vendor.ts',
        'app': './src/main.ts'
    },
    output: {
        path: helpers.root('dist'),
        // publicPath: '/',
        filename: '[name].[chunkhash].js',
        chunkFilename: '[id].[chunkhash].chunk.js'
    },
    module: {
        rules: [{
            test: /\.ts$/,
            loaders: [{
                loader: 'awesome-typescript-loader',
                options: {
                    configFileName: helpers.root('src', 'tsconfig.json')
                }
            },
                'angular2-template-loader'
            ]
        }, {
            test: /\.html$/,
            loader: 'html-loader',
            query: {
                ignoreCustomFragments: [/\{\{.*?}}/],
                root: helpers.root('src'),
                attrs: ['img:src', 'img:ng-src']
            }
        }, {
            test: /\.(png|jpe?g|gif|svg)$/i,
            loaders: [
                'file-loader?hash=sha512&digest=hex&name=images/[name].[hash].[ext]',
                'image-webpack-loader'
            ]
        }, {
            test: /\.(eot|otf|ttf|woff|woff2)$/i,
            loader: 'file-loader?hash=sha512&digest=hex&name=fonts/[name].[hash].[ext]'
        }, {
            test: /\.scss$/,
            exclude: [helpers.root('src', 'app')],
            loader: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: [
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true,
                            importLoaders: true
                        }
                    }, {
                        loader: 'postcss-loader',
                        options: {
                            sourceMap: true
                        }
                    }, {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true
                        }
                    }
                ]
            })
        },
            {
                test: /\.scss$/,
                include: [helpers.root('src', 'app')],
                loaders: [
                    {
                        loader: 'raw-loader'
                    }, {
                        loader: 'postcss-loader',
                        options: {
                            sourceMap: true
                        }
                    }, {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true
                        }
                    }
                ]
            }
        ]
    },

    plugins: [
        // Workaround for angular/angular#11580
        new webpack.ContextReplacementPlugin(
            /angular(\\|\/)core(\\|\/)@angular/, // The (\\|\/) piece accounts for path separators in *nix and Windows
            helpers.root('./src'), // location of your src
            {} // your Angular Async Route paths relative to this root directory
        ),
        new webpack.optimize.CommonsChunkPlugin({
            name: ['vendor', 'polyfills', 'manifest'],
            minChunks: Infinity
        }),
        new webpack.optimize.ModuleConcatenationPlugin(),
        new webpack.HashedModuleIdsPlugin(),
        //new WebpackChunkHash(), // <---------- **Removed this**.
        new InlineManifestWebpackPlugin({
            name: 'webpackManifest'
        }),
        new HtmlWebpackPlugin({
            template: helpers.root('src', 'index.ejs'),
            filename: helpers.root('dist', 'index.html'),
            minify: {
                removeComments: true
            }
        }),
        new ScriptExtHtmlWebpackPlugin({
            defer: [/app/, /vendor/, /polyfills/],
            defaultAttribute: 'async'
        }),
        new ExtractTextPlugin({
            filename: '[name].[contentHash].css',
            allChunks: true
        })
    ],
    resolve: {
        extensions: ['.ts', '.js']
    },
    devServer: {
        historyApiFallback: true,
        stats: 'minimal',
        compress: true,
        inline: true,
        port: 8080
    }
};
```

**Comment by ThorstenBux** [comment] 2017-09-15 08:36
Same problem here for now I use:

```
    "watch": "webpack --progress --watch",
    "start": "concurrently -k -p \"[{name}]\" -n \"Webpack,HTTP-Server\" -c \"cyan.bold,green.bold\"  \"npm run watch\" \"npm run serve\" ",
    "serve": "http-server ./dist -p 8081 -o"
```

The only thing missing it auto-reload

**Comment by shellscape** [comment] 2017-09-15 12:54
This issue is quickly coming up on a 30-day stale date. Last call for a PR from the community. However, it looks like this issue is the cause of many different edge cases amongst those who have replied.

**Comment by aydun1** [comment] 2017-09-18 01:09
I had this problem serving through an Apache reverse proxy with mod_pagespeed enabled.
The page would reload when I changed a file, but it would remain the same.
Disabling mod_pagespeed fixed the issue for me.

**Comment by shellscape** [comment] 2017-09-20 12:04
folks, we've got a few workarounds listed in this issue for various cases that produce the same result. we'll reopen if someone can nail down a specific culprit within webpack-dev-server to discuss, and as always we'd happily accept a PR for review. given the age of this issue, the multiple edges that this can be experienced on, and the multiple workarounds, we're going to close this one.

**Closed by shellscape** 2017-09-20 12:04 UTC
Labels: bug, S5: Regression, X0: need more information, X5: PR welcome

**Comment by gzoritchak** [comment] 2017-10-03 23:22
I don't understand why this issue is closed. It's not working even with a basic configuration. The only workaround is to use webpack --watch.

**Comment by miks** [comment] 2017-10-04 04:00
Same for me. It's still not working.

**Comment by indrekru** [comment] 2017-10-04 13:47
Hello, had the same issue. Here's what fixed it for me:
I had `"webpack-dev-server --config webpack.config.dev.js --content-base ./ --port 1729 --progress --inline"` in my package.json, removing the `--content-base ./` fixed it, no need to specify the content-base really, it comes out of the box

**Comment by LeDanielH** [comment] 2017-10-07 20:23
removing devServer option `hot: true` fixed it for me.

**Comment by elliot-a** [comment] 2017-10-17 00:30
Sorry not sure why this is not being looked at, maybe I am missing something but is this not the most basic functionality?

**Comment by elliot-a** [comment] 2017-10-17 01:26
I had the same issue. 

Fix for me : disable all chrome plugins that have similar features to hot reload in my case "LiveReload" & "JetBrains IDE support".

**Comment by Randore** [comment] 2017-11-14 19:37
@indrekru what goes inside webpack.config.dev.js ?

**Comment by Asalem1** [comment] 2017-11-19 03:31
@gzoritchak Can't tell you how grateful I am for that comment.

**Comment by mribichich** [comment] 2017-11-27 13:56
In my case was using `WebpackChunkHash` and `ModuleConcatenationPlugin` together. 

Since `WebpackChunkHash` has a bug when using it with `ModuleConcatenationPlugin`
https://github.com/alexindigo/webpack-chunk-hash/issues/15

**Comment by ProductOfAmerica** [comment] 2017-12-22 03:25
Still getting this issue, workarounds don't work.

**Comment by stnever** [comment] 2018-01-05 12:28
FWIW, I was having a similar symptom (browser was always getting a stale version of the compiled files), which brought me to this issue, BUT in my case the problem was deeper: webpack wasn't actually picking up changes and recompiling.

I'm using a Xubuntu 16.04 guest in a Windows 8.1 Virtualbox host, using Node 8.6.0, and `webpack --watch` itself wasn't being notified of changes in the source files. I added the polling option to my `webpack.config.js` and it started working (even hot reloading):

```
module.exports = {
  ...
  watchOptions: {
    poll: true
  }
}
```

I knew there were problems with watches on shared Virtualbox folders, but this particular VM doesn't have any shared folders -- all files are inside the VM.

**Comment by leandroruel** [comment] 2018-01-06 23:14
i made a upgrade on my nodejs to 9.x and it's working now.

**Comment by 7rakir** [comment] 2018-01-06 23:23
Once I removed the `[name]` from `output.filename` of the Webpack config it started to work.
I checked and some of you have it as well. Might help you as a temporary workaround.

**Comment by JoaquinAraujo** [comment] 2018-01-11 16:03
Apparently, the problem was never solved :sob:

**Comment by KokoDoko** [comment] 2018-01-12 19:27
Nope. webpack-dev-server won't recompile or reload for me either, tried all the above fixes.

**Comment by usmansbk** [comment] 2018-01-14 19:02
Not working for me... so i just switched to using npm 'live-server' and 'webpack --watch'.

**Comment by carlosHerz** [comment] 2018-01-20 18:57
Adding this to the webpack.config.js file did the trick for me:

`devServer: {publicPath: '/public', port: 8080},`

**Comment by ujwalarak99** [comment] 2018-01-23 09:23
I had the same issue, upgrading packages worked for me :)

**Comment by bangnguyenanh** [comment] 2018-01-27 04:05
Still stuck on this issue :(

**Comment by antimatterjs** [comment] 2018-01-31 00:10
It seems to be working fine for me now on Phaser projects, but not on React projects.

For phaser projects, the solution was to make sure that code wasn't wrapped in a `window.onload = () => {}`

Not sure what's going on in React - is everyone here using React or are people using something else?

**Comment by usmansbk** [comment] 2018-01-31 23:07
So, I read the docs and it turns out that I needed to add same **publicPath** in **output** and **devServer** _properties_  like so,
```
 output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'js'),
    publicPath: path.resolve(__dirname, '/js/')
  },
  devServer: {
    contentBase: path.resolve(__dirname, './'),
    publicPath: path.resolve(__dirname, '/js/'),
  },
```

**Comment by 50shashwat** [comment] 2018-02-06 19:27
other workaround is to use `webpack --watch`  but hot reload is not there in that option.

**Comment by hamasho** [comment] 2018-02-11 13:27
This stackoverflow answer may be helpful.
https://stackoverflow.com/a/42717524

**Comment by idbartosz** [comment] 2018-02-21 14:45
Tested with simple app and everything works (node: v8.9.4; webpack: 3.11.0; webpack-dev-server: 2.11.1)

```
appRoot
├── node_modules
├── src
│   └── index.js
└── public
    ├── index.html
    ├── scripts
    │   └── bundle.js
    └── styles
        └── main.css
```

**index.html** 
```html
...
    <script src="scripts/bundle.js"></script>
  </body>
</html>
```

**webpack.config.js**
```js
const path = require('path')

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'public/scripts')
  },
  devtool: 'source-map',
  devServer: {
    contentBase: path.resolve(__dirname, 'public'),
    publicPath: '/scripts/',
    host: '127.0.0.1',
    port: 8080,
    open: true
  }
}
```

**Note**: it's important that `<script src="scripts/bundle.js">` points to the same path as `devServer.publicPath` (ie. http://127.0.0.1/scripts/bundle.js)

**Comment by turok1997** [comment] 2018-03-21 00:30
As I understand, you actually need neither `contentBase` property nor `publicPath` for basic run. `contentBase` just tells the path where to take static files, while `publicPath` says relative path in the url where to  serve your project at all.

**project structure**
`├───dist (read note below)*
└───src
 |   ├───css
 |   ├───js
 |   └───templates
├───webpack.config.js`
***** _actually dist could be empty, as webpack-dev-server serves files (except static ones maybe) from the memory, not FS_

webpack.config.js
`
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
const dist = path.resolve(__dirname, './dist');
//...
module.exports = {
	entry: {
		index: path.resolve(src, './js/index.js')
	},
	output: {
		filename: 'js/[name].bundle.js',
		path: dist
	},
        //...
	devServer: {
		hot: true,
		host: '0.0.0.0', //to serve all clients from any sources (e.g. local network)
		open: false
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: path.resolve(templates, './home.html'),
			filename: path.resolve(dist, './index.html')
		}),
		new webpack.NamedModulesPlugin(),
		new webpack.HotModuleReplacementPlugin()
	]
}`

**home.html**
`<html>
<body>
HELLO, WORLD!
</body>
</html>`

**package.json**
`"scripts": {
    ...
     "start": "SET NODE_ENV=development && webpack-dev-server --color"
  }`

**Comment by turok1997** [comment] 2018-03-21 00:36
As I understand, you actually need neither `contentBase` property nor `publicPath` for basic run. `contentBase` just tells the path where to take static files, while `publicPath` says relative path in the url where to  serve your project at all.

**project structure**
```
├───dist (read note below)*
└───src
|    ├───css
|    ├───js
|    └───templates
├───webpack.config.js
```
***** _actually `dist` could be empty, as webpack-dev-server serves files (except static ones maybe) from the memory, not FS_

**webpack.config.js**
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
const dist = path.resolve(__dirname, './dist');
//...
module.exports = {
	entry: {
		index: path.resolve(src, './js/index.js')
	},
	output: {
		filename: 'js/[name].bundle.js',
		path: dist
	},
        //...
	devServer: {
		hot: true,
		host: '0.0.0.0', //to serve all clients from any sources (e.g. local network)
		open: false
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: path.resolve(templates, './home.html'),
			filename: path.resolve(dist, './index.html')
		}),
		new webpack.NamedModulesPlugin(),
		new webpack.HotModuleReplacementPlugin()
	]
}
```

**home.html**

```
<html>
<body>
HELLO, WORLD!
</body>
</html>
```

**package.json**
```
"scripts": {
    ...
     "start": "SET NODE_ENV=development && webpack-dev-server --color"
  }
```

**Comment by liujiajun1** [comment] 2018-03-29 06:25
some problem

**Comment by jwu910** [comment] 2018-04-02 02:28
@liujiajun1 https://github.com/webpack/webpack-dev-server/issues/875#issuecomment-362101506 this worked for me.

**Comment by Moddest** [comment] 2018-04-05 09:48
I was having a similar issue using `webpack-dev-middleware` with `webpack-hot-middleware`. The updated bundle was not served after the initial build (first start) of dev server. The updated bundle was served only after forcing webpack to rebuild, e.g. saving any watched project file, and making a hard refresh in the browser.

The solution I've found is to force recompilation in the setup script using [devMiddleware.invalidate](https://github.com/webpack/webpack-dev-middleware#invalidate) method.

```js
const webpack = require('webpack');
const express = require('express');
const webpackDevMiddleware = require('webpack-dev-middleware');
const webpackHotMiddleware = require('webpack-hot-middleware');
const config = require('../webpack.config')('development');

const compiler = webpack(config);
const app = express();

const devMiddleware = webpackDevMiddleware(compiler, {
  publicPath: config.output.publicPath,
  historyApiFallback: true,
  hot: true,
  inline: true,
});

/**
 * This method call instructs a webpack-dev-middleware instance to recompile the bundle
 */
devMiddleware.invalidate();

app.use(webpackHotMiddleware(compiler, { noInfo: false }));
app.use(devMiddleware);


app.get('*', (req, res) => {
  const htmlBuffer = devMiddleware.fileSystem.readFileSync(`${config.output.path}/index.html`)

  res.send(htmlBuffer.toString())
})

app.listen(8181, 'localhost');
```

**Comment by BrentGrammer** [comment] 2018-04-10 15:51
Hi guys, just in case this might help someone else, I went through most of the solutions here which did not work for me and wound up just moving my project files from a nested directory they were in onto the desktop, and then webpack dev server worked as expected and the problem was solved.  I have no idea why this works, but just wanted to pass the (simple) solution on in case it helps someone else who has tried all of the above to see if just moving the project files will work.  Good luck...

**Comment by justengland** [comment] 2018-04-12 18:35
I have struggled with this for the better part of a day, then I found this help
https://medium.com/bcgdv-engineering/when-using-react-js-webpack-dev-server-does-not-bundle-c2d340b0a3e8

**Comment by GerkinDev** [comment] 2018-04-23 13:12
Hi,

Actually, I think this issue can be highly related to the environment, for at least one of the situations it happens.

* On my MacOS, everything works well, using the configuration bellow. When changing a file (a SCSS in my case), Webpack triggers a recompilation & the output file is updated.
* On my Ubuntu's Windows integration, the recompilation is triggered but the file is never updated. I have to restart the dev server at every changes to update the ouput file.

I don't have pure Linux OS to test, but I guess it would just work well...

So, here is my Webpack config, a bit cutted out

```javascript
const path = require('path');
const webpack = require('webpack');
const CleanWebpackPlugin = require('clean-webpack-plugin');

const mainConf = {
    entry: ['./assets/src/scripts/main.ts'],
    buildPath: __dirname,
    publicPath: 'assets/dist',
    url: 'http://localhost:8080/'
};

module.exports = {
    entry: mainConf.entry,
    mode: 'development',
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(mainConf.buildPath, mainConf.publicPath),
        chunkFilename: '[id].[chunkhash].chunk.js',
        publicPath: mainConf.url + mainConf.publicPath + '/',
    },
    resolve: {
        // Add `.ts` and `.tsx` as a resolvable extension.
        extensions: ['.ts', '.tsx', '.js']
    },
    module: {
        rules: [
            // A bunch of rules
        ]
    },
    plugins: [
        // Clean dist folder.
        new CleanWebpackPlugin([path.resolve(mainConf.buildPath, mainConf.publicPath)], {
            verbose: true // Write logs to console.
        }),

        // avoid publishing when compilation failed.
        new webpack.NoEmitOnErrorsPlugin(),
    ],
    devServer: {
        contentBase: './',
        historyApiFallback: true,
        inline: true,
        progress: true,
        publicPath: mainConf.url + mainConf.publicPath + '/',
        headers: { "Access-Control-Allow-Origin": "*" }
    },

    // pretty terminal output
    stats: { colors: true },
};
```

My `package.json` contains following dev-dependencies:

```json
{
    "webpack": "^4.6.0",
    "webpack-cli": "^2.0.15",
    "webpack-dev-server": "^3.1.3",
    "webpack-hot-middleware": "^2.22.1"
}
```

Environment infos:

* On Windows:
  * Node: 9.11.1
  * Windows 10 v1709 - 16299.371
  * Linux subsystem version 20170830.1 with ubuntu 16.04 LTS
* On MacOS:
  * Node: 9.10.1
  * MacOS: 10.10.4 High Sierra

GL HF with this issue ;) and thanks for the help !

**Comment by luckylooke** [comment] 2018-05-13 07:43
As I have mentioned [here](https://github.com/webpack/webpack-dev-server/issues/786#issuecomment-388607715). I was getting bundle file from /dist builded earlier, not the one served from memory.

This feature
`If you're having trouble, navigating to the /webpack-dev-server route will show where files are served. For example, http://localhost:9000/webpack-dev-server.` ([src](https://webpack.js.org/configuration/dev-server/#devserver))
saves me, I was able to understand how files are served, then I have changed it by [publicPath](https://webpack.js.org/configuration/dev-server/#devserver-publicpath-).
🎉

My problem was in my multiple webpack config environment, so files were served in named contexts.
Like:
http://localhost:9000/webpackConfig1/yourFiles
http://localhost:9000/webpackConfig2/yourFiles
...
etc

**Comment by Youfka** [comment] 2018-06-13 04:20
have the same problem, really can't find the issue,
I have "server" command in package.json:
`"server": "webpack-dev-server --mode development --open --watch"`
and this is my webpack config. I tried many solutions, it's compiling, but not building
`const path = require('path');
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
let conf = {
	entry: './src/index.js',
	output: {
		path: path.resolve(__dirname, './dist'),
		filename: 'main.min.js',
		publicPath: 'dist/'
	},
	devServer: {
		contentBase: path.join(__dirname, "dist"),
		overlay: true,
		watchContentBase: true
	},
    	new ExtractTextPlugin("style.css"),
    	new webpack.NamedModulesPlugin(),
	    new webpack.HotModuleReplacementPlugin()
  	]
};

module.exports = (env, options) => {
	let production = options.mode === 'production';
	conf.devtool = production ? false : 'eval-sourcemap';
	return conf;
}`

**Comment by kgagnon-seedbox** [comment] 2018-09-18 18:47
webpack-dev-server needs to be installed globally to "watch" the project.

sudo npm i webpack-dev-server

**Comment by mahmoudafifi414** [comment] 2018-10-31 16:15
in webpack.config.js write 

module.exports = {
  devServer: {
    watchOptions: {
      poll: true
    }
  }
};

for further information see this link
https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-

**Comment by mahmoudafifi414** [comment] 2018-10-31 16:26
if the webpack not serving code changes so 
in webpack.congif.js write :

module.exports = {
  //...
  devServer: {
    watchOptions: {
      poll: true
    }
  }
};

for further information see this link:
https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-

**Comment by albertian** [comment] 2018-11-03 11:48
Hi guys.
I'm a newbie in Webpack and I got the same problem.
But now it works good. Even without bundle.js file my server works correctly.
command: `node_modules/.bin/webpack-dev-server --config webpack.config.js --hot`
webpack.config.js
```
output: {
        path: __dirname + '/js',
        publicPath: '/js',
        filename: 'bundle.js'
    },
    devServer: {
        contentBase:__dirname + '/',
        publicPath: '/js'
    },
```
Both _publicPath_ are url path, so not need to put your file path here.
After my changes my webpage reloades after each file change.
I hope it will be helpful so someone.

**Comment by khyamay** [comment] 2018-11-06 10:37
like @albertian mentioned and has shown in the example publicPath for output and devServer needs to be same.

> webpack-dev-server doesn’t serve the actual generated bundle from file system. Rather it'll watch your source files, and recompile the bundle whenever they are changed. This modified bundle is served directly from memory.

[Why webpack-dev-server Live-Reload Is Not Working](https://medium.com/code-oil/burning-questions-with-answers-to-why-webpack-dev-server-live-reload-does-not-work-6d6390277920)

[Webpack — Understanding the ‘publicPath’ mystery](https://medium.com/@raviroshan.talk/webpack-understanding-the-publicpath-mystery-aeb96d9effb1)

These two articles explains in deep about why live reloading and publicPath.

**Comment by kistora** [comment] 2018-11-25 16:20
I'm on ubuntu 18.04 and i fix this issue following [Visual Code guidelines](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc).

Hope it will help.

**Comment by mathstracted** [comment] 2018-11-27 02:39
Not sure if the same issue is happening for other that is happening for me.
My problem was that I had created a class but had forgotten to export it. And I started to use the class directly in one of other typescript file in the same module without having to export it. The ide I was using was vs code. I guess it thought the class was in global module and just didn't report error. 
In my bundled code code would execute upto the point where the I started using the class and after instantiating the could would just suspend(I don't know what else to call it), without reporting any error. To me it was looking like the webpack was not compiling the code. 

After going line by line, I found out at which point code stopped. After properly exporting and importing resolved the issue...

**Comment by EdgardoRodriguezSolano** [comment] 2018-11-28 03:51
Live-reload was not working for me. This might be a really dumb error, but I had missed (or deleted) the `<meta charset="utf-8" />` tag in the `<head></head>` section of my index.html. It's working like a charm now.

**Comment by neilmonroe** [comment] 2018-12-27 04:53
> like @albertian mentioned and has shown in the example publicPath for output and devServer needs to be same.
> 
> > webpack-dev-server doesn’t serve the actual generated bundle from file system. Rather it'll watch your source files, and recompile the bundle whenever they are changed. This modified bundle is served directly from memory.
> 
> [Why webpack-dev-server Live-Reload Is Not Working](https://medium.com/code-oil/burning-questions-with-answers-to-why-webpack-dev-server-live-reload-does-not-work-6d6390277920)
> 
> [Webpack — Understanding the ‘publicPath’ mystery](https://medium.com/@raviroshan.talk/webpack-understanding-the-publicpath-mystery-aeb96d9effb1)
> 
> These two articles explains in deep about live reloading and publicPath.

The "Why webpack-dev-server Live-Reload Is Not Working" article is what everyone here should read. This contains most of the answers to the questions here that keep getting repeated.

Thanks for pointing these out, @khyamay ! It helped me understand how webpack-dev-server works.

Having local files in an output dir from webpack-cli *will cause problems*. Remove them if you are going to use the dev server.

**Comment by xeptore** [comment] 2019-02-08 12:22
i had the same problem, i tried all of these suggestions, but none of them woks for me.
finally, i tried to add a `newline` at the end of the `webpack` configuration and it just worked!
awesome!

**Comment by Mozar10** [comment] 2019-03-06 03:25
Restarting the computer fixed it for me

**Comment by DrakeXiang** [comment] 2019-03-14 10:17
Just figured out sometimes it's about case sensitivity, I'm on macOS, and I misspelled route path from `/Auth` to `/auth`, the issue is gone when I fix the typo, hope helped

**Comment by lestrato** [comment] 2019-03-27 20:54
I spilled a cup of coffee on my keyboard and now it started working

**Comment by pmontu** [comment] 2019-04-04 12:06
I increased fs.inotify.max_user_watches=524288 and it worked
https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

**Comment by Msey** [comment] 2019-06-05 09:27
the resolution for me was to define paths properly
`
    output: {
        filename: 'bundle.js',
        publicPath: '/assets/',
        path: path.resolve(__dirname, './wwwroot/assets/'),        
    }
`
notice that the public path must have `/` on each side

**Comment by engelmav** [comment] 2019-06-07 21:23
> i had the same problem, i tried all of these suggestions, but none of them woks for me.
> finally, i tried to add a `newline` at the end of the `webpack` configuration and it just worked!
> awesome!

What the hell...

**Comment by pattoM** [comment] 2020-02-27 06:11
I encountered this on a Django + React app. I was on Kali linux, testing on Chrome. Fix was to run the django app with --nostatic flag because the older files were being cached. Please note that in my case, latest version was being served initially but suddenly stopped.

**Comment by CallmeKingsley** [comment] 2020-04-12 16:54
try adding the following code to your webpack.config.js file.
 devServer: {
    watchContentBase: true
  },

**Comment by zzwx** [comment] 2020-06-12 21:19
Removing `experimentalWatchApi: true` from ts-loader options helped me!

**Comment by ascott18** [comment] 2020-07-02 21:06
The cause of this issue for me was one of the various caches stored in `node_modules/.cache`. Deleting that folder instantly fixed it for me. I discovered these by watching Process Monitor for file accesses by node.exe on initial startup of my application.

![image](https://user-images.githubusercontent.com/5017521/86409222-41d29b80-bc6d-11ea-9685-17ddceda7c40.png)

**Comment by kaczor6418** [comment] 2020-07-18 14:42
You should check **`publicPath`** attribute of **`output`** config object. If you do not have it you should add this `attribute` to this object, then webpack will know when files should be changed (if any file of `publicPath` will be changed then webpack dev-server should recompile files and serve updated context).
```javascript
  ...
  output: {
    publicPath: '/',
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
 ...
````

**Comment by lzxxxxx** [comment] 2020-08-12 08:53
Check your file case.
My situation: the file real name: A.js. But I import it with the lowercase a.js
webpack can't watch my file change, can't generate new vendor for my code change in A.js.

**Comment by veaba** [comment] 2021-01-23 13:40
I just encountered this problem and solved it.
Remove your node_modules, and re install it.

**Comment by MITREDan** [comment] 2021-06-30 19:03
I thought I was having this problem. Turned out what was ACTUALLY happening is that I had webpack dev server running via some zombified process (no idea how it happened) which was taking up port 8080, which is how I have it configured to run; it was automatically incrementing the port number to 8081, and I didn't notice it in the output; just went to my standard localhost:8080, and voila: old version of the application running. Dumb error but easy to miss!
