### ISSUE TITLE
TypeError: Cannot read property 'headers' of null at Server.socket.on (***/node_modules/webpack-dev-server/lib/servers/SockJSServer.js:68:32)

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack-dev-server#2199] opened 2019-08-16 04:30 UTC
- Operating System: Windows 10
- Node Version: 12.8.1
- NPM Version: 6.10.3
- webpack Version: 4.39.2
- webpack-dev-server Version: since 3.5.0
- Browser: Chrome 76

- [X] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior

`connection` should not be null

### Actual Behavior

`TypeError: Cannot read property 'headers' of null at Server.socket.on (***/node_modules/webpack-dev-server/lib/servers/SockJSServer.js:68:32)`

### For Bugs; How can we reproduce the behavior?

This bug is difficult to reproduce. It happens occasionally.

https://github.com/webpack/webpack-dev-server/blob/2d44ef8088db2312516274cc2d5edda348064712/lib/servers/SockJSServer.js#L65-L69

line 67 should become

```js
if (connection) {
  f(connection, connection.headers)
}
```

**Comment by evilebottnawi** [comment] 2019-08-16 11:22
Please provide minimum reproducible test repo, i can't reproduce

**Comment by Loonride** [comment] 2019-08-16 14:34
Seems like an unsolved issue in sockjs https://github.com/sockjs/sockjs-node/issues/121

**Comment by evilebottnawi** [comment] 2019-08-16 15:14
@Loonride i am thinking we should mark this as bug :disappointed:

**Comment by cereallarceny** [comment] 2019-08-18 13:58
I have this issue as well.  Here's my `webpack.config.js`:

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  entry: './index.js',
  output: {
    filename: 'index.js',
    path: __dirname + '/dist'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: ['babel-loader']
      }
    ]
  },
  plugins: [
    new CopyPlugin([{ from: './*.css', to: './' }]),
    new HtmlWebpackPlugin({
      template: './index.html'
    })
  ]
};
```

And my `package.json`:

```json
{
  "name": "with-grid",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --hot --inline --open",
    "build": "rm -rf dist && webpack --mode=production",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "",
  "devDependencies": {
    "babel-loader": "^8.0.6",
    "copy-webpack-plugin": "^5.0.4",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.39.1",
    "webpack-cli": "^3.3.7",
    "webpack-dev-server": "^3.7.2"
  },
  "dependencies": {
    "syft.js": "file:../.."
  }
}
```

The exact bug report:

```
/Users/cereallarceny/Dropbox/Development/openmined/code/syft.js/examples/with-grid/node_modules/webpack-dev-server/lib/servers/SockJSServer.js:67
      f(connection, connection.headers);
                               ^

TypeError: Cannot read property 'headers' of null
    at Server.<anonymous> (/Users/cereallarceny/Dropbox/Development/openmined/code/syft.js/examples/with-grid/node_modules/webpack-dev-server/lib/servers/SockJSServer.js:67:32)
    at Server.emit (events.js:203:13)
    at App.emit (/Users/cereallarceny/Dropbox/Development/openmined/code/syft.js/examples/with-grid/node_modules/sockjs/lib/sockjs.js:196:29)
    at /Users/cereallarceny/Dropbox/Development/openmined/code/syft.js/examples/with-grid/node_modules/sockjs/lib/transport.js:111:25
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

OS: Mojave 10.14.6
Browser: Brave (Chrome) - Version 0.67.124 Chromium: 76.0.3809.100 (Official Build) (64-bit)
NPM Version: 6.10.3
Node Version: 12.8.0

**Comment by MattSchlatter** [comment] 2019-08-20 00:09
We've been running into this issue as well. It's generally very intermittent, but I was able to reproduce it consistently by maxing out the cpu/memory utilization of the machine our app is running on (using a prime95 torture test), then navigating to the app. It only appears to occur when navigating directly to a url, or when refreshing the page.

Checking the console output in chrome shows the following errors: 
```
Invalid Host/Origin header
error @ index.js:169
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
SockJS._transportMessage @ main.js:276
EventEmitter.emit @ emitter.js:50
(anonymous) @ sender-receiver.js:23
EventEmitter.emit @ emitter.js:50
(anonymous) @ polling.js:30
EventEmitter.emit @ emitter.js:50
EventSourceReceiver.es.onmessage @ eventsource.js:21
index.js:172

[WDS] Disconnected!
close @ index.js:172
(anonymous) @ socket.js:26
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:360
nrWrapper @ newrelic.js:369
setTimeout (async)
nrWrapper @ newrelic.js:369
SockJS._close @ main.js:348
SockJS._transportMessage @ main.js:288
EventEmitter.emit @ emitter.js:50
(anonymous) @ sender-receiver.js:23
EventEmitter.emit @ emitter.js:50
(anonymous) @ polling.js:30
EventEmitter.emit @ emitter.js:50
EventSourceReceiver.es.onmessage @ eventsource.js:21
index.js:172

[WDS] Disconnected!
close @ index.js:172
(anonymous) @ socket.js:26
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:360
nrWrapper @ newrelic.js:369
setTimeout (async)
nrWrapper @ newrelic.js:369
SockJS._close @ main.js:348
SockJS._transportClose @ main.js:307
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onclose @ websocket.js:49
websocket.js:6

WebSocket connection to 'ws://localhost:7777/sockjs-node/513/fc3v2vie/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
WebSocketBrowserDriver @ websocket.js:6
WebSocketTransport @ websocket.js:32
SockJS._connect @ main.js:219
SockJS._receiveInfo @ main.js:193
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
(anonymous) @ info-receiver.js:67
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
(anonymous) @ info-ajax.js:37
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
xhr.onreadystatechange @ abstract-xhr.js:124
nrWrapper @ newrelic.js:369
```

It's also worth mentioning that adding either of the following two bits to our webpack.config.js file resolves the issue if you do what I said above; however, we're still seeing the failure occur in our linux docker containers in CircleCI. Those settings are:
```
devServer: {
    hot: false,
    inline: false,
    liveReload: false
  },

  optimization: {
    splitChunks: {
      chunks: 'all'
    }
  }
```

**Comment by Loonride** [comment] 2019-08-20 00:34
> @Loonride i am thinking we should mark this as bug

@evilebottnawi Do you mean we should put the fix on `master`, not `next`? The core problem is with sockjs but we can at least prevent the TypeError

**Comment by rahuls360** [comment] 2019-08-20 04:17
I assume this issue is with webpack-dev-sever@3.8.0

I fixed the issue by removing the `^` symbol from my package.json

`"webpack-dev-server": "^3.7.2"`
to
`"webpack-dev-server": "3.7.2"`

Type `npm install`

Then your issue will be fixed. The caret symbol allows minor releases from the package to be installed. Here we are disabling that and keeping version 3.7.2 (which was working for me earlier)

**Comment by evilebottnawi** [comment] 2019-08-20 10:26
@Loonride yes, fix should be in master

**Closed** 2019-08-20 13:59 UTC

**Comment by alanwhy** [comment] 2019-08-29 01:49
什么时候可以发布新的版本啊，，我要被这个问题搞死了，或者有没有什么其他的解决方法啊

**Comment by nekoassassin** [comment] 2019-08-29 07:21
> 什么时候可以发布新的版本啊，，我要被这个问题搞死了，或者有没有什么其他的解决方法啊，一直在等新的版本出来

This has been fixed in their master branch, but not yet released. I too would like a release soon, as it definitely impacts our automation, but in the meantime you can get the fix by pointing your package manager to their master branch. In NPM, that would mean changing the package.json reference to: "webpack-dev-server": "webpack/webpack-dev-server".

Hopefully this helps =)

**Comment by alanwhy** [comment] 2019-08-29 07:25
> > 什么时候可以发布新的版本啊，，我要被这个问题搞死了，或者有没有什么其他的解决方法啊，一直在等新的版本出来
> 
> This has been fixed in their master branch, but not yet released. I too would like a release soon, as it definitely impacts our automation, but in the meantime you can get the fix by pointing your package manager to their master branch. In NPM, that would mean changing the package.json reference to: "webpack-dev-server": "webpack/webpack-dev-server".
> 
> Hopefully this helps =)

ok，我对这个不太懂，我现在是降低到3.7.0的版本了，暂时没有问题，而且具体没有研究过vue-cli3初始化的项目为什么package.json中的webpack是一个，，而不是分开的

**Comment by nekoassassin** [comment] 2019-08-29 08:30
> > > 什么时候可以发布新的版本啊，，我要被这个问题搞死了，或者有没有什么其他的解决方法啊，一直在等新的版本出来
> > 
> > 
> > This has been fixed in their master branch, but not yet released. I too would like a release soon, as it definitely impacts our automation, but in the meantime you can get the fix by pointing your package manager to their master branch. In NPM, that would mean changing the package.json reference to: "webpack-dev-server": "webpack/webpack-dev-server".
> > Hopefully this helps =)
> 
> ok，我对这个不太懂，我现在是降低到3.7.0的版本了，暂时没有问题，而且具体没有研究过vue-cli3初始化的项目为什么package.json中的webpack是一个，，而不是分开的

Sorry, Google Translate is failing me here. I'm not sure what you're asking. I will say that if you've found a working version, go with that for now until the team pushes a new one, as the issue is fixed on master, but not yet pushed out. Hopefully they push it soon 🤞

**Comment by alanwhy** [comment] 2019-08-29 08:32
> > > > 什么时候可以发布新的版本啊,,我要被这个问题搞死了，或者有没有什么其他的解决方法啊，一直在等新的版本出来
> > > 
> > > 
> > > 这已经在他们的主分支中修复，但尚未发布。我也希望尽快发布，因为它肯定会影响我们的自动化，但与此同时，您可以通过将软件包管理器指向其主分支来获得修复。在NPM中，这意味着将package.json引用更改为：“webpack-dev-server”：“webpack / webpack-dev-server”。
> > > 希望这有助于=）
> > 
> > 
> > OK，我对这个不太懂，我现在是降低到3.7.0的版本了，暂时没有问题，而且具体没有研究过VUE-CLI3初始化的项目为什么的package.json中的的WebPack是一个,,而不是分开的
> 
> 对不起，谷歌翻译让我失望了。我不确定你在问什么。我要说的是，如果你找到了一个正常工作的版本，那么现在就去使用它，直到团队推出一个新版本，因为问题已在master上修复，但尚未推出。希望他们很快推出它🤞

ok thanks

**Comment by charlex** [comment] 2019-09-04 05:56
Does anyone have any further information on the release schedule to resolve this?

**Comment by rwlnd** [comment] 2019-09-04 23:22
stumbled upon this issue as this issue actually occurs randomly for me when using `ng serve`

```
Angular CLI: 8.3.3
Node: 10.16.2
OS: win32 x64
Angular: 8.2.5
```

**Comment by gotnull** [comment] 2019-09-05 01:38
Getting the exact same problem:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle storm@0.0.1~prestart: storm@0.0.1
6 info lifecycle storm@0.0.1~start: storm@0.0.1
7 verbose lifecycle storm@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle storm@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\inetpub\wwwroot\storm\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\oracle\product\11.2.0\dbhome_2\bin;c:\oracle\product\11.2.0\dbhome_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\sqllite;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\fcus0001\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\fcus0001\AppData\Roaming\npm;c:\program files\nodejs\protractor
9 verbose lifecycle storm@0.0.1~start: CWD: C:\inetpub\wwwroot\storm
10 silly lifecycle storm@0.0.1~start: Args: [ '/d /s /c', 'ng serve --deploy-url /' ]
11 silly lifecycle storm@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle storm@0.0.1~start: Failed to exec start script
13 verbose stack Error: storm@0.0.1 start: `ng serve --deploy-url /`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid storm@0.0.1
15 verbose cwd C:\inetpub\wwwroot\storm
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error storm@0.0.1 start: `ng serve --deploy-url /`
22 error Exit status 1
23 error Failed at the storm@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by gotnull** [comment] 2019-09-05 01:51
> "webpack-dev-server": "webpack/webpack-dev-server"

I don't know what you mean by this. There's no such thing as an npm package at ``webpack/webpack-dev-server``

**Comment by collinbarrett** [comment] 2019-09-05 19:10
I see this issue intermittently when running an Angular app from a VS Code terminal. If I close VS Code and run it from a normal cli, I don't seem to ever see it...

**Comment by nekoassassin** [comment] 2019-09-05 20:40
> > "webpack-dev-server": "webpack/webpack-dev-server"
> 
> I don't know what you mean by this. There's no such thing as an npm package at `webpack/webpack-dev-server`

Apologies, I omitted the #master portion in my comment. I updated the comment, but just for clarity's sake, it should be:
```"webpack-dev-server": "webpack/webpack-dev-server#master"```
This will point you to the current master branch, instead of any released version.

**Comment by jtrump70** [comment] 2019-09-06 01:29
@cereallarceny try adding the following in your webpack.config.js: 
`  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 3000
  },`

I was having the same issue and this seemed to resolve it.

**Comment by chenhailun2006** [comment] 2019-09-12 06:20
@jtrump70 it's really works, and there's one thing should be noticed is that you should confirm that's not another server(port 3000) which you run before, you can change another port to test it

**Comment by Harmonickey** [comment] 2019-09-16 14:35
The fix is released!  Seems to be working for me so far, give it few days though...

**Comment by iyer24** [comment] 2019-10-01 08:32
I still don't see a fix. Any workaround?

**Comment by evilebottnawi** [comment] 2019-10-01 10:42
@iyer24 update your deps and lock file

**Comment by Willem-Merwe** [comment] 2019-10-01 13:56
> @iyer24 update your deps and lock file

Sorry, how would I go about doing that?

**Comment by evilebottnawi** [comment] 2019-10-01 14:09
`npm update`/`yarn upgrade` (hardcore: `rm -r node_modules`, `rm -r package-lock.json` and `npm i`)

Please read how to use package manager

**Comment by kdreally** [comment] 2020-12-22 08:58
I got this error when doing npm start.

I closed vlcplayer and did npm start again, and the problem went away.

once the app is running, i can run vlc player again.

this is most likely an issue with some application opening a port that either sockjsserver wants to open, or does not respond correctly to sockjsserver connection.
