### ISSUE TITLE
Invalid WebSocket url in a Chrome extension context

### ISSUE THREAD

**Issue by OriginalEXE** [webpack/webpack-dev-server#2743] opened 2020-09-22 18:43 UTC
- Operating System: Windows 10
- Node Version: 12.18.2
- NPM Version: 6.14.5
- webpack Version: 4.44.1
- webpack-dev-server Version: 3.11.0
- Browser: Chrome 85.0.4183.121

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
Webpack dev server `transportMode: 'ws'` should work as expected when loaded inside a context of a Chrome extension popup.

### Actual Behavior
Webpack dev server `transportMode: 'ws'` throws an error that the url is not valid. The problem is with this line of code

```
_this.client = new WebSocket(url.replace(/^http/, 'ws'));
```

found in WebsocketClient.js

It assumes that the protocol will be one of `http:`/`https:`, but in chrome extension popup it's actually `chrome-extension:`

### For Bugs; How can we reproduce the behavior?
Set the `transportMode: 'ws'` config to the dev server, and use it to serve a browser extension popup

**Comment by CPatchane** [comment] 2020-12-01 14:19
Since in the v4, `transportMode` is now `ws` by default, we now get that error by default. At least, on my side, I am getting it in chrome.

**Comment by alexander-akait** [comment] 2020-12-01 14:29
@CPatchane Please create reproducible test repo

**Comment by CPatchane** [comment] 2020-12-01 14:30
I got it in a big project, I'll try to reproduce it in a minimal repo 👍

**Comment by ylemkimon** [comment] 2021-02-17 20:13
Possibly fixed in `master` via #2954. Could you test it?

**Comment by alexander-akait** [comment] 2021-03-26 12:04
Yep, fixed, feel free to feedback

**Closed by alexander-akait** 2021-03-26 12:04 UTC
