### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by MitchTalmadgeUofU** [webpack/webpack-dev-server#1373] opened 2018-04-10 17:39 UTC
* Operating System: Windows 10 x64
* Node Version: 7.3.0
* NPM Version: 3.10.10
* webpack Version: 4.5.0
* webpack-dev-server Version: 3.1.3

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/MitchTalmadgeUofU/Digital-Story/tree/a73fbbf8c5d0f90d9190232e976407610eb5fb7e

### Expected Behavior

When I visit `http://localhost:9000/`, it should display the index.html page generated by HtmlWebpackPlugin.

### Actual Behavior

When I visit `http://localhost:9000/`, I receive a 404: `Cannot GET /`. If I compile the index.html using my production webpack config -- so that the files are generated on the hard drive and not in memory -- I can then load webpack dev server and the index.html file is served (but does not update when I make changes to the template).

### For Bugs; How can we reproduce the behavior?

1. Clone the repository
* **Edit: We discovered that this error only occurs on Windows, and only if you clone into a directory with _spaces_ in the path. No spaces? No error.** 

2. Checkout this tree: `git checkout a73fbbf8c5d0f90d9190232e976407610eb5fb7e .`
3. Install dependencies: `npm i`
4. Start dev-server: `npm run dev-web`.
* **Edit: I forgot to remove part of my `dev-web` script; open `package.json` and replace the `dev-web` script contents with:**

```
webpack-dev-server --config webpack/webpack.dev.config.js --progress
```

5. Visit http://localhost:9000 and see the error message.
6. Stop the dev-server.
7. Compile the production files: `npm run build-web`.
8. Start dev-server again: `npm run dev-web`.
9. Visit http://localhost:9000 and see "Hello World".

**Comment by tresko** [comment] 2018-04-10 17:49
I also have the same problem that only appears on Windows, but on Mac and Ubuntu, it works fine.

- Operating System: Windows 10 x64
- Node Version: 9.11.1
- Yarn Version: 1.3.2
- webpack Version: 4.5.0
- webpack-dev-server Version: 3.1.3

**Comment by MitchTalmadgeUofU** [comment] 2018-04-10 18:29
I downgraded back to these versions:

```
"html-webpack-plugin": "^2.30.1",
"webpack": "^3.8.1",
"webpack-dev-server": "^2.9.3"
```

And I can confirm that it works again. This seems to be a problem with upgrading to webpack 4

**Comment by tresko** [comment] 2018-04-10 19:25
@MitchTalmadgeUofU you can use the following versions; these are the last ones that worked for me:

> "html-webpack-plugin": "^3.2.0",
>  "webpack": "^4.5.0",
>  "webpack-dev-server": "3.1.0"


I receive `Cannot GET /` on Windows for all versions which are higher than 3.1.0.

Is this related? https://github.com/webpack/webpack-dev-middleware/issues/270

**Comment by GuacheSuede** [comment] 2018-04-10 20:24
@tresko I verify your solution works 👍

**Comment by GuacheSuede** [comment] 2018-04-10 21:03
However webpack dev middleware issue still persists

**Comment by ejnu** [comment] 2018-04-12 04:37
ok i got this - thanks to this issue - https://github.com/webpack/webpack-dev-server/issues/1375
for now - you need remove spaces from the project path

**Comment by s-h-a-d-o-w** [comment] 2018-05-01 16:11
> I receive Cannot GET / on Windows for all versions which are higher than 3.1.0.

Odd, 3.1.1 still works for me.

Just created a project from scratch based on the official webpack docs, got the "Cannot GET /" error, downgraded to 3.1.1 and everything is good.

**Comment by nguyenkhois** [comment] 2018-05-10 07:19
This issue has been fixed in version 3.1.4. It works finne for me now 👍  Thanks so much! 🥇

**Comment by theliveseven** [comment] 2018-06-11 09:22
@nguyenkhois I had the same issue, upgraded to 3.1.4, and it has been fixed! Thanks!

**Comment by dandohotaru** [comment] 2018-06-11 11:19
@nguyenkhois, @theliveseven can you you mention what webpack version (and plugins) do you rely on?

**Comment by nguyenkhois** [comment] 2018-06-12 15:34
@dandohotaru
- Webpack Dev Server 3.1.1 or 3.1.4 works fine for me and I rely on 3.1.1. I have not used so much this version 3.1.4 but I think it works very well.
- Webpack - I use the latest version and it works without a problem.
- Plugins: You decide what fits your project. You can view my simple example [here](https://github.com/nguyenkhois/build-environments/blob/master/simple-react-css-build-env/package.json)

Have a nice day!

**Comment by dandohotaru** [comment] 2018-06-12 16:14
@nguyenkhois well, the only reason i'm asking is because i couldn't have webpack-dev-server refresh as expected for any of the versions i've tried (3.1.x)
Check my dependencies in [here](https://github.com/dandohotaru/labs.katas/blob/kata012/package.json)
In the meantime i tackle the problem with lite-server instead :)

**Comment by theliveseven** [comment] 2018-06-13 00:31
@dandohotaru  

- webpack : 4.6.0 
-  webpack-dev-server: 3.1.4

I was previously using **webpack-dev-server:3.1.3**. I had no issue with this before because I was only using my mac for development. I encountered the issue when I set up the project in my PC (Windows 10). Upgrading the webpack-dev-server to version 3.1.4 fixed the issue. 

Here is a part of my **package.json** file :)

```
"webpack": "^4.6.0",
"webpack-bundle-analyzer": "^2.11.1",
"webpack-cli": "^2.0.14",
"webpack-dev-server": "^3.1.4",
"webpack-merge": "^4.1.2"
```

**Comment by dandohotaru** [comment] 2018-06-25 13:43
As far as I'm concerned I've fixed the issue by 
* making sure a base path is defined
* making sure all 404s are redirected to index.html

```
module.exports = {
  ...
  output: {
    ...
    publicPath: '/'
  },
  devServer: {
    historyApiFallback: true,
  },
}
```

```
"webpack": "^4.12.1",
"webpack-cli": "^3.0.8",
"webpack-dev-server": "^3.1.4",
"webpack-merge": "^4.1.3"
```

**Comment by hz9527** [comment] 2018-07-08 08:33
I also have the same problem(entrypoint undefined = index.html). first,  I thought it was a bug of webpack4, but I built it by the config, everything is normal. so I thought it was a bug of webpack-dev-server. but I it not work with some other versions. finally, I add "context: resolve('../')",  good running!

**Comment by PatelDipen92** [comment] 2018-08-01 14:02
I am using 

"webpack": "^4.16.3",
"webpack-cli": "^3.1.0",
"webpack-dev-server": "^3.1.5"

still getting the error

**Comment by nguyenkhois** [comment] 2018-08-01 14:34
@PatelDipen92 Have you tried to use "./" before `output` and ` dist`?:
````
var path = require('path');

module.exports = {
    entry: './src/app.js',


    output: {
        path: path.join(__dirname, './output'),
        filename: 'bundle.js'
    },

    devServer: {
        contentBase: path.join(__dirname, './dist'),
        compress: true,
        port: 9000
    }
}
````

I use Windows 10 and WDS works fine for me. You can see [here](https://github.com/nguyenkhois/build-environments/tree/master/react-redux-typescript) on my repo.

**Comment by PatelDipen92** [comment] 2018-08-01 14:40
@nguyenkhois I have tried that also but still getting the same error. I am using Windows 8.1

```
    entry: './src/app.js',

    output: {
        path: path.join(__dirname, './output'),
        filename: 'bundle.js',
        publicPath: '/'
    },

    devServer: {
        contentBase: path.join(__dirname, './dist'),
        compress: true,
        port: 9000,
        historyApiFallback: true
    }
```

**Comment by hz9527** [comment] 2018-08-01 15:04
Duplicate of #1421 e...I try it again.  entryPoint undefined = index.html. but I can use devServer. you can set context and set devServer.publicPath = '/' (not './'). so you can get page with inject js & css. @PatelDipen92

**Comment by dandohotaru** [comment] 2018-08-01 15:14
the setup bellow works for me as expected for quite some time by now...

_webpack.config.js_

```
const path = require("path")
const webpack = require('webpack')

module.exports = {
  entry: {
    app: './src/app.js'
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: '[name].bundle.js',
    publicPath: '/',
  },
  ...
```

_webpack.dev.js_

```
const path = require("path")
const webpack = require('webpack')
const merge = require('webpack-merge')
const common = require('./webpack.config.js')

module.exports = merge(common, {
  mode: 'development',
  devtool: 'source-map',
  devServer: {
    contentBase: path.join(__dirname, "dist"),
    port: 8080,
    stats: "minimal",
    watchContentBase: true,
    historyApiFallback: true,
    open: false,
    hot: false
  },
  ...
```

**Comment by PatelDipen92** [comment] 2018-08-01 16:05
@hz9527 @dandohotaru I have tried with both solutions you have provided. But none of it worked.

**Comment by PatelDipen92** [comment] 2018-08-01 17:17
The problem is resolved. The issue was with the directory name. For the output, I was using "output" directory and for devServer I was providing contentBase from "dist" which was not containing index.html page. So it was throwing "Cannot Get /" error  

```
entry: './src/app.js',

    output: {
        path: path.join(__dirname, 'output'),
        filename: 'bundle.js'        
    },

    devServer: {
        contentBase: path.join(__dirname, 'output'),
        compress: true,
        port: 9000,
        historyApiFallback: true,
        publicPath: '/'
    }
```

**Closed** 2018-08-26 00:03 UTC
Labels: priority: 1 (critical), severity: 2 (regression), type: bug

**Comment by adamklepacz** [comment] 2018-10-02 20:01
Got the same problem after downloading some of the boilerplates. Thank You @PatelDipen92  for resolving a problem

**Comment by fortinmike** [comment] 2018-11-20 17:57
> As far as I'm concerned I've fixed the issue by
> 
> * making sure a base path is defined
> * making sure all 404s are redirected to index.html
> 
> ```
> module.exports = {
>   ...
>   output: {
>     ...
>     publicPath: '/'
>   },
>   devServer: {
>     historyApiFallback: true,
>   },
> }
> ```

Thanks @dandohotaru, this works for us too. We didn't have to revert to earlier versions of the packages; just adding the `publicPath` did the job (we already had `historyApiFallback` so I can't comment on the effect of that).

**Comment by zeroone001** [comment] 2019-05-05 00:16
```javascript
output: {
    ...
    publicPath: '/'
  }
```
This is the key

**Comment by AndreyGFranca** [comment] 2019-05-12 14:20
I made a copy of index.html in a new folder I called `deployment` to match what I specified in the output.path

**Comment by ecarrera** [comment] 2019-06-11 04:57
https://stackoverflow.com/questions/37954809/cannot-get-error-running-hello-world-in-webpack

**Comment by a-m-dev** [comment] 2019-11-09 06:13
> @MitchTalmadgeUofU you can use the following versions; these are the last ones that worked for me:
> 
> > "html-webpack-plugin": "^3.2.0",
> > "webpack": "^4.5.0",
> > "webpack-dev-server": "3.1.0"
> 
> I receive `Cannot GET /` on Windows for all versions which are higher than 3.1.0.
> 
> Is this related? [webpack/webpack-dev-middleware#270](https://github.com/webpack/webpack-dev-middleware/issues/270)

with `webpack-dev-server-@3.1.0` you have to run `npm audit fix`,

basically does not works now ...
 :(((

**Comment by darnoceloc** [comment] 2020-04-15 18:40
@PatelDipen92 Good eye! This tormented me for quite some time.

```
module.exports = {
    entry: './src/index.js',
    mode: 'development',
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /(node_modules)/,
                loader: 'babel-loader',
                options: { presets: ["@babel/env"] }
            },
            {
                test: /\.css$/,
                use: ["style-loader", "css-loader"]
            },
        ]
    },
    resolve: { extensions: ['*', '.js', '.jsx', '.es6'] },
    output: {
        path: path.resolve(__dirname, 'output'),
        publicPath: './dist/',
        filename: 'bundle.js'
    },
    devServer: {
        contentBase: path.join(__dirname, 'output'),
        port: 3000,
        writeToDisk: true,
        publicPath: 'http://localhost:3000/dist/',
        hotOnly: true,
        historyApiFallback: true,
    },
    plugins: [
        new HtmlWebpackPlugin({hash: true,
            title: 'My Awesome application',
            myPageHeader: 'Hello World',
            template: './src/index.html',
            filename: './dist/index.html'}),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.HotModuleReplacementPlugin({template: './public/index.html'})
    ]    
};
```
