### ISSUE TITLE
"proxy" is not defined

### ISSUE THREAD

**Issue by jedwards1211** [webpack/webpack-dev-server#479] opened 2016-05-07 20:10 UTC
some PR broke the `proxy.web` call in the deprecated `contentBase` section.  If you add `no-undef` to the ESLint rules, you'll see it:

```
Andys-MBP:webpack-dev-server andy$ npm run lint

> webpack-dev-server@2.0.0-beta lint /Users/andy/webpack-dev-server
> eslint lib test


/Users/andy/webpack-dev-server/lib/Server.js
  212:7  error  "proxy" is not defined        no-undef
```

**Comment by bebraw** [comment] 2016-05-10 06:30
Here, https://github.com/webpack/webpack-dev-server/commit/efd32a05944499b0c8165da6ff75519fb8fe21a6#diff-15fb51940da53816af13330d8ce69b4e . That removed `var proxy = new httpProxy.createProxyServer({secure: false});` and the branch you are pointing depends on that.

**Comment by SpaceK33z** [comment] 2016-08-25 08:46
@jedwards1211, this does not seem to be the case anymore in `1.15.0` or `2.1.0-beta0`. Do you still have this issue?

**Comment by jedwards1211** [comment] 2016-08-26 21:26
I'm honestly too busy to check right now, so you're welcome to just close this if you can't reproduce it.

**Comment by SpaceK33z** [comment] 2016-08-26 22:00
Okay, can't reproduce it, so closing it.

**Closed by SpaceK33z** 2016-08-26 22:00 UTC
Labels: bug, Needs Response From Author
