### ISSUE TITLE
Self signed certificate no longer valid as of Chrome 58

### ISSUE THREAD

**Issue by PaulTondeur** [webpack/webpack-dev-server#854] opened 2017-03-20 13:19 UTC
It turns out that the Subject Alt Name property is missing in the certificate, resulting in Chrome that marks the certificate as insecure. The error in chrome is misleading (net::ERR_CERT_COMMON_NAME_INVALID), though according to [this post](https://productforums.google.com/forum/#!topic/chrome/zVo3M8CgKzQ;context-place=topicsearchin/chrome/category$3ACanary%7Csort:relevance%7Cspell:false) it is about the Subject Alternative Name (SAN) that is missing.

**Comment by johnboxall** [comment] 2017-03-21 00:05
Based on https://github.com/webpack/webpack-dev-server/commit/e97741c84ca69913283ae5d48cc3f4e0cf8334e3 and https://security.stackexchange.com/a/91556 I believe this could be regenerated with something like:

```sh
openssl req \
    -newkey rsa:2048 \
    -x509 \
    -nodes \
    -keyout server.pem \
    -new \
    -out server.pem \
    -subj /CN=localhost \
    -reqexts SAN \
    -config <(cat /System/Library/OpenSSL/openssl.cnf \
        <(printf '[SAN]\nsubjectAltName=DNS:localhost')) \
    -sha256 \
    -days 3650
```

On OSX.

**Comment by ream88** [comment] 2017-03-31 14:35
Apparently this fix works also for Chrome 57. Thx @johnboxall!

**Comment by jesstelford** [comment] 2017-04-07 05:38
I also had to set `-extensions SAN` to get @johnboxall's command to work:

```bash
openssl req \
    -newkey rsa:2048 \
    -x509 \
    -nodes \
    -keyout server.pem \
    -new \
    -out server.pem \
    -subj /CN=localhost \
    -reqexts SAN \
    -extensions SAN \
    -config <(cat /System/Library/OpenSSL/openssl.cnf \
        <(printf '[SAN]\nsubjectAltName=DNS:localhost')) \
    -sha256 \
    -days 3650
```

**Comment by stephanvierkant** [comment] 2017-04-20 14:06
I've used that command, but still getting ERR_CERT_AUTHORITY_INVALID on Chrome 58. Adding it to Chrome doesn't work because of "Not a Certification Authority" error message.

Any idea how to fix this?

**Comment by ianfitzpatrick** [comment] 2017-04-21 20:26
@stephanvierkant 

I don't know what platform you are on, but assuming you are on OSX, you need to follow these instructions to manually trust self signed certificates.

https://github.com/webpack/webpack-dev-server/issues/854

FWIW I followed the instructions from @jesstelford above, then manually re-trusted the new certificate following instructions similar to above link, and I'm now all good.

My local dev server is running debian on a VM in my mac, so I did have to change `/System/Library/OpenSSL/openssl.cnf` to `/usr/lib/ssl/openssl.cnf`

**Comment by chibisuke** [comment] 2017-04-27 13:20
Time to migrate away from chrome.... with the latest update chrome is violating RFC2818.

**Comment by zijuexiansheng** [comment] 2017-05-02 02:31
The methods above works for me with Chrome. But I ran into some new issues.

1) I cannot install the self-signed certificate on Firefox. And if I install it on iphone, it's not trusted. 
2) I added `basicConstraints=CA:TRUE,pathlen:0` to the `openssl.cnf` file. Not it works perfectly for iphone. I can also import it to firefox. But the problem is that I cannot load my webpage with firefox

Does anyone have some ideas on how to resolve the firefox issue?

**Comment by CreativeWolf** [comment] 2017-05-02 09:27
Facing the same issue as @stephanvierkant mentioned here - https://github.com/webpack/webpack-dev-server/issues/854#issuecomment-295750188

Appreciate any work around for this please.

**Comment by lehne** [comment] 2017-05-02 13:43
https://serverfault.com/questions/845766/generating-a-self-signed-cert-with-openssl-that-works-in-chrome-58
I used this method and it worked well.

**Comment by lewis617** [comment] 2017-05-04 16:37
What about Windows?  @johnboxall

**Comment by RakeshMangroliya** [comment] 2017-05-15 06:18
Hello All

please use below mention solution work for Chrome + 58 and IISexpress 10.

please follow below steps

#1. run command prompt as administrator rights

#2 .type powershell -> enter

#3. now provide path of powershell script which i have attached

#4 .run it. 

[5464-iisexpress.zip](https://github.com/webpack/webpack-dev-server/files/1000216/5464-iisexpress.zip)

**Comment by szkrd** [comment] 2017-05-15 08:37
@lewis617 mingw git comes with an openssl binary (/mingw64/bin/openssl), use that. Copy `/usr/ssl/openssl.cnf` to somewhere else, add the two extra lines (`[SAN]...`) and use the `-config` param with the customized cnf, the rest of the params are the same as above mentioned. Hope it works!

**Comment by DBosley** [comment] 2017-05-16 21:45
@RakeshMangroliya this script did not work for me. It did fix IIS Express cert issues, but it did not fix the cert bundled with webpack-dev-server

**Comment by RakeshMangroliya** [comment] 2017-05-17 05:36
@DBosley 

Hi

Please use this script and let me know. or provide me port no for webpack-dev-server you are using.

**Comment by DBosley** [comment] 2017-05-17 16:55
@ianfitzpatrick Thanks for your help! Combining some stuff with others from @jesstelford I was able to edit the cert that comes with webpack-dev-server to have an SAN without invalidating the cert my whole team has already added to their trusted store.

All of this was a hassle as a windows user. I couldn't get the `<(cat /usr/lib/ssl/openssl.cnf <(printf '[SAN]\nsubjectAltName=DNS:server.local'))` part of the command to work, so I just ended up adding this section to my cnf file and removing it after I was done:
```
[SAN]
subjectAltName=DNS:server.local
```

**Comment by wilga** [comment] 2017-05-18 18:23
Here is a Windows script to generate the self-signed certificate with openssl:
[makeCert.bat](https://github.com/wilga/win-openssl-self-signed-san/blob/master/makeCert.bat)

**Comment by zrubinrattet** [comment] 2017-06-02 21:24
Took me a moment to figure out (with help from this post) that because I'm using a virtual host set up via MAMP Pro I had to change that command a bit to output key and crt files (to plug into MAMP Pro's SSL tab) and I had to make sure I inputted the correct name of the virtual server (wherever you see "yoursite.dev").

```
openssl req \
    -newkey rsa:2048 \
    -x509 \
    -nodes \
    -keyout yoursite.key \
    -new \
    -out yoursite.crt \
    -subj /CN=yoursite.dev \
    -reqexts SAN \
    -extensions SAN \
    -config <(cat /System/Library/OpenSSL/openssl.cnf \
        <(printf '[SAN]\nsubjectAltName=DNS:yoursite.dev')) \
    -sha256 \
    -days 3650
```

**Comment by finkunlimited** [comment] 2017-06-29 20:22
Hi Folks, for us beginner tech folk who has only ever used MAMP Pro and now pulling hair out as we cannot access our production site, is there a step by step guide explaining where and how to make these changes?

Thanks.

**Comment by shellscape** [comment] 2017-08-09 00:45
Original issue as reported should be resolved in 400b2896c79f55c6928d59aebfb773b6e037b8ef. Closing due to age and commit.

**Closed by shellscape** 2017-08-09 00:45 UTC

**Comment by afhole** [comment] 2017-08-09 16:35
Is the resolution included in v2.7.1?

**Comment by shellscape** [comment] 2017-08-09 16:39
That commit is in the latest version, yes.

**Comment by k0a1a** [comment] 2017-08-10 00:59
Here is a solution that works for me:

https://ram.k0a1a.net/self-signed_https_cert_after_chrome_58

Tested on Debian/Apache2.4 + Debian/Chromium 59

**Comment by afhole** [comment] 2017-08-10 11:46
So the cert generated by dev server automatically still doesn't work with latest Chrome?

**Comment by shellscape** [comment] 2017-08-10 11:48
@afhole not sure where you got that. works fine for me.

**Comment by afhole** [comment] 2017-08-10 11:53
@shellscape Oh cool, glad it's sorted. In 2.7.1 I am still getting `ERR_CERT_COMMON_NAME_INVALID` I wonder if I have the cert cached somewhere? Is there anything I need to do to clear the cache and generate a new cert?

**Comment by shellscape** [comment] 2017-08-10 11:56
@afhole I'm not sure about that one I'm afraid.

**Comment by afhole** [comment] 2017-08-10 12:00
@shellscape Sorry, just to clarify - you no longer have errors with `Subject Alternative Name missing` and `ERR_CERT_COMMON_NAME_INVALID`? I just deleted `ssl/server.pem` and it regenerated, to no avail.

**Comment by shellscape** [comment] 2017-08-10 12:06
Correct

**Comment by afhole** [comment] 2017-08-10 13:51
With `localhost` right? Has anyone else had success/failure with 2.7.1?

**Comment by accentureChris** [comment] 2017-08-14 20:23
We're unable to upgrade to 2.7.1 currently. Any cross-platform guidance? I've tried several guides/openssl cert/key generation.

**Comment by paillave** [comment] 2017-09-24 20:49
I am facing the issue. Whatever I can try doesn't work, I still have this ERR_CERT_AUTHORITY_INVALID after any solution I apply from the net.
Something puzzles me: why IISExpress doesn't face this issue? If I get it well, if IIS Express work, this means that, as a matter of a fact, it is possible to provide a certificate that can be accepted by chrome. Why the certificate provided by webpack-dev-server is refused even if it is trusted? BTW, I don't believe we should even create a certificate ourselves for a development server.

**Comment by zijuexiansheng** [comment] 2017-09-24 20:51
@paillave Chrome has some cache issue with certificates. Try reboot your computer or remove the cert cache and then reboot

**Comment by afhole** [comment] 2017-09-25 09:39
@paillave FWIW I still can't get it to work in Chrome 61/macOS 10.12.6, not sure what else to try

**Comment by afhole** [comment] 2017-09-25 11:03
Finally I got this to work with webpack-dev-server@2.8.2
I loaded it in Safari and set it to Always Trust for SSL and now it works in Chrome.
It shows as a root CA, is that correct?

**Comment by k0a1a** [comment] 2017-09-27 19:35
You can as well add the cert using Chrome/Chromium 
https://ram.k0a1a.net/self-signed_https_cert_after_chrome_58#add_cert
(although I'm not sure if it works on OSX the same way it does on Linux)

**Comment by stevenfitzpatrick** [comment] 2017-09-30 13:22
Still getting issue with latest chrome and latest webpack regarding ERR_CERT_COMMON_NAME_INVALID.

So I am trying generating a self signed cert.

What wasn't clear from this thread is where are you placing the self signed cert ?

Are you replacing the cert in node_modules/webpack-dev-server/ssl/server.pem or like this
```
https: {
      ca: fs.readFileSync('server.pem')
    },
```

**Comment by wenJanus** [comment] 2017-11-20 01:51
I have the same problem when I use headless mode. Any body have some solution?
09:24:07.722 DEBUG selenium-nodejs.HomePage: navigate
[1120/092408.090:VERBOSE1:network_delegate.cc(31)] NetworkDelegate::NotifyBeforeURLRequest: https://localhost/home
[1120/092408.403:VERBOSE1:navigator_impl.cc(242)] Failed Provisional Load: https://localhost/home, error_code: -501, error_description: , showing_repost_interstitial: 0, frame_id: 1

**Comment by mehrdaad** [comment] 2018-02-18 07:07
@stephanvierkant managed to fix it?

**Comment by baona95** [comment] 2018-03-14 11:59
@k0a1a Thank you so much! I've spent much time on this, you just saved my day.

**Comment by czebiniak** [comment] 2018-03-16 19:40
This is such a bullshit issue. This doesn't increase security in my CA at all. Forcing me to add a subject alternative name? WTF are you thinking Google? I'm done with Chrome. This on top of Chrome blocking all httpd in 2 months... Literally insane.

**Comment by jkulak** [comment] 2018-07-13 20:57
For me (macOS High Sierra), going to Certificates in Keychain Access and setting Always Trust for SSL solved the issue.

<img width="600" alt="screen shot 2018-07-13 at 22 53 09" src="https://user-images.githubusercontent.com/426746/42713489-f1c8701a-86ef-11e8-97ca-7239ce1a0794.png">

**Comment by vog** [comment] 2018-11-24 10:18
Note that generating a self-signed certificate with SAN is a lot easier than any of the long commands specified here. In particular, you do not need to know the location of the OpenSSL config file in your system. It is described in the following StackOverflow answer:

* https://stackoverflow.com/a/41366949/19163

**Comment by adi518** [comment] 2020-03-13 01:53
Hmm, I guess this issue is back? why was it closed? can it even be fixed or are we at the mercy of Chrome and fixing it ourselves by generating certificates? well anyway, Windows users should do this:

- Grab OpenSSL for [Windows](https://slproweb.com/products/Win32OpenSSL.html).
- Add binary to `PATH` environment variable, as their installer doesn't do that.
- Restart your CLI, type `openssl` and it should work.
- Run @wilga batch file.

**Comment by evilebottnawi** [comment] 2020-03-13 08:50
@adi518 Update your version of webpack-dev-server to latest stable
