### ISSUE TITLE
Unclear config issue when using API? "Error: Invalid path"

### ISSUE THREAD

**Issue by scvnc** [webpack/webpack-dev-server#88] opened 2014-12-20 17:03 UTC
Repo replicating the issue: https://github.com/scvnc/webpack-dev-server-grief

My webpack config seems to be configured correctly because running the CLI `webpack-dev-server` is successful.  However when using the [gulp example](http://webpack.github.io/docs/usage-with-gulp.html) from the webpack docs: I can't seem to successfully invoke the webpack dev server.  What is going on?

	$ npm install
	$ gulp
	[10:35:59] Using gulpfile ~/webpack-dev-server-grief/gulpfile.js
	[10:35:59] Starting 'default'...
	[10:35:59] Finished 'default' after 49 ms
	[10:35:59] [webpack-dev-server] http://localhost:8080/index.html

	/home/vincent/webpack-dev-server-grief/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:161
				if(isError) throw e;
				                  ^
	Error: Invalid path
	    at pathToArray (/home/vincent/webpack-dev-server-grief/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:23:38)
	    at MemoryFileSystem.mkdirpSync (/home/vincent/webpack-dev-server-grief/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:107:13)
	    at MemoryFileSystem.(anonymous function) [as mkdirp] (/home/vincent/webpack-dev-server-grief/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:187:34)
	    at Tapable.<anonymous> (/home/vincent/webpack-dev-server-grief/node_modules/webpack/lib/Compiler.js:225:25)
	    at Tapable.applyPluginsAsync (/home/vincent/webpack-dev-server-grief/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
	    at Tapable.Compiler.emitAssets (/home/vincent/webpack-dev-server-grief/node_modules/webpack/lib/Compiler.js:222:7)
	    at Watching.<anonymous> (/home/vincent/webpack-dev-server-grief/node_modules/webpack/lib/Compiler.js:53:18)
	    at /home/vincent/webpack-dev-server-grief/node_modules/webpack/lib/Compiler.js:397:12
	    at Tapable.next (/home/vincent/webpack-dev-server-grief/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:11)
	    at CachePlugin.<anonymous> (/home/vincent/webpack-dev-server-grief/node_modules/webpack/lib/CachePlugin.js:40:4)

**Comment by ambodi** [comment] 2015-10-28 09:08
@sokra @scvnc I came across the issue and the leading ./ was the issue but why the webpack core package doesn't reflect on it and the dev server is throwing the error only? Isn't it inconsistent?

**Comment by CoolGoose** [comment] 2015-11-08 18:21
Same issue here, using the proposed fix from @sokra 
```
 path: require("path").resolve("./build/js"),
```
works like a charm.
Any way for a nicer error output ?

**Comment by 0x80** [comment] 2016-03-07 14:56
This just cost me a few hours of frustration trying to move an existing project from dev server to middleware. A validation of `output.path` and a little more descriptive error would be very welcome.

**Comment by cchamberlain** [comment] 2016-04-27 00:55
I just started getting this with webpack-hot-middleware today and the cause was a recent refactor of my webpack config builder to es6, now using export default.

Fix for me was to change `require('../webpack.config')` to `require('../webpack.config').default` in my server code that wires up the hot middleware. Boils down to the same issue with not having a path set, would be good to have an assert in webpack with a more useful message.

**Comment by zedd45** [comment] 2016-04-27 21:34
I encountered this issue trying to find the middle-ground for `:global` / and `:local` for CSS modules styles, based on @sokra's comments, here: 
https://github.com/css-modules/css-modules/issues/59#issuecomment-144127638

I did not modify `path` nor `publicPath` for my `output` for this task (nor for some time), but I do believe another misconfiguration on my part caused this same error (and thus led me to this post). 

In my case, I was importing a stylesheet that had previously been local to a container component, but I switched the stylesheet to be global by default, and my build failed with the same error message.

I believe my `include` (preferred) / `exclude` logic may have been to blame for this (`webpack` likely could no longer parse this file).  I was experimenting with this feature, and restructuring my CSS locally.

**Comment by SpaceK33z** [comment] 2016-09-09 10:07
#337 was fixed in the latest beta release. This means that the dev-server CLI does no longer overwrite `output.path` to `/`, making the error the author initially had less weird.

I'll look into having some validation for `output.path`, if I can find some cases where it is always incorrect.

**Comment by SpaceK33z** [comment] 2016-09-20 11:36
`webpack-dev-middleware` should now give a proper error when using a relative path;
https://github.com/webpack/webpack-dev-middleware/commit/ee9b796385919f1d7a2af1e48903d61968740e1b

**Closed by SpaceK33z** 2016-09-20 11:36 UTC
Labels: bug, P1: Urgent
