### ISSUE TITLE
High CPU Usage?

### ISSUE THREAD

**Issue by vollpiin** [webpack/webpack-dev-server#2643] opened 2020-06-09 12:31 UTC
- Operating System: Ubuntu 20.04
- Node Version: 12.18.0
- NPM Version: 6.14.4
- webpack Version: 5.0.0
- webpack-dev-server Version: 3.11.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const HtmlWebpackPlugin = require("html-webpack-plugin");
const HtmlWebpackInlineSourcePlugin = require("html-webpack-inline-source-plugin");

const path = require("path");

const mode = process.env.NODE_ENV || "development";
const prod = mode === "production";

module.exports = {
  entry: {
    bundle: ["./src/main.ts"],
  },
  resolve: {
    alias: {
      svelte: path.resolve("node_modules", "svelte"),
    },
    extensions: [".mjs", ".js", ".svelte", ".ts"],
    mainFields: ["svelte", "browser", "module", "main"],
  },
  output: {
    path: __dirname + "/public",
    filename: "[name].js",
    chunkFilename: "[name].[id].js",
  },
  target: "electron-renderer",
  module: {
    rules: [
      {
        test: /\.svelte$/,
        exclude: /node_modules/,
        use: {
          loader: "svelte-loader",
          options: {
            emitCss: true,
            hotReload: true,
            preprocess: require("svelte-preprocess")({
              typescript: {
                tsconfigFile: "./tsconfig.json",
                scss: true,
              }
            }),
          },
        },
      },
      {
        test: /\.ts$/,
        use: [
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: true,
              experimentalWatchApi: true,
            },
          },
        ],
      },
      {
        test: /\.(scss|sass|css)$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              hmr: mode === "development",
            },
          },
          "css-loader",
          "sass-loader",
        ]
      },
      {
        test: /\.(png|jpe?g|gif|mp4|svg|ttf|woff|woff2)$/,
        use: [
          {
            loader: "file-loader",
          },
        ],
        include: path.resolve(__dirname, 'src/assets'),
      },
    ],
  },
  mode,
  plugins: [
    new MiniCssExtractPlugin({
      filename: "[name].css",
    }),
    new HtmlWebpackPlugin({
      inlineSource: ".(js|css)$",
      template: "./src/index.html",
      title: "Web Builder",
    }),
    new HtmlWebpackInlineSourcePlugin(),
  ],
  devtool: prod ? false : "source-map",
  devServer: {
    port: 9000,
    contentBase: path.join(__dirname, "public"),
  },
};
```

### Expected Behavior
I want the HMR to only happen when I switch the code editor window, similar to `nodemon`

### Actual Behavior
I noticed that `webpack-dev-server` consume too much cpu since it try to re-compile on every change I make.

**Comment by evilebottnawi** [comment] 2020-06-09 12:46
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Do not remove `For Bugs; How can we reproduce the behavior?` section and others

**Closed by evilebottnawi** 2020-06-09 12:46 UTC
