### ISSUE TITLE
Proxy requests do not work when not connected to internet

### ISSUE THREAD

**Issue by jsgoupil** [webpack/webpack-dev-server#744] opened 2017-01-16 23:44 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
[HPM] Error occurred while trying to proxy request /api/errors from localhost:3000 to http://localhost:55323 (ENOENT) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**If the current behavior is a bug, please provide the steps to reproduce.**
Turn of your WIFI or unplug your network cable

**What is the expected behavior?**
Proxy requests, especially if they are on localhost...

**Please mention your webpack and Operating System version.**
2.1.0-beta.12
Windows 10

**Comment by xxn520** [comment] 2017-01-21 01:49
same issue

**Comment by SpaceK33z** [comment] 2017-01-21 08:54
I tried reproducing your issue by proxying to a server on localhost, but it worked for me when offline. Could you provide more information? Note that we use [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware/issues) for proxying, so if there is an issue, it's probably over there.

**Comment by afucher** [comment] 2017-02-06 20:40
same issue.. I'm trying to search more useful information to put here... But I don't find anything that could be help

**Comment by nassimus26** [comment] 2017-03-24 16:59
same issue ...!!

**Comment by chimurai** [comment] 2017-03-24 17:30
Similar discussion @ https://github.com/facebookincubator/create-react-app/issues/1116

On _Windows_ you have to use `127.0.01` instead of `localhost` to be able to work offline.

**Comment by liyu2012** [comment] 2017-05-01 07:52
the same issue with me!,I find in the http-proxy-middleware,there is a error.
in function getProxyEventHandler()
_.get will return undefined instead of a Function type.
But it need a function to listen proxyEvents

**Comment by lucasvinals** [comment] 2017-06-20 21:16
Guys, I think "localhost" is resolved with an active connection to the router. Try to replace localhost to 0.0.0.0 in your proxy object like this: 
`proxy: {
      '/api': {
        target: {
          host: '0.0.0.0',
          port: 3000,
        },
        secure: false,
      },
    },`

**Comment by shellscape** [comment] 2017-08-09 00:51
Pruning due to age, inactivity, and apparent solutions/workarounds.

**Closed by shellscape** 2017-08-09 00:51 UTC
Labels: question, X0: need more information
