### ISSUE TITLE
Project built with v2.8.2 outputs webpack code with ES6 features which causes error with browsers that don't support it

### ISSUE THREAD

**Issue by pavle-goloskokovic** [webpack/webpack-dev-server#1104] opened 2017-09-19 10:45 UTC
* Operating System: **Windows 10 Home**
* Node Version: **v6.10.0**
* NPM Version: **3.10.10**
* webpack Version: **3.6.0**
* webpack-dev-server Version: **2.8.2**

- [ ] This is a **feature** request
- [x] This is a **bug**

I'm building an app that targets device with a browser that does not support ES6 features. 
I've been using webpack-dev-server for development and it worked fine up to and including v2.7.1.
When I updated version to 2.8.2 it started outputting webpack code with ES6 features which causes browser to throw an error.
Project code and configuration for webpack, typescript and command for running webpack-dev-server are the same, the only difference is webpack-dev-server version.
Building app only with webpack works fine as well.
You can find below code that is server by webpack-dev-server after starting it:

### Code

Compiled webpack code with webpack-dev-server v2.7.1:
```js
...
/* WEBPACK VAR INJECTION */(function(__resourceQuery) {/* global __resourceQuery WorkerGlobalScope */
var url = __webpack_require__(61);
var stripAnsi = __webpack_require__(67);
var log = __webpack_require__(69)
var socket = __webpack_require__(70);
var overlay = __webpack_require__(102);
...
```
Compiled webpack code with webpack-dev-server v2.8.2:
```js
...
/* WEBPACK VAR INJECTION */(function(__resourceQuery) {
 
/* global __resourceQuery WorkerGlobalScope self */
/* eslint prefer-destructuring: off */

const url = __webpack_require__(61);
const stripAnsi = __webpack_require__(67);
const log = __webpack_require__(69).getLogger('webpack-dev-server');
const socket = __webpack_require__(70);
const overlay = __webpack_require__(102);
...
```

### Expected Behavior

Code runs fine when built with webpack-dev-server v2.8.2.

### Actual Behavior

Browser throws an error: 

> Syntax error at line 20608 while loading: syntax error
> const url = __webpac
> ^

### How can we reproduce the behavior?

1. Start any project built with webpack using webpack-dev-server v2.8.2
2. Run it in any browser that does not support ES6 features such as `const` or `let` (any such browser can be found in this table: https://kangax.github.io/compat-table/es6/)

**Comment by shellscape** [comment] 2017-09-19 11:58
@pavle-goloskokovic  thanks for filing an issue. this is kind of a duplicate of #1091, but you've been more specific, so we'll address it. Unfortunately we're not supporting browsers that don't support `const` and `let` - all major browsers two full major versions back support those keywords now. Old IE support [ended in January 2016](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support). If you're using a fringe browser that doesn't support those keywords, please open an issue with those browsers' projects. We wrestled with whether or not this was a breaking change that constituted a new major version, but since Old IE support ended so very long ago, and all other major browsers have supported those keywords for over two years, we felt it was reasonable in a minor version. Unfortunately this isn't something we're gong to fix for 2.8.x. If you still need to support those really old browsers, you'll have to stick with 2.7.x.

**Closed by shellscape** 2017-09-19 11:58 UTC

**Comment by e01010100** [comment] 2017-09-22 18:17
Can a "Breaking Changes" section be added to the [v2.8.0 release notes](https://github.com/webpack/webpack-dev-server/releases/tag/v2.8.0), noting that browsers that do not natively support ES6 will no longer be supported?

This would help alleviate confusion for users upgrading, especially those that test/unit-test on older browsers. 

Thank you!

**Comment by patrick-ivers** [comment] 2017-09-28 05:45
I agree with @e01010100 . I just ran into this issue and it took me a while to figure out what was going on (Thought it had something to do with my webpack config or babel-loader).

**Comment by HopeLyn** [comment] 2017-10-03 09:11
Agree.I was just involved in some project , which had some webpack config.I was so puzzled until I found this page.

**Comment by EloB** [comment] 2018-01-05 16:25
This issue took me more than 2-3 days to figure out. I'm working with "smart" devices that often have really bad debugging possibilities and webpack is the best thing that happend to these devices because of hot loading etc. Is their a reason why you don't define `jsnext:main` and `main` in package.json? Is really easy and will remove a lot of headache and the only blocker right now for webpack to run on older browsers/devices.

**Comment by ViggoV** [comment] 2018-01-12 10:35
Wait, what?! So WDS doesn't compile according to the webpack config?

**Comment by joshhead** [comment] 2018-01-19 22:14
I ended up adding `--inline=false``./node_modules/.bin/webpack-dev-server --inline=false`

**Comment by EloB** [comment] 2018-01-22 17:05
@joshhead I think they are added ES5 to the bundle right now... Saw some PRs about it 😃 

https://github.com/webpack/webpack-dev-server/pull/1273
https://github.com/webpack/webpack-dev-server/pull/1270
