### ISSUE TITLE
Multi-compiler mode, hot-update.json 404

### ISSUE THREAD

**Issue by maqunjing** [webpack/webpack-dev-server#2355] opened 2019-12-17 12:33 UTC
- Operating System:macOS Mojave version 10.14.3
- Node Version:10.16.3
- NPM Version:6.9.0
- webpack Version:4.39.2
- webpack-dev-server Version:3.9.0
- Browser:Chrome  79

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const path = require('path');
const IP = require('ip').address()
module.exports = [
    {
        name: 'hello',
        devServer:{
            hotOnly: true,
            host: '0.0.0.0',
            sockPath: '/custom-sockjs-node',
            
            sockHost: `${IP}`, 
            sockPort: '8080', 
            headers: {
                'Access-Control-Allow-Origin': '*', 
            
            
            },
        },
        mode: 'development',
        
        
        context: path.resolve(__dirname, 'app'), 
        
        optimization: {
            minimize: false 
        },
        output: {
            path: path.join(__dirname, 'dist'),
            filename: 'index.js',
            publicPath: `http://${IP}:8080/`
        },
        plugins: [
            
            
            
        ],
        entry: './src/index.js',
    },
    {
        name: 'world',
        mode: 'development',
        context: path.resolve(__dirname, 'app'), 
        
        optimization: {
            minimize: false 
        },
        output: {
            path: path.join(__dirname, 'dist'),
            filename: 'index2.js',
            publicPath: `http://${IP}:8080/`
        },
        plugins: [
        ],
        entry: './src/index2.js',
    }
];
```

```js
// hello.js
export default {
    world: 'lala'
}

// index.js
import Hello from './hello.js';
console.log(Hello.world);
console.log(123456)

if (module.hot) module.hot.accept()

// index2.js
import Hello from './hello.js';
console.log(Hello.world);
console.log(14113333312212333323333999444333)

if (module.hot) module.hot.accept()
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script src="http://10.104.32.88:8080/index.js"></script>
    <script src="http://10.104.32.88:8080/index2.js"></script>
</body>
</html>
```

### Expected Behavior
bundles don't process each other's updates

### Actual Behavior
![image](https://user-images.githubusercontent.com/4019477/70995603-e8a97d00-210b-11ea-911e-667208ae825f.png)

**Comment by evilebottnawi** [comment] 2019-12-17 12:36
Please create reproducible test repo

**Comment by maqunjing** [comment] 2019-12-17 13:29
> Please create reproducible test repo

thanks!
https://github.com/maqunjing/issue-webpack-dev-server-multi-compiler-mode

**Comment by astr0junk** [comment] 2020-01-10 11:17
+ same problem

**Comment by zachintosh** [comment] 2020-01-27 21:53
Same issue here. I am using the `name` property on the configs, but when either of my two compilers recompile, it triggers an attempt to update via HMR from both.

Say Compiler 1 recompiles on a file save:
- Recompiles
- Both attempt to update through HMR
- One succeeds, but the other fails (hot-update 404 error)

**Comment by 7kms** [comment] 2020-06-24 09:54
Same problem with me
I hava 2 webpack-dev-server instance in a page.  
```js
if (module.hot) module.hot.accept()
```
so the second access of `module` may be is same as the first one.

**Comment by ArgonAlex** [comment] 2020-08-19 07:46
I just ran into this problem. After lots of debugging, I discovered that the order in which the compilers emit the "done" event seems to determine whether you run into this issue or not.

In my case, if the client compiler finished before the server compiler, then I was seeing this issue. But if the client compiler finishes last, everything works as expected.

**Comment by luogan210** [comment] 2020-09-03 01:59
this issue still open , how to solve it

**Comment by aboks** [comment] 2020-09-09 07:08
I can consistently reproduce this issue as well, with the following case: https://gist.github.com/aboks/b5ca75f028631ca06d1235f866b348a7 (in case it helps). It is only a minimal variation of the `multi-compiler` example that comes with Webpack: I mainly added something that can be HMR'ed and changed the output so that both compilers output to a different path (without an explicitly configured filename). If I then run `webpack-dev-server --watch --hot`, open both 'magic' html files and make a change to the message in `shared-stuff.js` exactly one of the open pages fails to download the `<hash>.hot-update.json` file (due to a 404) and falls back to a full page reload.

It seems that the failing page tries to download the `<hash>.hot-update.json` file with the hash of the other compiler. This depends on the order in which the two compilers finish. In a situation where the two compilers would write to the same `output.path` (as in the original `multi-compiler` example) the hot update file with the 'incorrect' hash can be found as if nothing is wrong, but with different output paths the hot update file with the hash of compiler A cannot be found in the out path of compiler B.

Other observation: if I add different output filenames to both compilers (these are commented out in the gist), everything seems to work fine. Could it be that hashes are emitted linked to the output filename, but without taking the output path into account?

**Comment by daychongyang** [comment] 2020-09-23 04:55
Set name parameters to make sure bundles don't process each other's updates. It can run normally. 😉 [https://github.com/webpack-contrib/webpack-hot-middleware#multi-compiler-mode](https://github.com/webpack-contrib/webpack-hot-middleware#multi-compiler-mode)

**Comment by aboks** [comment] 2020-09-23 07:08
@daychongyang my example in https://github.com/webpack/webpack-dev-server/issues/2355#issuecomment-689354816 has `name`-parameters set, but can still consistently reproduce this issue. So unfortunately that does not seem to be sufficient.

**Comment by daychongyang** [comment] 2020-09-23 07:14
> @daychongyang my example in [#2355 (comment)](https://github.com/webpack/webpack-dev-server/issues/2355#issuecomment-689354816) has `name`-parameters set, but can still consistently reproduce this issue. So unfortunately that does not seem to be sufficient.

The difference is that I used `webpack-dev-middleware` and `webpack-hot-middleware` directly, and I think this should not cause an error. 🤔

**Comment by hiisea** [comment] 2021-07-20 07:41
this issue still open , how to solve it

**Comment by alexander-akait** [comment] 2021-07-21 22:07
Close in favor https://github.com/webpack/webpack-dev-server/issues/2792 https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-808328432, here is the same problem, you use different chunks with different runtime on the same page, anyway it is possible in webpack v5, set `runtimeChunk: single`, check you have unique https://webpack.js.org/configuration/output/#outputuniquename for each runtime.

Also we have small problems with multi compiler mode https://github.com/webpack/webpack-cli/issues/2408 (it will be fixed in near future).

Also I recommend to use this https://webpack.js.org/configuration/other-options/#dependencies if one build depend on other

**Closed by alexander-akait** 2021-07-21 22:07 UTC
