### ISSUE TITLE
Issue with "!" in the Directory Path

### ISSUE THREAD

**Issue by Silvenga** [webpack/webpack-dev-server#315] opened 2015-11-16 01:38 UTC
Under Windows, considering the following parent directory:

```
C:\!Development\App\
```

Webpack-dev-server gives an error similar to the following:

```
Module not found: Error: Cannot resolve directory 'C:\' in C:\!Development\App
```

The `!` character in the path appears to confuse webpack-dev-server, removing this character (renaming the folder) mitigates this issue and allows webpack-dev-server to build like normal. 

Webpack alone is able to bundle my project.

**Comment by SpaceK33z** [comment] 2015-11-28 10:56
Do you have a more detailed stacktrace? That would show where the error is coming from...

**Comment by Silvenga** [comment] 2015-11-28 20:09
> Do you have a more detailed stacktrace?

Not really (is there a way to give more verbose output?). All I have is 50KB of this:

<pre>
ERROR in multi main
Module not found: Error: Cannot resolve directory 'C:\(Snip)' in C:\(Snip)\!Dashboard\app
 @ multi main
</pre>

<pre>
ERROR in ./app/assets/scss/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../.. in C:\(Snip)\!Dashboard\app\assets\scss
 @ ./app/assets/scss/main.scss 7:13-90
</pre>

<pre>
ERROR in ./~/react/lib/flattenChildren.js
Module not found: Error: Cannot resolve directory 'C:\(Snip)' in C:\(Snip)\!Dashboard\node_modules\react\lib
 @ ./~/react/lib/flattenChildren.js 1:0-114
</pre>

Sorry for the snipping - my paths may contain sensitive information. 

The `!` symbol can appear anywhere in the absolute path to the root folder and it causes these issues.

**Comment by spoeken** [comment] 2016-01-19 12:33
Probably related to issue #188 
Can someone point me in the right direction so I can try fix this?

**Comment by SpaceK33z** [comment] 2016-08-27 10:15
Dupe of #188.

**Closed by SpaceK33z** 2016-08-27 10:15 UTC
