### ISSUE TITLE
HMR doesn't work if webpack-dev-server is only installed globally

### ISSUE THREAD

**Issue by andyhall** [webpack/webpack-dev-server#1017] opened 2017-08-04 04:58 UTC
This occurs with the most minimal hot-reloading project I could manage - webpack config copied verbatim from the [HMR guide](https://webpack.js.org/guides/hot-module-replacement/), and current versions of both `webpack` and `webpack-dev-server`, and nothing else in the repository.

If the project is run with both libraries present locally - i.e. as a result of doing:

```shell
yarn add --dev webpack
yarn add --dev webpack-dev-server
webpack-dev-server
```

..then HMR works normally. If the dev server is only installed globally - e.g. by doing:

```shell
yarn remove webpack-dev-server
yarn global add webpack-dev-server
webpack-dev-server
```

..then everything *except* the reloading part of HMR works. That is, bundling works and the page console shows a log message that HMR is enabled. However when a hot-reloading update is triggered, the page console reads: 

```
[WDS] App updated. Recompiling...
bundle.js:4589 [WDS] App hot update...
```

but the next line ("Checking for updates on the server...") never occurs. and the `module.hot.accept` handler never gets called.

Am I missing something? Are global installs of the dev server not supported?

**Comment by shellscape** [comment] 2017-08-09 16:03
For thoroughness, please try your test cases using `npm` rather than `yarn`. We've had several issues resolved by going that route, believe it or not :)

**Comment by andyhall** [comment] 2017-08-10 02:07
@shellscape I tried both npm and yarn, same result. Why, is it not reproducing?

(The rest of my environment is: current OS X, current Chrome. I'm not able to easily test Windows.)

**Comment by shellscape** [comment] 2017-08-10 02:48
A global install isn't something we've ever really tested for. There's a few other issues that touch on it and it's generally not recommended. I haven't had the chance to attempt to triage a global install. Out of curiosity, why do you need to install the module globally?

**Comment by andyhall** [comment] 2017-08-10 03:19
It's not that I have something that won't work without a global install. It's just that I use webpack+dev server as a default setup in many dozens of projects, so I have them installed globally to avoid having the same ~50MB of stuff sitting in many dozens of places. 

I mean, if global installs are unsupported then that's that. I just never heard of something like that before, so I assumed it wasn't the case here.

**Comment by shellscape** [comment] 2017-08-30 03:52
Following up on this one...

I've run several of the tests in the `examples` with webpack-dev-server installed globally in Node 4.8.4, 6.10.2, 7.8.0 (because why not), and 8.2.1. I'm pleased to report that 2.7.1 behaves normally for all node versions for all examples that I ran (compression, hmr, host-port, https, overlay).

I can't reproduce the same issue on my end unfortunately. Officially, WDS is intended to be run locally, but all tests over here show that it works as expected globally. This may be a most-cases-but-not-all-cases type of thing. If you can find a specific reason why it's not working with your config/setup, please do ping me and we'll reopen and start working on a fix.

**Closed by shellscape** 2017-08-30 03:52 UTC
Labels: question

**Comment by andyhall** [comment] 2017-08-30 06:01
Hey, thanks for checking! 

It sounds like this may just be my dev machine then. I will update if I see it elsewhere or figure out the specific cause; otherwise please disregard and sorry for the runaround!

(For my own reference: current reproducing environment is node 8.4.0, npm 5.3.0, webpack 3.5.5, dev server 2.7.1.)

**Comment by shellscape** [comment] 2017-08-30 13:46
Never a worry, always happy to look into a potential bug, especially a potential one at that level.
