### ISSUE TITLE
Can't click anything on webpage on 1.15.0. (Can in 1.14.1.)

### ISSUE THREAD

**Issue by tylerhou** [webpack/webpack-dev-server#576] opened 2016-08-28 17:22 UTC
I can't click anything on my /webpack-dev-server/ webpage in 1.15.0. I'm running macOS El Capitan 10.11.6 on a Retina MacBook Pro 12,1. When I double click, I highlight the "App ready" span at the top of the screen. Clicking works when navigating to the file directly via localhost:8080 or the file system.

I've made a minimal example repository to illustrate the issue: tylerhou/webpack-bug. Using the repository, I've reproduced the issue on another Retina MacBook Pro running macOS 10.11.6. I'm not sure if it can be reproduced on other systems.

When 1.14.1 is installed, clicking works.

**Comment by SpaceK33z** [comment] 2016-08-28 18:09
Dupe of #559. TL;DR - it's getting fixed.

**Closed by SpaceK33z** 2016-08-28 18:09 UTC
