### ISSUE TITLE
HTTPS - examples/https directory - Chrome Error  BugReport

### ISSUE THREAD

**Issue by jdiapps** [webpack/webpack-dev-server#668] opened 2016-10-24 19:38 UTC
I'm submitting a bug report. I am attempting to run the example under the examples/https directory.

I am using  "webpack": "2.1.0-beta.22", 
"webpack-dev-server": "2.1.0-beta.9",

I am running on windows 8 using Chrome.

I get this error from chrome and it won't allow me to add an exception or proceed:

**localhost normally uses encryption to protect your information. When Google Chrome tried to connect _to localhost this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be localhost, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.
You cannot visit localhost right now because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later._**

How can I use the built in certificate to launch webpack-dev-server

**Comment by SpaceK33z** [comment] 2016-10-24 19:50
This is probably related to #648.

**Comment by SpaceK33z** [comment] 2016-10-25 09:13
Closing this as a dupe of #648.

**Closed by SpaceK33z** 2016-10-25 09:13 UTC

**Comment by carlaarchuleta707-lgtm** [comment] 2026-09-06 17:55
_8https://github.com/webpack/webpack-dev-server/issues/668_
