### ISSUE TITLE
Webpack-dev-server HMR only displays SCSS changes after first reload but none thereafter

### ISSUE THREAD

**Issue by mattwebber-epam** [webpack/webpack-dev-server#3259] opened 2021-05-06 16:14 UTC
- Operating System: MacOS
- Node Version: v14.16.0
- NPM Version: v6.14.11
- webpack Version: v5.8.0
- webpack-dev-server Version: v4.0.0-beta0
- Browser: Chrome

- [X] This is a **bug**
- [ ] This is a **modification** request

### Code

Repository: https://github.com/mattwebber-epam/test-single-spa
Screencast of issue: https://imgur.com/a/ja1AI7K

### Expected Behavior

When running our single-spa microfrontend in standalone mode, Webpack HMR should detect changes to our React components and SCSS files within. It should then re-render the browser with the updated changes.

### Actual Behavior

It seems to only detect SCSS changes the first time they change, but does not detect the changes thereafter. It does however refresh the screen when the SCSS file is saved, the issue is that the changes are not included as part of the up to date screen,

### For Bugs; How can we reproduce the behavior?

1. Clone the repository linked above.
2. Run an `npm install`.
3. Run `npm run start:standalone`.
4. Navigate to FormHeader.scss and update the background colour. You should see the browser update with your chosen colour.
5. Change the colour again. Although the browser will refresh, it does not include the latest SCSS changes.

### For Features; What is the motivation and/or use-case for the feature?

N/A

**Comment by joeldenning** [comment] 2021-05-13 17:51
I debugged this a bit today and the root cause appears to be that webpack's `done` hook for the compiler is emitting the same `stats.hash` repeatedly. Since the hash isn't changing, webpack doesn't perform HMR as shown in the following code:

https://github.com/webpack/webpack/blob/4837c3ddb9da8e676c73d97460e19689dd9d4691/hot/dev-server.js#L51-L57

https://github.com/webpack/webpack/blob/4837c3ddb9da8e676c73d97460e19689dd9d4691/hot/dev-server.js#L8-L10

From this, it seems the bug is within webpack rather than webpack-dev-server.

**Comment by alexander-akait** [comment] 2021-05-13 17:56
I will look at this in near future

**Comment by alexander-akait** [comment] 2021-05-14 17:32
I will look at this tomorrow, if it is webpack bug I will reopen/fix it

**Comment by alexander-akait** [comment] 2021-05-15 12:59
No problems... Can you try to chagen `import "./formHeader.scss";` to `import "./FormHeader.scss";` (I see you on macos and you have case insensitivity fs)?

**Comment by joeldenning** [comment] 2021-05-17 16:55
Changing the import specifier fixed it for me on Mac. Thanks @alexander-akait. @mattwebber-epam can you confirm that it works for you too?

**Comment by alexander-akait** [comment] 2021-05-17 16:58
Note - using case insensitivity imports will break bundling your app on windows and linux too, because on other platforms different file names === different modules

**Comment by mattwebber** [comment] 2021-05-17 18:46
@joeldenning  @alexander-akait It seems to have fixed the issue too! Both on Windows & Mac.

**Comment by alexander-akait** [comment] 2021-05-18 11:26
@mattwebber 

> It's strange behaviour for case sensitivity

It is not strange, on linux/windows I can have `module.js` and `Modules.js`, it is different modules, even more when your upload app to server (most of server) doesn't handle requests as case insensitivity. I recommend to setup linter here. 

We have the same issue in webpack repo https://github.com/webpack/webpack/issues/5543, but it will add additional fs calls and reduce performance.

Also here plugin https://github.com/Urthen/case-sensitive-paths-webpack-plugin, but I strongly recommend do it on linter step and do not lose performance.

I want to close this issue, anyway feel free to feedback.

**Closed by alexander-akait** 2021-05-18 11:26 UTC
