### ISSUE TITLE
No data received ERR_EMPTY_RESPONSE webpack

### ISSUE THREAD

**Issue by KhaledMohamedP** [webpack/webpack-dev-server#336] opened 2015-12-07 10:33 UTC
I am trying to run webpack-dev-server, but when I go to `http://localhost:8080/` the browser returns 

    No data received 
    ERR_EMPTY_RESPONSE

**Solution**

I was able to resolve this issue by explicitly telling webpack to use port 3000 

    webpack-dev-server --port 3000

go ->  `http://localhost:3000/`

It's not clear why the server didn't run in the defaulted port number?

**Comment by marconak** [comment] 2016-03-13 15:30
+1

**Comment by AdamGustavsson** [comment] 2016-07-05 07:22
+1

**Comment by KayBeSee** [comment] 2016-07-28 23:56
+1

**Comment by SpaceK33z** [comment] 2016-08-26 10:33
Dupe of #183, which also contains a lot more information about how to fix this.

**Closed by SpaceK33z** 2016-08-26 10:33 UTC
