### ISSUE TITLE
How to do incremental build when it recompiled

### ISSUE THREAD

**Issue by martinko2009** [webpack/webpack-dev-server#770] opened 2017-02-01 13:16 UTC
**Do you want to request a *feature* or report a *bug*?**

I want to request a feature.

**What is the current behavior?**
I know webpack-dev-server will watch the source files which are changed.After these files are changed, webpack-dev-server will recompile these files.
I find it recompile by doing full build. 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I hope it will do incremental build when recompile after files are changed.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
My OS is win7.  
I use webpack-dev-server 1.14.1.

I use command line style to start the webpack-dev-server by the webpack.config.js like below:
```
webpack-dev-server --inline --hot --progress --port 9090
```

**Comment by SpaceK33z** [comment] 2017-02-01 13:20
webpack-dev-server does not do anything related to building, webpack itself does this (you'll see that `webpack --watch` gives the same behavior). See https://github.com/webpack/webpack/issues/1537 and https://github.com/webpack/webpack/issues/1530 for related tickets.

**Comment by martinko2009** [comment] 2017-02-01 13:57
I don't understand what you said.
In development environment, I use webpack-dev-server， it build the source code to memory, if webpack-dev-server does not do anything related to building, and webpack does, then how can I do to increment build. I find log in console that it do full build after I edit one file.Because what I do is multipage application site, there is too many pages in that, when I edit one page, the others are also rebuilt , full rebuilt. It takes too much time.

**Comment by SpaceK33z** [comment] 2017-02-01 16:13
I meant that the package `webpack` itself does all the building, webpack-dev-server just gives you a server to present the webpack assets. If you read the issues I mentioned, you'll read that it actually does an incremental build. You don't really give details about how to reproduce your issue, so I can't really help you...

**Comment by martinko2009** [comment] 2017-02-02 03:35
OK,I tell you the details about how to reproduce.
I package webpack-dev-server.cmd, its content like below:
```
"node.exe"  "%~dp0\node_modules\webpack-dev-server\bin\webpack-dev-server.js" %*
```
I start webpack-dev-server like below:
```
webpack-dev-server --inline --hot --progress --port 9090
```
Though there is no webpack.config.js in the command line,but it uses webpack.config.js by default.
Here is the content of webpack.config.js. My application is multi-page application.
```
process.env.NODE_ENV = "development";
var path = require("path");
var webpack = require("webpack");
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var glob = require('glob');
var entries = getEntry('./src/**/*.js');
var chunks = Object.keys(entries);
module.exports = {
	entry:entries,
	output:{
		path:path.resolve(__dirname,"app"),
		filename:"js/[name].[hash].js",
		chunkFilename:"js/[name].[hash].js",
		publicPath:"/app/"
	},
	module:{
		loaders: [
		  {test: /\.vue$/, loader: 'vue' },
		  {
			test: /\.js$/,
			exclude: /node_modules/,
			loader: 'babel',
			query: {
				compact: false,
				cacheDirectory: true
			}
		  },
		  {test: /\.css$/, loader: "style!css" },
		  {test: /\.scss$/, loader: "style!css!sass"},
		  {test: /\.less$/, loader: "style!css!less"},
		  {
			test: /\.(png|jpg|gif|svg)$/,
			loader: 'url',
			query: {
				limit: 15000,
				name: 'imgs/[md5:hash].[ext]'
			}
		  },
		  { test: /\.(eot|woff|woff2|svg|ttf)$/, loader: "file-loader" },
		  { test: /\.(eot|woff|woff2|svg|ttf)([\?]?.*)$/, loader: "file-loader" }
		]
	},
	resolve:{
		root:[process.cwd() + '/src', process.cwd() + '/node_modules', process.cwd() + '/public'],
		extensions: ['', '.js'],
		alias:{
			 configuration: path.resolve(__dirname,"./public/js/configuration.js"),   
			 jcutils: path.resolve(__dirname,"./public/js/utils.js"),   
			 dateutilselfmade: path.resolve(__dirname,"./public/js/dateutil.js")  
		}
	},
	vue: { // 
		loaders: {
		  js: 'babel',
		  css: ExtractTextPlugin.extract('vue-style-loader', 'css-loader')
		}
	},
	plugins:[
            new webpack.ProvidePlugin({
                "$": 'jquery',
                "jQuery": 'jquery',
				"window.$": 'jquery',
                "window.jQuery": 'jquery',
				"Vue": "vue",
				"configuration": "configuration",
				"jcutils": "jcutils"
            }),
			new webpack.optimize.CommonsChunkPlugin({
				name: 'vendors',
				chunks: chunks,  
				minChunks: chunks.length
			}),
			new webpack.DllReferencePlugin({
				context: __dirname,
				manifest: require('./public/js/dll/manifest/manifest_lib.json'),
			}),
			new ExtractTextPlugin('css/[name].css'),
//			new webpack.optimize.DedupePlugin()
    ],
	babel: {
		presets: ['es2015'],
		plugins: ['transform-runtime']
	},
	devtool: 'cheap-module-source-map',
	cache:true,
	devServer: {
		proxy:{
			"/xxxx/*":{
				target:"http://localhost:8088",
				secure:false
			}
		}	
	}
};


var prod = process.env.NODE_ENV === 'production';
if (prod) {
//delete module.exports.devtool;
  module.exports.plugins = module.exports.plugins.concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
	  mangle: {
        except: ['$super', '$', 'exports', 'require']
      },
	  minimize: true, 
	  output: {comments: false} 
    }),
    new webpack.optimize.OccurenceOrderPlugin()
  ]);
}

var pages = getEntry("./src/**/*.html");
for (var pathname in pages) {
  //
  var conf = {
    filename: './web/' + pathname + '.html', //  export the path of html files
    template: pages[pathname], // 
    inject: true,              // 
    minify: {
      removeComments: true,
      collapseWhitespace: false
    }
  };
  if (pathname in module.exports.entry) {
    conf.chunks = ['vendors', pathname];
    conf.hash = false;
  }
  // how many html files to be generated, we config  the same quatity of HtmlWebpackPlugin object
  module.exports.plugins.push(new HtmlWebpackPlugin(conf));
}

function getEntry(globPath) {
  var entries = {},
    basename, tmp, pathname;

  glob.sync(globPath).forEach(function (entry) {
    basename = path.basename(entry, path.extname(entry));
	var tmpWholeArray = entry.split('/');
	if(tmpWholeArray.length >= 2 && path.extname(entry) == '.js'){
		var libFolder = tmpWholeArray.splice(-2,1);
		if(libFolder != "lib"){
			 var tmp = entry.split('/');
			 var tmp1 = entry.split('/').splice(2, tmp.length-3);
			 pathname = tmp1.join("/") + '/' + basename;   // export js and html's path correctly
			 entries[pathname] = entry;
		}
	}else{
		var tmp = entry.split('/');
		var tmp1 = entry.split('/').splice(2, tmp.length-3);
		pathname = tmp1.join("/") + '/' + basename;    // export js and html's path correctly
		entries[pathname] = entry;
	}
  });
  return entries;
}
```
I just edit one file, but it rebuild all the files like below picture:
![image](https://cloud.githubusercontent.com/assets/3345987/22536260/5d63e100-e93b-11e6-8b89-b8087808fb81.png)

**Comment by martinko2009** [comment] 2017-02-03 08:38
Here is the code location.

[https://github.com/martinko2009/demo](https://github.com/martinko2009/demo)

**Comment by SpaceK33z** [comment] 2017-03-11 15:53
Thanks for the extra info, this looks a lot like this issue; https://github.com/webpack/webpack/issues/309#issuecomment-45703006. I'm going to close this since it's not related to webpack-dev-server.

**Closed by SpaceK33z** 2017-03-11 15:53 UTC
