### ISSUE TITLE
Getting errors on client build. 

### ISSUE THREAD

**Issue by ddaza** [webpack/webpack-dev-server#367] opened 2016-01-11 22:18 UTC
Updated to webpack 
```
├── webpack@1.12.11
├── webpack-core@0.6.8
├── webpack-dev-middleware@1.4.0
├── webpack-dev-server@1.14.1

```

I am seeing an error: 

```
Uncaught TypeError: Cannot read property 'replace' of null
```

in line 5 of `webpack-dev-server/client/index.js` : 

```javascript
var scriptHost = scriptElements[scriptElements.length-1].getAttribute("src").replace(/\/[^\/]+$/, "");
```

**Comment by globexdesigns** [comment] 2016-01-11 23:15
+1

**Comment by zag2art** [comment] 2016-01-12 09:37
+1

**Comment by cloudsan** [comment] 2016-01-12 13:29
+1, rollback to @1.14.0 is fine for me,

**Comment by csaintc** [comment] 2016-01-12 15:25
:+1:

**Comment by le0pard** [comment] 2016-01-15 10:03
The same error after update to 1.4.1

**Comment by liujason** [comment] 2016-01-21 16:41
+1 rolledback to @1.14.0 fixed the problem.

**Comment by jaylinski** [comment] 2016-01-22 19:18
also getting this error on client when adding an inline-script-tag

**Comment by Stas404** [comment] 2016-02-09 14:11
+1 hi all.

**Comment by kwtangerine** [comment] 2016-02-10 07:48
+1. thanks for the tip, rolling back to 1.14.0 works for me too

**Comment by christophehurpeau** [comment] 2016-02-12 18:25
:+1:

**Comment by kenjim83** [comment] 2016-02-12 22:55
+1 me to.  1.14.0 works.

**Comment by Qrysto** [comment] 2016-02-15 09:14
+1, same issue as this and #381. Why is this unresolved for so long?

**Comment by goodseller** [comment] 2016-02-16 06:50
+1

**Comment by jaylinski** [comment] 2016-02-18 07:40
@sokra can you have a quick look at this? there are already two issues and three PRs open for this problem.

**Comment by EwanValentine** [comment] 2016-02-29 15:57
+1

**Comment by jakubzitny** [comment] 2016-03-04 09:42
+1

**Comment by denich** [comment] 2016-03-19 12:29
+1

**Comment by foxtree** [comment] 2016-03-28 16:49
+1

**Comment by incleaf** [comment] 2016-04-10 14:57
+1

**Comment by numical** [comment] 2016-04-13 18:31
+1

**Comment by saponifi3d** [comment] 2016-04-28 23:27
+1

**Comment by EvNaverniouk** [comment] 2016-06-13 15:30
For those who want to make the leap to Webpack 2.0 beta, this issue appears to be fixed in webpack-dev-server `2.1.0-beta.0`

**Comment by SpaceK33z** [comment] 2016-08-21 14:05
Dupe of #117.

**Closed by SpaceK33z** 2016-08-21 14:05 UTC
Labels: bug
