### ISSUE TITLE
Node processes do not exit normally when CTRL+C (SIGINT)

### ISSUE THREAD

**Issue by gaui** [webpack/webpack-dev-server#1093] opened 2017-09-15 11:18 UTC
> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template. Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._
**Please do remove this header to acknowledge this message.**

* Operating System: Windows 10
* Node Version: 8.5
* NPM Version: yarn 1.0.1
* webpack Version: 3.5.5
* webpack-dev-server Version: 2.7.1

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
```

### Expected Behavior

node.exe processes should exit and Webpack shouldn't trigger compile afterwards.

### Actual Behavior

node.exe processes don't exit and Webpack triggers compile afterwards.

### For Bugs; How can we reproduce the behavior?

Clone the repro repo with the appropriate Webpack/dev-server + Node version and follow these steps:
https://github.com/gaui/devserver-node-hang

```
# Install dependencies
yarn

# Run dev server
yarn dev

# Kill Webpack dev server and press CTRL+C

# Remove node_modules folder
rm -rf node_modules
```

**Screencast of bug:**

https://i.imgur.com/8oT04Nn.gif

**Comment by shellscape** [comment] 2017-09-15 12:48
Duplicate of #860

**Closed by shellscape** 2017-09-15 12:48 UTC

**Comment by gaui** [comment] 2017-09-18 20:39
@shellscape Are you sure this is the same issue?

@h6ah4i describes it as:

> Pressing Ctrl+C to stop webpack-dev-server does not work while compiling assets. (NOTE: Ctrl+C works well after finished compilation.)

In my case it doesn't completely kill Node processes after compiling assets.

**Comment by shellscape** [comment] 2017-09-18 20:49
My confidence is high. I believe the point at which the SIGINT actually kicks is in a red herring. The greater issue lies with Windows. If you'd like to add your specific series of events to that issue in a comment, please do :)

**Comment by gaui** [comment] 2017-09-18 21:07
Ok thank you. :)

**Comment by nightlyop** [comment] 2017-12-19 09:47
If you are using Git for Windows, that might be the problem: https://github.com/git-for-windows/git/issues/1219 (There is workaround described in that link).
