### ISSUE TITLE
'setup' deprecation warning issued without 'setup' in use

### ISSUE THREAD

**Issue by bazineta** [webpack/webpack-dev-server#1119] opened 2017-09-27 15:57 UTC
* Operating System: Any
* Node Version: 6.11.3
* NPM Version: 3.10.10
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.9.0

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x ] This is a **modification** request

### Expected Behavior

The new 'setup' deprecation message should be issued only if 'setup' was actually used in the configuration.

### Actual Behavior

Console message issued in all cases:

```
Using "setup" is deprecated and will be removed in the next major version. Please use the "before" and "after" hooks instead.
If "setup" was working fine for you until now, simply replace it with "before"
```

### For Bugs; How can we reproduce the behavior?

Call webpack dev server, using a configuration lacking the 'setup' option.

### For Features; What is the motivation and/or use-case for the feature?

Just spent a bit of time trying to find a non-existent 'setup' in our configuration; would like others not to have to do the same.

**Comment by shellscape** [comment] 2017-09-27 16:53
Duplicate of #1118

**Closed by shellscape** 2017-09-27 16:53 UTC
