### ISSUE TITLE
Running webpack-dev-server on this project runs fine on windows but not on mac

### ISSUE THREAD

**Issue by finbarmaginn** [webpack/webpack-dev-server#317] opened 2015-11-17 12:10 UTC
Hi when I run `webpack-dev-server` on windows for this project (after running npm i) https://github.com/finbarmaginn/one_page_app and then navigating to the browser I get No data received error in chrome in the mac. However this works fine in windows.

```js
"devDependencies": {
    "autoprefixer-loader": "^3.1.0",
    "babel-core": "^6.1.20",
    "babel-loader": "^6.1.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "css-loader": "^0.22.0",
    "less": "^2.5.3",
    "less-loader": "^2.2.1",
    "style-loader": "^0.13.0",
    "tape": "^4.2.2",
    "webpack": "^1.12.4",
    "webpack-dev-server": "^1.12.1"
  },
  "dependencies": {
    "react": "^0.14.2",
    "react-dom": "^0.14.2",
    "babel-polyfill": "^6.1.19"
  }
```

**Comment by QuantumInformation** [comment] 2015-11-17 12:12
I also experience the same issue with 2 separate project on the mac.

**Comment by SpaceK33z** [comment] 2016-08-27 09:27
Dupe of #183, which contains many suggestions to fix this.

**Closed by SpaceK33z** 2016-08-27 09:27 UTC
