### ISSUE TITLE
Malformed paths when trying to view `/webpack-dev-server` route [Windows]

### ISSUE THREAD

**Issue by kaiyoma** [webpack/webpack-dev-server#1386] opened 2018-04-24 00:55 UTC
* Operating System: Windows 10
* Node Version: 8.9.0
* NPM Version: 5.5.1
* webpack Version: 4.6.0
* webpack-dev-server Version: 3.1.3

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
According to [this page](https://webpack.js.org/configuration/dev-server/#devserver):

> If you're having trouble, navigating to the /webpack-dev-server route will show where files are served. For example, http://localhost:9000/webpack-dev-server.

However, when I try that with my dev server, I get a JS backtrace in the console:

```
Error: no such file or directory
    at MemoryFileSystem.readdirSync (C:\...\node_modules\memory-fs\lib\MemoryFileSystem.js:126:10)
    at writeDirectory (C:\...\node_modules\webpack-dev-server\lib\Server.js:124:34)
    at Server.app.get (C:\...\node_modules\webpack-dev-server\lib\Server.js:156:5)
    at Layer.handle [as handle_request] (C:\...\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\...\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\...\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\...\node_modules\express\lib\router\layer.js:95:5)
    at C:\...\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\...\node_modules\express\lib\router\index.js:335:12)
    at next (C:\...\node_modules\express\lib\router\index.js:275:10)
```

### Actual Behavior
I'm not sure exactly (since I've never used this feature), but I was expecting something helpful to happen.

### For Bugs; How can we reproduce the behavior?
Visit `http://localhost:9000/webpack-dev-server` for a dev server.

**Comment by kaiyoma** [comment] 2018-04-24 01:51
I'm having a lot of trouble upgrading our project to webpack 4 (webpack-dev-server refuses to "just work") and this feature appears to be the only thing that could help. And it's seemingly broken. 😭

**Comment by joyfulelement** [comment] 2018-04-26 21:06
I'm having the exact same issue with a setup of webpack 4 + webpack-dev-server setup with node.js (version `v8.9.1`). Still digging...

**Comment by andreasschuele** [comment] 2018-04-29 10:43
I had the same issue. It looks like to be an issue with path handling, since after removing white space from my project path it did work again.

**Comment by evilebottnawi** [comment] 2019-02-22 14:15
Closing in favor https://github.com/webpack/memory-fs/issues/59, also we have problem in `webpack-dev-middleware` and already fixed this problem, so update deps, if problem still exists feel fee to open new issue with reproducible test repo, thanks

**Closed by evilebottnawi** 2019-02-22 14:15 UTC
Labels: priority: 3 (important), scope: fs, severity: 3 (broken), type: bug
