### ISSUE TITLE
"webpack-dev-server --progress --inline" reloading page on devServer timeout

### ISSUE THREAD

**Issue by misuzu** [webpack/webpack-dev-server#369] opened 2016-01-13 10:29 UTC
I guess proxy timeout (just the way backend works) triggers page reload.
Chrome Dev Tools screenshot: http://i.imgur.com/aLoA4xm.png http://i.imgur.com/3WSpBmc.png

Chromium 46.0.2490.71
nodejs v4.2.4
webpack 1.12.11
webpack-dev-server 1.14.1

webpack.config.js:
```js
var autoprefixer = require('autoprefixer')
var path = require('path')
var webpack = require('webpack')


module.exports = {
    entry: {
        app: path.resolve(__dirname, 'app', 'index.js'),
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name].js'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    compact: false,
                    cacheDirectory: true,
                    presets: ['es2015', 'react'],
                },
            },
            {
                test: /\.css$/,
                loader: 'style!css'
            },
            {
                test: /\.scss$/,
                loaders: ['style', 'css', 'postcss', 'sass']
            },
            {
                test: /\.(png|jpg|gif)$/,
                loader: 'url-loader?limit=4096&name=[name].[ext]'
            },
            {
                test: /\.(html|svg|eot|woff|woff2|ttf)$/,
                loader: 'file?name=[name].[ext]'
            }
        ]
    },
    postcss: [
        autoprefixer({
            browsers: ['last 2 versions']
        })
    ],
    devServer: {
        proxy: {
            '/*': {
                target: process.env.SERVER,
                secure: false,
                changeOrigin: true,
            },
        },
    },
    plugins: (process.env.NODE_ENV == 'production') ? [
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify(process.env.NODE_ENV)
            },
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        }),
        new webpack.optimize.DedupePlugin(),
    ] : [],
}
```

**Comment by margru** [comment] 2016-04-05 13:21
I'm experiencing a similar issue with AJAX requests which are proxied to a backend server. It's a big issue as even POST requests are sent again by the webpack dev proxy server and thus creating multiple records on the server side (the creation takes some minutes to finish as some calculation are done there). Is there any possibility to set the proxy timeout or to avoid it completely?

**Comment by oers** [comment] 2016-07-20 07:12
This was giving me major headaches. There seems to be hard wired timeout (like 2 minutes) after which the proxy sends the request again.
I too have long running actions.
The second request will always crash due to database locks and report a failure to the client.

I really need a way to disable this proxy timeout or set it to a higher value.

**Comment by SpaceK33z** [comment] 2016-09-03 14:07
This was fixed with PR #478, and released with `1.15.0`.

**Closed by SpaceK33z** 2016-09-03 14:07 UTC

**Comment by Martin-Wegner** [comment] 2016-11-23 16:04
@SpaceK33z please reopen this issue because we got the same behaviour with 2.1.0-beta.11 :( We have a long running job (3-4 minutes) and after 2 minutes the proxy sends a second request to the server.

**Comment by SpaceK33z** [comment] 2016-11-23 16:10
Can you provide an easy way of testing this? Or are you willing to send a PR?

**Comment by Martin-Wegner** [comment] 2016-11-23 16:15
Hopefully @phillipj can fix it? An easy way, hmmm, a REST interface which waits 3 minutes before responding and logging all incoming requests... Or a nodejs server which the same functionality...

**Comment by phillipj** [comment] 2016-11-23 17:40
Reading the previous comments here, the issue here is requests being retryed? Not the whole webapp being reloaded, like which was the issue issue in #478.

Worth mentioning that 2 minutes is the default timeout in Node.js core, that's probably the reason several of you have experienced a 2 minute timeout. It's configurable with https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_request_settimeout_timeout_callback

**Comment by Martin-Wegner** [comment] 2016-11-23 17:47
@phillipj how to set the timeout for the webpack dev server proxy?

**Comment by phillipj** [comment] 2016-11-23 17:50
ATM I don't know -- I don't have a computer available, and reading the source code on mobile isn't really my thing 😕

**Comment by Martin-Wegner** [comment] 2016-11-23 18:02
@phillipj it would be great if you could find it out next time you have a real computer :)

**Comment by phillipj** [comment] 2016-12-04 11:06
As most of the proxy functionality comes from [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware), I'd try providing the `proxyTimeout` option:

```js
devServer: {
  proxy: {
    '/*': {
        target: process.env.SERVER,
        secure: false,
        changeOrigin: true,
        proxyTimeout: 1000 * 60 * 5, // 5 minutes
    },
  },
},
```

**Comment by Martin-Wegner** [comment] 2016-12-05 08:59
@phillipj this does not help :( After 2 minutes the request was repeated :(

Please checkout this little example:

https://github.com/Martin-Wegner/webpack-dev-server-issue-369

and run `npm install` and `npm start`.

Finally open your brower and go to `http://localhost:8080/test/`.

You will see the message `incoming request` and after 2 minutes as second message `incoming request`.

**Comment by phillipj** [comment] 2016-12-07 22:01
@Martin-Wegner thanks for creating that repro project!

I've done some digging now, and haven't found anything in webpack-dev-server or the [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) explicitly doing some retrying for *all* HTTP requests being proxied.

Because of that I started suspecting the browser as the culprit, and found a couple of hints suggesting that actually might be the case: http://stackoverflow.com/a/19697278. That's new to me and I've never encountered this before, but I don't have any other suspects ATM.

**Comment by Martin-Wegner** [comment] 2016-12-08 09:41
@phillipj thanks.

>  when the connection is closed before receiving a response from the server

But who closes the connection?

In general the connection should not be closed and therefore no retry should be applied. A good example is the use of asynchronous servlets for web push notifications.

**Comment by phillipj** [comment] 2016-12-11 00:18
> But who closes the connection?

Excellent question which made me do another round of digging, which let me to find the culprint.

[http-proxy](https://github.com/nodejitsu/node-http-proxy) doesn't set a timeout on the incoming request, 
which is 2 minutes as default, and therefore closes the incoming request too early even when `proxyTimeout` is set.

The `proxyTimeout` option only sets timeout on the outgoing request the proxy makes, which is neccessary to solve this issue,
but it's only one of the two timeouts which needs to be set.

Although not documented, incoming requests to a Node.js HTTP server has timeout of 2 seconds. If one wants to change that,
[request.setTimeout()](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_message_settimeout_msecs_callback) has to be invoked.

By invoking `req.setTimeout()` in [http-proxy's request listener](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/index.js#L36) and doing something similar in your repro server https://github.com/Martin-Wegner/webpack-dev-server-issue-369/pull/1, I was able to get the `Hello World` message printed.

I probably won't be able to open a PR against the http-proxy module in the next few days, so anyone who wants to give it a shot, please go ahead.

**Comment by Martin-Wegner** [comment] 2016-12-12 15:52
@phillipj a PR would be great :)

**Comment by phillipj** [comment] 2017-03-17 23:29
@Martin-Wegner sorry for dropping the ball on this. I've submitted the PR https://github.com/nodejitsu/node-http-proxy/pull/1154, fingers crossed we'll get this fixed at last.

**Comment by mohankumarv2005** [comment] 2017-12-06 15:43
Solved, please see https://github.com/webpack/webpack-dev-server/issues/369

Need to set timeout in Server.js
