### ISSUE TITLE
configuration has an unknown property 'outputPath'

### ISSUE THREAD

**Issue by jeusdi** [webpack/webpack-dev-server#701] opened 2016-11-17 12:01 UTC
`webpack-dev-server` is telling me:

```
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'outputPath'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiF
allback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }
```

`webpack` works fine and generates everything well.

These are my config files:

 * [webpack.common.js](https://gist.github.com/jeusdi/134e19006a6f8da06bf4123c35d8a8a7)
 * [webpack.dev.js](https://gist.github.com/jeusdi/365e8cc433ef629d6246776dce0e3092)
 * [webpack.prod.js](https://gist.github.com/jeusdi/919e6228b753cbe67f72edfd613a8c99)

**webpack and webpack-dev-server version:**
webpack: 1.10.x/2.x 
webpack-dev-server: 1.x/2.x

**Please tell us about your environment:**
Windows 10

**Comment by SpaceK33z** [comment] 2016-11-17 12:07
`outputPath` isn't a valid option in webpack-dev-server, it doesn't do anything.

**Comment by jeusdi** [comment] 2016-11-17 12:16
Now it's telling me:

```
# webpack-dev-server --config config/webpack.dev.js --progress --profile --content-base src/                                                       10% building modules 3/3 modules 0 active
Project is running at http://localhost:3000/
webpack output is served from /
Content not from webpack is served from D:\projects\living\user-platform\project\src
404s will fallback to /index.html                                                                                                     9304ms building modules                                                                           4ms add1m150ms 226ms asset82ms emitting
[default] Checking started in a separate process...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Console.warn (console.js:51:16)
    at printErrorAndExit (D:\projects\living\user-platform\project\node_modules\source-map-support\source-map-support.js:406:11)
    at process.emit (D:\projects\living\user-platform\project\node_modules\source-map-support\source-map-support.js:419:16)
    at process._fatalException (bootstrap_node.js:292:26)
```

**Comment by SpaceK33z** [comment] 2016-11-20 14:55
You seem to be using the package `source-map-support`. Could you temporarily disable it and see if that resolves it?

**Comment by jeusdi** [comment] 2016-11-21 08:00
Thanks @SpaceK33z . I'm not able to find out what I need to comment.

Which line do I need to comment?

**Comment by SpaceK33z** [comment] 2016-11-24 10:22
@jeusdi, I also don't know where it is, but the stack trace you posted doesn't seem to come from anything that is installed by webpack or webpack-dev-server. I'd suggest to remove some plugins / loaders and check where the issue is.

**Comment by jeusdi** [comment] 2016-11-25 09:06
Mmm, I've asked it on [this question on stackoverflow](http://stackoverflow.com/questions/40780892/webpack-dev-server-doesnt-start/40790691#40790691). What do you think about that?

**Comment by SpaceK33z** [comment] 2016-11-25 09:38
I'm going to close this and put a clear warning in the README that webpack-dev-server has issues with Node.js v7.

**Closed by SpaceK33z** 2016-11-25 09:38 UTC
Labels: X0: need more information

**Comment by kousithiru** [comment] 2017-03-29 05:13
Unknown property "Service" It displays a message like this what to do ?

**Comment by stevematdavies** [comment] 2017-09-29 08:50
configuration has an unknown property 'modules'.

React 2.5.1 and followed all advice, documentation is useless. Any help?
