### ISSUE TITLE
Update webpack-dev-middleware to 4.0.0 for support webpack 5.X

### ISSUE THREAD

**Issue by altro3** [webpack/webpack-dev-server#2805] opened 2020-10-29 19:55 UTC
- Operating System: Win10
- Node Version: 15.0.1
- NPM Version: 6.14.8
- webpack Version: 5.3.1
- webpack-dev-server Version: 3.11.0
- Browser: Firefox 82.0.2

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior

No warning should be shown. Need to update webpack-dev-middleware to 4.0.0 version.

See https://github.com/webpack/webpack-dev-middleware/issues/741.

Already released here: https://github.com/webpack/webpack-dev-middleware/releases/tag/v4.0.0

### Actual Behavior

Have warning every build:
```
[4/5] Linking dependencies...
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has incorrect peer dependency "webpack@^4.0.0".
```

### For Bugs; How can we reproduce the behavior?

Just run `yarn install` with `"webpack": "^5.3.1"` and `"webpack-dev-server": "^3.11.0"`

As I understood from the webpack documentation, the devserver already supports webpack 5. Or not? If yes, then you should pay attention to this warning.

**Comment by ylemkimon** [comment] 2020-10-29 22:46
Duplicate of #2784.

**Closed** 2020-10-30 10:19 UTC
