### ISSUE TITLE
Issue with Chrome Popup Blocker Pro extension and webpack dev mode

### ISSUE THREAD

**Issue by jneveux** [webpack/webpack-dev-server#457] opened 2016-04-18 20:23 UTC
Hi,

I encountered a problem with Chrome extension http://popup-blocker.org/ which is injecting a script tag at the end of the index page. 

The script webpack-dev-server/client/index.js is looking for the last script tag:
` var scriptElements = document.getElementsByTagName("script"); var scriptHost = scriptElements[scriptElements.length-1].getAttribute("src").replace(/\/[^\/]+$/, ""); `

Original issue https://github.com/AngularClass/angular2-webpack-starter/issues/511(which took me a few hours to detect.)

It would be nice, if the webpack script tag selection could rely on something other than being the last one. 

Thanks,

Jean

**Comment by SpaceK33z** [comment] 2016-08-27 10:31
This is kind of a dupe of #117. We're discussing ways to improve the current script detection over there.

**Closed by SpaceK33z** 2016-08-27 10:31 UTC
Labels: enhancement
