### ISSUE TITLE
CORS Access-Control-Allow-Origin problem with v1.11.0

### ISSUE THREAD

**Issue by dlong500** [webpack/webpack-dev-server#277] opened 2015-09-22 11:06 UTC
Upgrading to webpack-dev-server 1.11.0 from 1.10.1 produces the output shown in the screenshot with errors due to missing or improper CORS headers.  Rolling back to v1.10.1 eliminates the errors.  I haven't changed any other configuration.

![screenshot-2015-09-22-06 56 53](https://cloud.githubusercontent.com/assets/430481/10016810/8c028a7a-60f7-11e5-9a7a-b0c62d2e16b9.png)

**Comment by jinishiu** [comment] 2015-09-23 22:28
Same problem with Node 4. Getting back to Node 0.12 fixed the problem. Don't have time to investigate more.

**Comment by dlong500** [comment] 2015-09-30 08:44
Anyone have updates on this?  I'd like to update to the latest version but the problem is still present with v1.12.0

**Comment by dlong500** [comment] 2015-09-30 09:02
Well, after doing some searching I tried adding the following to the config:

    headers: { "Access-Control-Allow-Origin": "http://localhost:4000", "Access-Control-Allow-Credentials": "true" }

I'm not getting errors anymore so I think things are working.  However, I'm a bit perplexed as to what changed after v1.10.1 because I did not have errors before without that headers parameter.

**Comment by bennidi** [comment] 2015-10-09 14:26
I am seeing the same warnings. It also breaks hot module replacement and connection with browsersync. Downgrade to older version of webpack-dev-server did not help. I am running on iojs 2.3.4

webpack: 1.12.2
webpack-dev-server: 1.10.1
webpack-streams: 2.1.1

Interestingly I just noticed that this problem only exists with chrome: Version 45.0.2454.101 Ubuntu 15.04 (64-bit)

Firefox continued to work fine. I did a system update yesterday, then an npm install today and mixed that with some structural refactorings of my build....(good idea?!) Sudddenly all those warnings. Freaked my out quite a bit.

**Comment by dlong500** [comment] 2015-10-10 14:54
@bennidi Do you have the headers parameter set in your dev-server config like I mentioned above?  That solved the issue for me and everything is working with the latest versions of Node and webpack-dev-server.  I don't know why things changed between versions but adding that fixed it for me.

**Comment by bennidi** [comment] 2015-10-11 09:37
@dlong500 Yes, I tried the header parameter. It didn't work for me.

**Comment by Liu-Huaqing** [comment] 2015-11-27 05:17
@dlong500 I tried the header parameter. It also does not work for me. So I set the webpack-dev-server back to 1.10.1 as you recommended. Thanks very much.

**Comment by jbasdf** [comment] 2015-12-08 01:53
I ran into the same issue with CORS. Rolling back to 1.10.1 fixes the issue. Any idea what changed between 1.10.1 and 1.11.0 to cause this problem?

**Comment by ivan-kleshnin** [comment] 2015-12-21 10:28
Same problem with webpack-dev-server 1.14.0. 
SockJS still [didn't not release](https://github.com/sockjs/sockjs-node/issues/177) update 0.3.16 which should fix the root cause of this error.

**Comment by tonyqian66** [comment] 2016-06-23 19:46
@dlong500, could you please tell me which configuration file you added and where.
headers: { "Access-Control-Allow-Origin": "http://localhost:4000", "Access-Control-Allow-Credentials": "true" }

Thanks,

**Comment by dlong500** [comment] 2016-06-23 21:03
@tonyqian66 To be honest, it's been a while since I used this configuration because I switched to invoking webpack middleware in the main server file using `hapi-webpack-plugin` (I currently use hapi as my main server, but there are also webpack middleware plugins for express).  Doing it that way really simplifies the whole webpack-dev-server implementation in my experience.

What I was previously doing was invoking webpack-dev-server from a gulp task.

So, for example, if I required `webpack-dev-server` in the gulpfile like so:

```javascript
var WebpackDevServer = require('webpack-dev-server');
```

Then I might have a task configured like this:
```javascript
gulp.task('webpack-watch', function(done) {
  new WebpackDevServer(webpack(frontendConfig), {
    publicPath: "http://localhost:3000/public/build/js/",
    headers: { "Access-Control-Allow-Origin": "http://localhost:4000", "Access-Control-Allow-Credentials": "true" },
    hot: true,
    stats: outputOptions
  }).listen(3000, 'localhost', function (err, result) {
    if(err) {
      console.log(err);
    }
    else {
      console.log('webpack dev server listening at localhost:3000');
    }
  });
});
```

**Comment by tonyqian66** [comment] 2016-06-24 12:59
Davison,


Really appreciate your prompt reply.


Tony


________________________________

**Comment by SpaceK33z** [comment] 2016-08-25 16:54
Closing because author says it's fixed...

**Closed by SpaceK33z** 2016-08-25 16:54 UTC
