### ISSUE TITLE
v3.2.0 Breaks host parameter passed with options falling back to localhost

### ISSUE THREAD

**Issue by shobhitsharma** [webpack/webpack-dev-server#1675] opened 2019-02-20 21:37 UTC
- Operating System: macOS Mojave
- Node Version: 10.15.1
- NPM Version: 6.x
- webpack Version: 4.x
- webpack-dev-server Version: 3.2.0

- [x] This is a **bug**
- [ ] This is a **modification** request

```js
...
devServer: {
   host: 'custom.local.host' // Gets disregarded
}
```

**Comment by evilebottnawi** [comment] 2019-02-21 09:15
@shobhitsharma Please describe you issue more verbosely, what do you mean `Breaks host parameter`?

**Comment by evilebottnawi** [comment] 2019-02-21 10:02
Please create minimum reproducible test repo

**Comment by miketownsend** [comment] 2019-02-22 15:13
* Operating System: macOS Mojave
* Node Version: 10.15.1
* NPM Version: 6.x
* webpack Version: 4.x
* webpack-dev-server Version: 3.2.0

* [x]  This is a **bug**
* [ ]  This is a **modification** request

I am seeing the same issue, and have a project serving html with a local ssl certificate on:
https://app.domain.com:3000

The webpack assets are served on:
https://app.domain.com:8080

Using:

```
{
  devServer: {
    hot: true,
    inline: true,
    disableHostCheck: true,
    host: '0.0.0.0',
    headers: {
      'Access-Control-Allow-Origin': 'https://app.domain.com:3000'
    },
    https: {
      key: fs.readFileSync(path.join(__dirname, '../localssl/server.key')),
      cert: fs.readFileSync(path.join(__dirname, '../localssl/server.crt'))
    }
  }
}
```

Chrome now rejects assets from webpack due to ssl certificate host check.

**Comment by shobhitsharma** [comment] 2019-02-23 09:56
@evilebottnawi This resolves the issue for me https://github.com/webpack/webpack-dev-server/pull/1686. If you guys have better ideas up there, feel free to commit and let me know.

**Comment by phil-lgr** [comment] 2019-02-24 04:03
v3.2.0 broke my --https setup with --host I get the autogenerated certificate instead of the one I pass in parameters

**Comment by phil-lgr** [comment] 2019-02-24 04:11
I don't understand the changes here: https://github.com/webpack/webpack-dev-server/commit/0b89fd9#diff-15fb51940da53816af13330d8ce69b4e cc @evilebottnawi 

@shobhitsharma  It's sad that such a change was merged and released! Hopefully your revert can be merged quickly!

**Comment by phil-lgr** [comment] 2019-02-24 04:39
Repro: https://github.com/phil-lgr/repro-https-issue

![image](https://user-images.githubusercontent.com/9644867/53295174-cbde3a80-37c3-11e9-8b03-bd7af37f99e4.png)

![image](https://user-images.githubusercontent.com/9644867/53295183-fb8d4280-37c3-11e9-9ca7-1eecb49dcfee.png)

**with "webpack-dev-server": "3.1.14"**:

![image](https://user-images.githubusercontent.com/9644867/53295205-5030bd80-37c4-11e9-8a0d-84099650a31a.png)

**Comment by phil-lgr** [comment] 2019-02-24 04:43
basically... all the --cert --key args are ignored

**Comment by phil-lgr** [comment] 2019-02-24 04:46
Looks like v3.2.0 just ignores --cert --key and the other --https args? let me know if you have any questions

**Comment by evilebottnawi** [comment] 2019-02-25 09:35
@phil-lgr please don't post issue in difference issue, create new issue instead

**Closed** 2019-02-25 10:35 UTC

**Comment by shobhitsharma** [comment] 2019-02-25 13:11
@evilebottnawi Please write better testing in future to prevent issues like this.

**Comment by evilebottnawi** [comment] 2019-02-25 13:30
@shobhitsharma it is open source and i am maintaining many projects and sometimes doesn't have enough time on all test cases, you can help us just send a PR with more tests
