### ISSUE TITLE
Webpack-dev-server version 4.12.0 causing compile errors in application

### ISSUE THREAD

**Issue by AlmaFenetre** [webpack/webpack-dev-server#4771] opened 2023-03-15 12:36 UTC
### Bug report
Webpack-dev-server version 4.12.0 causes compile errors in application on browser viewport resize

### Actual Behavior

We run an application which uses webpack-dev-server 4.12.0 as a dependency. With this version of webpack-dev-server, whenever we resize the browser viewport in our application (e.g. by opening developer tools), an error overlay pops up stating "ResizeObserver loop limit exceeded". _This behaviour does not occur in the exact same version of the application that uses webpack-dev-server version 4.11.1_.

![image](https://user-images.githubusercontent.com/95417235/225309115-e5f8c1a7-5619-4f84-b41e-f0038a6205a5.png)

### Expected Behavior

The error should not appear when resizing the browser viewport in any way.

### How Do We Reproduce?

- Run an application that uses webpack-dev-server version 4.12.0
- Open developer tools in the browser

![image](https://user-images.githubusercontent.com/95417235/225310066-48c94ae3-4ea8-4df6-b0f1-5ae3f755fdc3.png)

![image](https://user-images.githubusercontent.com/95417235/225310141-2d886ba0-44ed-407b-94f9-cb9a83251f9b.png)

![image](https://user-images.githubusercontent.com/95417235/225310267-2a3b0394-742a-45cf-a9f9-3bb3e59ae1d1.png)

**Comment by AugustoPreis** [comment] 2023-03-15 20:33
Same problem here

**Comment by alexander-akait** [comment] 2023-03-15 22:17
> How Do We Reproduce?
> Run an application that uses webpack-dev-server version 4.12.0
> Open developer tools in the browser

Sorry I can't please provide normal reproducible test error,we don't have `ResizeObserver` at all in our code, so I think you have a non official plugin and something that patch your webpack runtime, without good example and configuration I can't help you, please in future avoid using screenshots for such errors, because rewritting takes a lot of time

There is a PR for our new overlay and it was improved and redesign https://github.com/webpack/webpack-dev-server/commit/87a26cf4c1fd9ac8140d345a8520a8d5cb059556 and you will not find there something criminal 

Please avoid any spam, if you need help, provide a reproducible test repo as we ask and I will help you

**Comment by AlmaFenetre** [comment] 2023-03-16 08:15
> please in future avoid using screenshots for such errors, because rewritting them takes a lot of time

The error text is literally in the bug description.

`
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.40.1",
    "@typescript-eslint/parser": "^5.40.1",
    "@vue/cli-plugin-babel": "^5.0.8",
    "@vue/cli-plugin-eslint": "^5.0.8",
    "@vue/cli-plugin-typescript": "^5.0.8",
    "@vue/cli-service": "^5.0.8",
    "@vue/eslint-config-typescript": "^9.1.0",
    "babel-eslint": "^10.1.0",
    "copy-webpack-plugin": "^11.0.0",
    "cross-env": "^5.2.0",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3",
    "sass": "1.43.4",
    "sass-loader": "10.2.0",
    "typescript": "4.2.4",
    "vue-reactive-provide": "^0.3.0",
    "vue-template-compiler": "2.6.14"
  },
`

our dev dependencies

the error this morning:
ERROR
ResizeObserver loop completed with undelivered notifications.
./node_modules/webpack-dev-server/client/overlay.js/createOverlay/<@https://localhost:50009/js/chunk-vendors.js:469001:56
EventListener.handleEvent*listenToRuntimeError@https://localhost:50009/js/chunk-vendors.js:469128:10
createOverlay@https://localhost:50009/js/chunk-vendors.js:468994:82
./node_modules/webpack-dev-server/client/index.js?protocol=wss&hostname=localhost&port=50009&pathname=%2Fws&logging=none&progress=true&overlay=%7B%22errors%22%3Afalse%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true@https://localhost:50009/js/chunk-vendors.js:467834:73
__webpack_require__@https://localhost:50009/js/app.js:5349:33
@https://localhost:50009/js/app.js:6569:83
__webpack_require__.O@https://localhost:50009/js/app.js:5398:23
@https://localhost:50009/js/app.js:6572:53
@https://localhost:50009/js/app.js:6574:12

As for a test repo, it is like I said, install webpack-dev-server 4.12.0 in an application and then open and close the developer tools a few times in a browser of your choice (I've seen it happen in Chrome, Edge and Firefox).

If this is not enough, please be more clear in what you need from me to be able to look into this issue.

**Comment by malcolm-kee** [comment] 2023-03-16 09:31
@alexander-akait  I think it may be caused by the runtime error catching behavior. I'll see if I can add new config options to opt-out this behavior next week.

Does that sounds like good idea to you?

**Comment by malcolm-kee** [comment] 2023-03-16 09:37
@AlmaFenetre thanks for raising the issue, I'm sorry that you have some issue with the latest release.

Regarding reproduction, knowing 4.12.0 cause error in your setup does tell us that some change in 4.12.0 cause the error, but it doesn't tell us "in what scenario it has issue", which is important to create a proper fix. 

A popular project like `webpack-dev-server` can be used in so many ways, having a minimal reproduction example allows us to understand what's happening. Thank you.

**Comment by alexander-akait** [comment] 2023-03-16 10:35
> @alexander-akait I think it may be caused by the runtime error catching behavior. I'll see if I can add new config options to opt-out this behavior next week.

> Does that sounds like good idea to you?

Can you clarify, I think they have custom scripts for our runtime and because our HTML was changed they have a problems now, usually I closed such issues, because no one provide how we can reproducible it and we don't have `ResizeObserver`, and yes, if it was a bug regression we will have here a lot of issues and :+1: 

I will keep open some times, if noone give normal reproducible example I will close, unfortunately we are not magicians

**Comment by alexander-akait** [comment] 2023-03-16 12:20
@malcolm-kee  Can you check it, maybe we don't respect it? But we have tests...

**Comment by AlmaFenetre** [comment] 2023-03-16 12:21
https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded

From this link:
"﻿This error means that ResizeObserver was not able to deliver all observations within a single animation frame. It is benign (your site will not break)."

So what I think is happening is that all errors (including benign ones that are ignored by the application, as they do not show up in the developer console in my instance) are nevertheless bubbled up to webpack-dev-server's error overlay.

**Comment by aeggum** [comment] 2023-03-16 14:16
I'm also seeing this.  

In my case I have multiple apps, but I only get the immediate overlay with errors when resizing in one of my apps.   In each of them, any logged JS error leads to the overlay. This is despite having `client: { overlay: false }` in my webpack config, as @nstepien mentioned.  I have not tried the CLI argument `--no-client-overlay`.

This happens on 4.12.0 but if I use 4.11.1 hiding the overlay works as expected.

**Comment by crobinson42** [comment] 2023-03-16 17:06
I am experiencing this issue as well. `client: { overlay: false }` & `--no-client-overlay` are not respected.

Inspecting the code, these options are never passed to `createOverlay()`. Here is the PR to get merged and published ASAP: https://github.com/webpack/webpack-dev-server/pull/4773

**Comment by crobinson42** [comment] 2023-03-16 17:13
The temporary work-around for frustrated developers is to rollback to v4.11.1 or manually comment this line out in `node_modules/webpack-dev-server`: 
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/5973579/225699085-058c6532-ee99-4138-b901-7671315df0c6.png">

**Comment by alexander-akait** [comment] 2023-03-16 19:58
Overlay will be fixed soon, with `ResizeObserver` I don't undestand, somebody can provide an example of this?

**Comment by crobinson42** [comment] 2023-03-16 19:59
@alexander-akait `ResizeObserver` is a motherfucker in browsers, we can blame the chromium team for the annoying error related to missing frames in the browser 😂.

**Comment by alexander-akait** [comment] 2023-03-16 20:59
Oh, I see, we can provide an option to disable this behaviour, I thought it will be better experience, but looks like not for all

**Comment by crobinson42** [comment] 2023-03-16 21:01
@alexander-akait a really "nice to have" feature would be an option to filter errors/warnings ie:

```typescript
client: {
 errors?: boolean | (error: Error) => boolean
 warnings?: boolean | (warn: unknown) => boolean
}
```

Where we could use it like:

```js
client.errors = (error) => !error.message.includes('ResizeObserver')
```

**Comment by alexander-akait** [comment] 2023-03-16 23:58
Ideally:
```
client: {
 errors?: boolean | (error: Error) => boolean
 warnings?: boolean | (warn: unknown) => boolean
 runtimeErrors?: boolean | (error: Error) => boolean
}
```

But let's implement boolean firstly, so you can disable it if you need, and then we can look at serilization

**Comment by alexander-akait** [comment] 2023-03-16 23:59
Becaise `errors` and `runtimeErrors` are different things, mostly you should not ignore `error` because they are from compilation, but you can ignore runtimeErrors, for example you can implement only part of application and another part can be buggy

**Comment by alexander-akait** [comment] 2023-03-17 00:00
I think we will close such problem today (I need some rest after 12 hours of work), so workaround - keep 4.11.1 temporary

**Comment by RichieChoo** [comment] 2023-03-17 02:38
lock version  4.11.1

**Comment by alexander-akait** [comment] 2023-03-17 22:08
Link on improvements https://github.com/webpack/webpack-dev-server/issues/4777, 
Fixes https://github.com/webpack/webpack-dev-server/pull/4773/,

Please open an issue if you faced with problems in your versions, let's don't mix them in one issue and please follow the issue template, thank you

**Closed** 2023-03-17 22:07 UTC

**Comment by alexander-akait** [comment] 2023-03-17 22:20
https://github.com/webpack/webpack-dev-server/releases/tag/v4.13.0

**Comment by redbugz** [comment] 2023-03-23 12:10
This bit us as well, hampering local development. Another very confusing aspect is this is listed as a compilation error when it's not. We were aware of the ResizeObserver issue in other contexts and had measures to deal with it, however, suddenly it started showing up as a compilation error in webpack, which made no sense as it doesn't show up in the build console during compilation, and we were stumped as to why what is normally a runtime error had suddenly morphed into a compilation error.
If you are going to show runtime errors now as well, please don't label them as compilation errors, label them properly as runtime errors.

**Comment by malcolm-kee** [comment] 2023-05-11 02:29
To close the loop, this is documented https://webpack.js.org/configuration/dev-server/#overlay

**Comment by an-parubets** [comment] 2024-02-23 10:11
> I'm seeing this as well. What's really frustrating is that I have `client: { overlay: false }` set up so WDS won't show up any overlay, yet is still does, why? We use WDS to run custom visual regression tests in CI, and WDS now breaks them by displaying an overlay we didn't opt in to, and swallows the errors.

Thank you! This solved my problem
