### ISSUE TITLE
Webpack-dev-server output directory incorrect

### ISSUE THREAD

**Issue by ShadeAJ1** [webpack/webpack-dev-server#2153] opened 2019-07-26 21:54 UTC
I am making an Ionic4 app with an AWS backend. When running ionic serve in the terminal to test my app in the browser, I see the following output on terminal...

```
[ng] ℹ ｢wds｣: Project is running at http://localhost:8100/webpack-dev-server/
[ng] ℹ ｢wds｣: webpack output is served from /
[ng] ℹ ｢wds｣: 404s will fallback to //index.html
```

I took the following steps to try and fix the problem...

- Delete all the node_modules and reinstalling them with npm install
- Make a webpack.config.js file in the root directory of the project with the following code as per what webpack says.

```
var path = require('path');

module.exports = {
  //...
  devServer: {
      contentBase: path.join(__dirname, 'src'),
      compress: true,
      port: 8101
  }
};
```

- Running ionic serve --verbose with the following output that was out of place...

`Error: listen EADDRNOTAVAIL: address not available`

This error came up with any port between 8000 and 9000 I put in ionic serve --port=8100 --verbose. As a result, I would get the 404 on webpack everytime and be directed to my index.html which shows a blank page. Additionally, webpack output is served from / when I really want it to be served from the root directory. How can I change the directory that the webpack output produces and fix the error of EADDRNOTAVAIL? I am clueless as to what the problem is. Is the problem the EADDRNOTAVAIL error or an incorrect webpack output directory? Please let me know as I am very new to ionic and webpack (in fact, I just learned of webpack yesterday).Let me know if you need more information. Thank you so much!

**Comment by hiroppy** [comment] 2019-07-27 05:46
Please submit the reproducible repo.

**Comment by evilebottnawi** [comment] 2019-07-27 11:46
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use issue template and issue was reopen

**Closed by evilebottnawi** 2019-07-27 11:46 UTC

**Comment by Simeon2001** [comment] 2020-05-01 01:37
[ng] ℹ ｢wds｣: Project is running at http://localhost:8100/webpack-dev-server/
[ng] ℹ ｢wds｣: webpack output is served from /
[ng] ℹ ｢wds｣: 404s will fallback to //index.html
Facing this problem

**Comment by Amit221060** [comment] 2020-05-18 14:58
Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /   
i ｢wds｣: 404s will fallback to //index.html

**Comment by Simeon2001** [comment] 2020-05-19 13:57
Yeah having same problem back yet no solution
