### ISSUE TITLE
[webpack-dev-middleware] ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.

### ISSUE THREAD

**Issue by gonandriy** [webpack/webpack-dev-server#4947] opened 2023-07-18 09:50 UTC
### Actual Behavior

If I export multiple configurations, as described here
https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations
and run `webpack serve`
I see this error
![image](https://github.com/webpack/webpack-dev-server/assets/546048/ca8fa7a3-d8da-490d-8d9d-3a1032386572)

**And watching for files changing does not work!**

webpack.config.js is very simple
```
const path = require('path');

module.exports = [
  {
    mode: 'development',
    entry: './src/index.js',
    output: {
      filename: 'main.js',
      path: path.resolve(__dirname, 'dist/default/'),
    },
    devtool: 'inline-source-map',
    devServer: {
      static: './dist/default',
    },
  },
  {
    mode: 'development',
    entry: './src/admin.js',
    output: {
      filename: 'admin.js',
      path: path.resolve(__dirname, 'dist/admin/'),
    },
    devtool: 'inline-source-map',
    devServer: {
      static: './dist/admin',
    },
  }
];
````

### Expected Behavior

The webpack dev server is running and watches after file changing and always serve the most recent compiled content.

**Comment by 9at8** [comment] 2023-08-21 23:42
Can repro 👍

**Comment by sentience** [comment] 2023-11-09 07:35
Looks like a dupe of #3666, although that one didn't mention that watching for file changes was broken.

**Comment by sentience** [comment] 2023-11-09 08:11
I believe this is actually a misconfiguration.

Per https://github.com/webpack/webpack-cli/issues/2408#issuecomment-793052542, the correct way to configure webpack-dev-server in a multi-config setup is to add the `devServer` block only to the _first_ config:

```json
const path = require('path');

module.exports = [
  {
    entry: './src/index.js',
    ⋮
    devServer: {
      static: './dist/default',
    },
  },
  {
    entry: './src/admin.js',
    ⋮
  }
];
```

The one instance of webpack-dev-server will serve files for _both_ of your configurations! This is very convenient, but it does present challenges if you _want_ devServer to be configured differently for each of your webpack configs (e.g. in @gonandriy's case above, having different `static` values). This does not appear to be possible, except by running entirely separate processes for each webpack-dev-server, using the `--config-name` flag to select which configuration to run for each.

**Comment by alexander-akait** [comment] 2024-01-04 15:21
Close in favor https://github.com/webpack/webpack-cli/issues/2408, we are still working on it, current solution is using https://github.com/webpack/webpack-dev-server/issues/4947#issuecomment-1803342454

**Closed by alexander-akait** 2024-01-04 15:21 UTC
