### ISSUE TITLE
image link breaks after updating scss with html-loader

### ISSUE THREAD

**Issue by jderijke** [webpack/webpack-dev-server#4481] opened 2022-06-11 08:58 UTC
### Bug report
When I start the page in the small attached project using webpack-dev-server the page is displayed as expected..
When webpack reloads the project, image links break.
Images are loaded by html-loader.
Issue is also reported here: https://stackoverflow.com/questions/72498866/webpack-images-disappear-after-css-changes-using-webpack-dev-server

### Actual Behavior

When I start the page in the small attached project using webpack-dev-server the page is displayed as expected.
When I change something (e.g. a margin in scss), webpack reloads the project,
when I refresh the page image links are broken.
### Expected Behavior

When I refresh the page images should still be there.

The problem does NOT appear if i first build and then run webpack-dev-server,
probably because webpack-dev-server can fallback on the image that is generated in dist.
So there is a workaround but it still is annoying.

### How Do We Reproduce?

Reproduce (in attached small project)
[q2.zip](https://github.com/webpack/webpack-dev-server/files/8883558/q2.zip)

npm i
npm start
# change a margin in scss
# reload page in browser

**Comment by alexander-akait** [comment] 2022-09-27 02:09
Sorry for delay, known issue (duplicate of https://github.com/webpack/webpack/issues/13275), the bug in `html-webpack-plugin`, we can't fix it here (but you can ping author of `html-webpack-plugin`), sorry

**Closed by alexander-akait** 2022-09-27 02:09 UTC
