### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin / Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by pladaria** [webpack/webpack-dev-server#1052] opened 2017-08-24 08:31 UTC
Using webpack-dev-server 2.7.1

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After updating to webpack 3 and latest `webpack-dev-server` dev server stops working.
![](http://i.imgur.com/iPqVoy9.png)

With webpack 2.6.0 and webpack-dev-server 2.5.0 everything works as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

Our dev environment runs inside a docker container with nginx:
```
    devServer: {
        clientLogLevel: 'none',
        noInfo: true,
        quiet: true,
        https: true,
        compress: true,
        hot: true,
        proxy: {
            '/': {
                target: 'https://nginx_dev', // this is a docker-compose service
                secure: false,
            },
        },
        watchOptions: {
            ignored: /node_modules/,
        },
        disableHostCheck: true,
        host: '0.0.0.0',
        port: 5555,
        publicPath: '/bundles/',
    },
```
Not sure if relevant but in our local machines, we add an `/etc/hosts` entry to resolve `local.company.com` to `127.0.0.1`, this way we can consume `company.com` apis and resources from a locally served website.

For development, nginx uses a self-signed certificate (we tried to use the same certificate in the devServer.http field with the same result).

As said before, our setup works perfectly with webpack 2 and a previous dev-server version.

**What is the expected behavior?**
Working dev server

**Please mention your webpack and Operating System version.**
Webpack 3.5.5
OS: Ubuntu Linux x86_64

**Comment by shellscape** [comment] 2017-08-28 03:54
This is almost certainly an issue rooted in your webpack (and/or environment) configuration. Check your plugins, loaders, resolvers, etc within your webpack config and try to pick them off until you're at a bare bones config. That's also a pretty complex setup and I'm afraid we won't be able to reproduce that locally.

We'll leave this one open in case further triage reveals an edge case bug that needs to be fixed, but we see these kinds of wonky errors come through a few times a week, and that's usually what it ends up being.

**Comment by coltonw** [comment] 2017-08-31 18:28
I am having this exact same issue (with a similarly complicated setup) so @pladaria if you do figure it out, I would greatly appreciate it if you post a reply back to this thread!

**Comment by stephenmudra** [comment] 2017-09-12 02:21
I've been running into the same issue as well.

It seems the issues has something to do with a change in webpack rather than the dev server, as I can reproduce the issue by just upgrading to webpack v3, no other dependencies.

It also only occurs when https is enabled, works fine in http mode.

**Comment by pladaria** [comment] 2017-09-12 18:59
We tried to upgrade our deps again to the latest versions. This time without problems! HMR, DLL, https, docker, nginx proxy, several third party and custom plugins... everything works perfectly.

Current versions:
- webpack: 3.5.6
- webpack-dev-server: 2.7.1

**Comment by shellscape** [comment] 2017-09-12 23:13
@pladaria great to hear, are we good to close this issue?

**Comment by pladaria** [comment] 2017-09-13 07:43
My issue is fixed, not sure if @stephenmudra or @coltonw can confirm

**Comment by coltonw** [comment] 2017-09-13 12:25
Yeah, don't keep it open on my account.  Seems to be working for me again.

**Comment by shellscape** [comment] 2017-09-13 14:20
Thanks all

**Closed by shellscape** 2017-09-13 14:20 UTC
Labels: X0: need more information
