### ISSUE TITLE
DefaultStatsFactoryPlugin in v5 may not be able to provide enough info for webpack-dev-server to auto-reload especially in undo change scenario

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack-dev-server#2774] opened 2020-10-16 07:17 UTC
I am unable to give you a branch to see the issue visually. I will do my best to describe it

webpack-dev-server is using this logic to determine if it needs to reload

https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/Server.js#L975

This information depends on [`compilation.emittedAssets`](https://github.com/webpack/webpack/blob/83790375529c5b2967d45ed40700399e107d478f/lib/stats/DefaultStatsFactoryPlugin.js#L689) 
```js
object.emitted = compilation.emittedAssets.has(asset.name);
```

Here is the scenario with v5, 
1. You have already started the server.
2. After the initial build, you introduce a new change and hit save. it will emit the assets and you will see an auto-reload because [this](https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/Server.js#L975) return `false`.
https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/Server.js#L969
  `stats` will look like this
    ```js
    [
      {
        type: 'assets by status',
        cached: true,
        filteredChildren: 1,
        size: 1377844
      },
      {
        type: 'asset',
        name: 'index.791ac9dd01fbfa7dfded.js',
        size: 2709,
        chunkNames: [ 'index' ],
        chunkIdHints: [],
        auxiliaryChunkNames: [],
        auxiliaryChunkIdHints: [],
        emitted: true, <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        comparedForEmit: false,
        cached: false,
        info: {
          immutable: true,
          contenthash: '791ac9dd01fbfa7dfded',
          size: 2709
        },
        filteredRelated: undefined
      }
    ]
    ```

3. Afterwards, you undo that change and then hit save, it will not emit the assets and you will not see a reload because [this](https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/Server.js#L975) return `true`. But I expect this should be a reload case
https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/Server.js#L969
  `stats` will look like this
    ```js
    [
      {
        type: 'assets by status',
        cached: true,
        filteredChildren: 2,
        size: NaN
      }
    ]
    ```

I would say This logic https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/Server.js#L975 is no longer valid in v5

**Comment by wood1986** [comment] 2020-10-16 07:32
I am not sure if this belongs to webpack or webpack-dev-server 

cc @sokra

**Comment by evilebottnawi** [comment] 2020-10-16 10:55
@wood1986 please stop provide links on code, describe your problem, better to create reproducible test repo, I closed this because you don't use the issue template, I will reopen it after you fix it

**Closed by evilebottnawi** 2020-10-16 10:55 UTC
