### ISSUE TITLE
Multiple config problem 

### ISSUE THREAD

**Issue by trsh** [webpack/webpack-dev-server#660] opened 2016-10-18 12:51 UTC
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
webpack: 2.1.0-beta.22
webpack-dev-server: 2.1.0-beta.2

**Please tell us about your environment:**
Windows 10
Running server via CLI

**Current behavior:**

I have multiple configs processed in one run `[configA, configB]` (similar to [https://github.com/webpack/webpack/tree/master/examples/multi-compiler] example) Config A puts all content in /dist/A, config B puts all in /dist/B (this what I get on building). However, when I run it on webpack-dev-server I just get 404 all the time when accessing the URLs. If it's just one config it works, multiple don't. Settings "publicPath" for each config did not help.

**Expected/desired behavior:**

If I set publicPath for A to "/A/" and for B "/B/", I should be able to access sites with urls like, localhost:300/A/ and localhost:3000/B/.

**Comment by SpaceK33z** [comment] 2016-10-18 13:11
Dupe of #200

**Closed by SpaceK33z** 2016-10-18 13:11 UTC
