### ISSUE TITLE
[sockjs-client] fix exponential reconnect time 

### ISSUE THREAD

**Issue by carlosgeos** [webpack/webpack-dev-server#1616] opened 2019-01-02 18:59 UTC
* Operating System: Debian
* Node Version: v11.6.0
* NPM Version: 6.5.0
* webpack Version: 4.28.3
* webpack-dev-server Version: 3.1.14

- [x] This is a **bug**

### Code

You can see the problem here:
https://github.com/webpack/webpack-dev-server/blob/v3.1.14/client-src/default/socket.js

### Expected Behavior

An exponential increase in time between reconnects with the sockjs server.

### Actual Behavior

As you can see in the code I linked, the method `onopen` resets the `retries` variable to 0, so retries is always 0, and `onclose` always tries to reconnect waiting the minimum time. Therefore the 'infinite logspam' solution doesn't work and people experience what is depicted in https://github.com/webpack/webpack-dev-server/issues/1604

Also, here (from https://github.com/webpack/webpack-dev-server/issues/1604 as well): 
![50633098-6354a900-0f4a-11e9-95ba-22cbbc569438](https://user-images.githubusercontent.com/5300711/50638259-62794280-0f5d-11e9-9383-803f3c448086.gif)

### How can we reproduce the behavior?

Make the sockjs server close the connection (for example because the client has a bad origin header), the client will try to reconnect forever without respecting the intended timeout.

It is obvious looking at the code anyway.

### PR

I've already submitted a PR.

**Comment by alexander-akait** [comment] 2021-07-19 20:05
Should be fixed in v4

**Closed by alexander-akait** 2021-07-19 20:05 UTC
Labels: priority: 3 (important), semver: patch, severity: 3 (broken), type: bug

**Comment by amakhrov** [comment] 2022-04-11 19:33
I don't see any related changes in the code, and it seems that v4 still keeps retrying indefinitely without any exponential backoff.
@alexander-akait could you please clarify?

**Comment by alexander-akait** [comment] 2022-04-11 20:19
@amakhrov Can you check you have a latest version? If you still have a problem, please provide example how we can reproduce it

**Comment by amakhrov** [comment] 2022-04-11 21:37
We're on 4.7.3

The exact scenario is webpack-dev-server terminating the socket, if it didn't receive the "pong" from the client as a part of heartbeat check.

**Comment by amakhrov** [comment] 2022-04-12 17:54
Now as I think further about the use case, I understand why retries do not work properly.

In this case a client socket successfully connects, but then the server terminates it (due to the lack of ping response). Every time a socket successfully connects, `retries` counter is reset - which is totally valid in other scenarios, but effectively disables the exponential retries logic for my case.

I'm not sure it's possible for the client socket to differentiate between the two cases, though
