### ISSUE TITLE
Push release to NPM

### ISSUE THREAD

**Issue by LegNeato** [webpack/webpack-dev-server#460] opened 2016-04-22 01:14 UTC
There have been a ton of great fixes since Jan. They should be pushed to npm.

FWIW, I hit the bug fixed by this:

https://github.com/webpack/webpack-dev-server/commit/ed43efa937e8f26fb92db9b12cb986446e6fcfa1

**Comment by MarkPieszak** [comment] 2016-04-22 13:21
I've been wondering myself, who is the `owner` of this Repo now? There hasn't been an update in 28 days. There are 23 PRs going way back that haven't been looked at or merged.

What's going on?

**Comment by SpaceK33z** [comment] 2016-08-21 14:20
Dupe of #363.

**Closed by SpaceK33z** 2016-08-21 14:20 UTC
