### ISSUE TITLE
[WDS] Disconnected! - Bug?

### ISSUE THREAD

**Issue by chobo2** [webpack/webpack-dev-server#1419] opened 2018-06-07 18:20 UTC
Hi

I am having a problem where my webpack seems to get chocked up and then I lose connection. I usually have to recompile after one refresh

OS: Windows 7
Node: v8.10.0
NPM: 6.1.0
webpack: ^4.10.2
webpack-cli: ^2.1.4
webpack-dev-server: ^3.1.4
Chrome : 67.0.3396.79

### Expected Behavior

When I hit the save button, it will refresh the google chrome page.

### Actual Behavior

It will refresh on save maybe once or twice but after that the connection timesout and then disconnects.
### For Bugs; How can we reproduce the behavior?

https://github.com/chobo2/WebpackTest

**Comment by waleedahmed3045** [comment] 2018-06-11 01:59
I am getting this message **HMR Not receive update signal from WDS** and stuck in console console. My page is going in an infinite loading.

**Comment by Bounty31** [comment] 2018-06-11 09:55
Also happening to me, it looks like it is happening since my Chrome updated to V67

**Comment by chobo2** [comment] 2018-06-11 15:53
I think for me it been happening even before v67. I have to admit I never tried any other browser to see if they have the same problem.

**Comment by gs-ppara** [comment] 2018-06-11 19:00
Open chrome://flags/#allow-insecure-localhost
Change 'Allow invalid certificates for resources loaded from localhost'  to `Enabled`

It works for me (temporary workaround)

**Comment by chobo2** [comment] 2018-06-11 19:35
@gs-ppara 

It does not seem to work for me.

**Comment by DanielRuf** [comment] 2018-06-12 05:01
Did you restart Chrome? Also which domain / hostname do you use for the server?

So far this is not a bug / issue in webpack. We have no control over the security settings of the browsers.

**Comment by DanielRuf** [comment] 2018-06-12 05:03
Also see https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate/31879393#31879393

**Comment by chobo2** [comment] 2018-06-12 15:57
@DanielRuf 

Yes I restarted Chrome. I am on localhost:8080.

I went to the stack page and I cannot find the option they are talking about in my version of chrome.

**Comment by DanielRuf** [comment] 2018-06-12 16:31
And one of the bypasses? https://stackoverflow.com/a/47646463/753676

**Comment by chobo2** [comment] 2018-06-12 22:54
@DanielRuf 

I am not sure, I will try it but I am not really sure how to get to wherever I need to put a bypass in.

**Comment by chobo2** [comment] 2018-06-14 19:06
Anyone have any other suggestions?

**Comment by cnyet** [comment] 2018-06-25 03:31
@chobo2 I had this problem at the beginning，and because I set `optimization.runtimeChunk` to `true` in my webpack configuration. so when I removed `optimization.runtimeChunk`, it works completely. I hope it will help you.

**Comment by chobo2** [comment] 2018-06-25 16:30
@cnyet 

I don't think I have that flag set, I dont' see it in my webpack config, unless this is something on by default?

**Comment by colingreene28** [comment] 2018-06-26 02:52
Unsure if this is related but I noticed that once I updated to Chrome v67 it was forcing localhost over https (or at least I think it was). I added [`https:true`](https://webpack.js.org/configuration/dev-server/#devserver-https) and that seemed to get me back up and running.

**Comment by gitors** [comment] 2018-07-04 06:43
@gs-ppara  it not work for me. 
i have restarted my chrome.
it is my chrome version ,


![image](https://user-images.githubusercontent.com/31715318/42260857-94c41576-7f98-11e8-85a3-a31119ffdae2.png)

**Comment by gitors** [comment] 2018-07-04 06:49
I am a Chinese, my English is not very good, do not know how to express, but now I will encounter endless requests, causing my own server to be blocked。
Can someone give me some advice？
thanks!

**Comment by xxxfuwei** [comment] 2018-07-17 08:47
@gitors , I have same problem. And my chrome version is 67.0.3396.99 just like you.

**Comment by xxxfuwei** [comment] 2018-07-17 09:34
@gitors , can you fixed this problem?

**Comment by gitors** [comment] 2018-07-19 00:49
@xxxfuwei  i reset my codes from gitlab to solve the problem.

**Comment by michael-ciniawsky** [comment] 2018-08-26 01:15
@all Does this still happen with https://github.com/webpack/webpack-dev-server/pull/1434 (v3.1.5) ?

**Comment by WellspringCS** [comment] 2018-10-03 00:50
I'm seeing this behavior too. Driving me nuts.

**Comment by WellspringCS** [comment] 2018-10-04 13:57
@evilebottnawi  I apologize, but I cannot, for several reasons. Behind on everything is #1, but even so the other problem was that in order to solve the problem I did strip my project bare and rebuilt it. The issue did not resurface until I had added several layers of components and navigation, at which point I started having existential moments, wondering what to do. I finally tried the desperation already noted, and it worked. But it seems that in order to have the problem, you have to have some weight to your project. That's my 2 cents, anyway. I will clarify, however, that the key features that produced this problem for me were (and I'm not sure which, if any, are the necessary ingredients... I'm just listing them:
1) OAuth security implemented by oidc-client
2) Angular 6+
3) components/angular materials
4) lazy loading


Here's the contents of my package.json

`{
  "name": "eqp-management-client",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve -o",
    "startfresh": "ng serve -o",
    "startprod": "ng serve -o --prod --configuration=production",
    "startstaging": "ng serve -o --prod --configuration=staging",
    "build": "ng build",
    "buildprod": "ng build --configuration=production",
    "buildstaging": "ng build --configuration=staging",
    "buildwatch": "ng build --watch --delete-output-path false",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "ngsw": "node_modules/.bin/ngsw-config dist ngsw-config.json",
    "ngsw-config": "node_modules/.bin/ngsw-config dist src/ngsw-config.json",
    "ngsw-copy": "cp node_modules/@angular/service-worker/ngsw-worker.js dist/",
    "build-prod-ngsw": "ng build --prod && npm run ngsw-config && npm run ngsw-copy",
    "serve-prod-ngsw": "npm run build-prod-ngsw && http-server dist -p 8080"
  },
  "prettier": {
    "printWidth": 80,
    "singleQuote": true,
    "useTabs": false,
    "tabWidth": 2,
    "semi": true,
    "bracketSpacing": true
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "0.6.8",
    "@angular/animations": "6.1.4",
    "@angular/cdk": "^6.1.4",
    "@angular/common": "6.1.4",
    "@angular/compiler": "6.1.4",
    "@angular/core": "6.1.4",
    "@angular/forms": "6.1.4",
    "@angular/http": "6.1.4",
    "@angular/material": "^6.4.6",
    "@angular/platform-browser": "6.1.4",
    "@angular/platform-browser-dynamic": "6.1.4",
    "@angular/pwa": "^0.7.5",
    "@angular/router": "6.1.4",
    "@angular/service-worker": "^6.1.4",
    "@fortawesome/fontawesome-free": "^5.2.0",
    "@ngrx/effects": "^6.1.0",
    "@ngrx/store": "^6.1.0",
    "@ngrx/store-devtools": "^6.1.0",
    "automapper-ts": "^1.9.0",
    "bootstrap": "4.1.0",
    "core-js": "^2.4.1",
    "cosmiconfig": "^5.0.5",
    "fast-json-patch": "^2.0.6",
    "hammerjs": "^2.0.8",
    "idb": "^2.1.3",
    "jquery": "^3.3.1",
    "json2typescript": "^1.0.6",
    "oidc-client": "^1.5.1",
    "popper": "^1.0.1",
    "popper.js": "^1.14.4",
    "resize-observer-polyfill": "^1.5.0",
    "rxjs": "^6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.5",
    "@angular/cli": "7.0.0-rc.1",
    "@angular/compiler-cli": "6.1.4",
    "@angular/language-service": "6.1.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "sockjs-client": "1.3.0",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "^2.9.2"
  },
  "main": "index.js"
}
`

**Comment by evilebottnawi** [comment] 2018-10-04 14:01
@WellspringCS It is hard to reproduce problem based on your information, i can't help without minimum reproducible test repo. We can contact via email and use NDA if you are afraid for the information in the project.

**Comment by WellspringCS** [comment] 2018-10-04 14:02
Yes, I would be fine with that approach, and if I can be of help I'd gladly do so.

**Comment by evilebottnawi** [comment] 2018-10-04 14:10
@WellspringCS translation game :smile:

**Comment by ArslanAmeer** [comment] 2018-10-29 20:34
Hi!
I dont know but Starting project with `npm start` instead of 'ng serve` fix my WDS Disconnected Error.  🙄😜

**Comment by evilebottnawi** [comment] 2019-04-09 17:31
Here there are lot of difference issues, so i am closing this issue, please open new issue (with reproducible test repo) when you have some problems with latest version

**Closed by evilebottnawi** 2019-04-09 17:31 UTC
Labels: priority: 3 (important), question, severity: 3 (broken), type: bug

**Comment by artemiusgreat** [comment] 2020-01-15 06:52
To reproduce.
Running ASP.NET Core 3.0 with standard React Template in **Visual Studio 2019 using react-scripts. 
Application gets started on https://localhost:44333/**
No errors. 
Removing package lock and executing `npm upgrade` 
List of updated packages. 

+ merge@1.2.1
+ react-router-bootstrap@0.24.4
+ react-scripts@3.3.0
+ react-router-dom@4.3.1
+ react-dom@16.12.0
+ jquery@3.4.1
+ react@16.12.0
+ oidc-client@1.10.1
+ bootstrap@4.4.1
+ reactstrap@6.5.0
+ rimraf@2.7.1

Now I'm getting error.

```
  | ./node_modules/react-dev-utils/webpackHotDevClient.js | @ | webpackHotDevClient.js:60
  | __webpack_require__ | @ | bootstrap:785
  | fn | @ | bootstrap:150
  | 1 | @ | index.js:10
  | __webpack_require__ | @ | bootstrap:785
  | checkDeferredModules | @ | bootstrap:45
  | webpackJsonpCallback | @ | bootstrap:32
  | (anonymous) | @ | main.chunk.js:1
```

Meanwhile, when I start React app without Visual Studio just using **npm run start**, it starts on **https://localhost:3000 without errors**.

**Comment by Aceofspades25** [comment] 2020-02-21 15:20
This can be reproduced as well using ASP.NET Core 3.1 with standard Angular Template (Angular 8) so long as you target Internet Explorer as your browser (It does not happen in Chrome)

Likewise when I start the Angular App without Visual Studio (npm start) then I get no script errors when visiting localhost:4200 using Internet Explorer.

Conditions for me appear to be that you must:
 - Use Internet Explorer
 - Serve an Angular SPA from ASP.NET Core (creating a port number different from the port generated from ng serve e.g. localhost:60348)
 - Use Angular 8+ (errors do not happen when I scaffold an Angular 5.2.0 SPA)
