### ISSUE TITLE
Deprecation warning when using Webpack 4

### ISSUE THREAD

**Issue by jods4** [webpack/webpack-dev-server#1324] opened 2018-02-26 17:17 UTC
* Operating System: Win 10
* Node Version: 8.9.4
* NPM Version: 5.6.0
* webpack Version: 4.0.0
* webpack-dev-server Version: 3.0.0

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior
No warning when using `webpack-dev-server`.

### Actual Behavior
A warning appears because `plugin` api is used by something (should be updated to `tap`).

### What is the motivation and/or use-case for the feature?
Warnings made me investigate if this was caused by my own plugin.
Tools, namely aspnet-core-spa, report failures when they detect errors/warnings.

**Comment by SpaceK33z** [comment] 2018-02-26 19:58
Thanks for filing this issue. I fixed the warnings in c32cfa8c01c89a6f35e971c3330d4fe5fb49df5a, however webpack-dev-middleware is not updated to the new API's yet.

See also https://github.com/webpack/webpack-dev-middleware/pull/264

**Comment by alexkrolick** [comment] 2018-02-28 18:51
Seems to be fixed: https://github.com/webpack/webpack-dev-middleware/pull/267

**Comment by gitterchris** [comment] 2018-03-08 22:02
It looks like v3.1.0 still has the deprecation warning even though `webpack-dev-middleware` is already updated. Can you please check?

**Comment by foxxyz** [comment] 2018-03-09 19:52
Looks like it was updated in 2b40391bcfa848d5d8e61f5cbeaf350e01198c39 which was committed after the last release was already out. So we're just waiting for the next release.

**Comment by SpaceK33z** [comment] 2018-03-09 21:38
Published `webpack-dev-server@3.1.1` with the fix.

**Closed by SpaceK33z** 2018-03-09 21:38 UTC

**Comment by osenvosem** [comment] 2018-03-11 14:35
Updated to version 3.1.1 and still am having this warning for some reason. Maybe because I'm using WDS Node API... 🤔

**Comment by SpaceK33z** [comment] 2018-03-11 14:39
@osenvosem I cannot reproduce this. Are you sure no other plugin is the cause of this error?

**Comment by osenvosem** [comment] 2018-03-11 14:46
@SpaceK33z  Only two standard plugins: `webpack.HotModuleReplacementPlugin` and `webpack.DefinePlugin`.
Here is the code: https://github.com/osenvosem/typescript-full-stack-boilerplate

**Comment by foxxyz** [comment] 2018-03-11 21:05
Confirming the deprecation warning no longer appears. Thanks @SpaceK33z!

**Comment by osenvosem** [comment] 2018-03-12 04:19
@foxxyz then, I suppose the issue somewhere on my side. Will be investigating.
