### ISSUE TITLE
Client-canceled XMLHttpRequests to proxy API cause webpack dev server to reload

### ISSUE THREAD

**Issue by anthonybarsotti** [webpack/webpack-dev-server#427] opened 2016-03-15 18:34 UTC
I've run into an issue where if an XMLHttpRequest to a proxy API is either aborted or times out on the client it causes a proxy error and the dev server reloads the page. Does anyone know of a way around this?

**Comment by anthonybarsotti** [comment] 2016-03-15 18:57
I've gotten around this temporarily by imposing the timeout on the server but I'm still curious to see if there is a solution to this.

**Comment by thetalecrafter** [comment] 2016-04-12 00:46
It looks like aborting a proxied request triggers a "proxy error" message through the socket, which causes the client to reload.

**Comment by jiarongxu** [comment] 2016-06-14 20:48
Same issue here. Any solution?

**Comment by oers** [comment] 2016-07-20 07:25
same issue like this?:

https://github.com/webpack/webpack-dev-server/issues/369

I think we need a way to configure/disable the timeout for long running requests.

**Comment by makuko** [comment] 2016-08-03 11:52
This can be fixed by adding the following line between lines 147 and 148 of lib/Server.js in 1.14.1:

`if (err.code === 'ECONNRESET') return;`

ECONNRESET means it was not actually an error but intentional by the client.

**Comment by doxavore** [comment] 2016-08-31 20:13
I can confirm @makuko's fix works in 1.14.1. This can sometimes be very common issue for those of us using Angular 2 + RxJS.

**Comment by SpaceK33z** [comment] 2016-09-03 14:06
This was fixed with PR #478, and released with `1.15.0`.

**Closed by SpaceK33z** 2016-09-03 14:06 UTC
Labels: bug

**Comment by hantsy** [comment] 2017-03-31 10:43
I always encountered the `ECONNRESET` when used a proxy config in my Angular2 project(generated by Angular CLI 1.0.0 which shipped webpack-dev-server 2.3.0). 

```
[HPM] GET /api/upload/uploads-1490782788752.png -> http://localhost:3000
[HPM] Error occurred while trying to proxy request /api/upload/uploads-1490782788752.png from localhost:4300 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by dhatawesomedude** [comment] 2017-08-23 05:59
@hantsy how did you get around this for Angular 2 projects?

**Comment by hantsy** [comment] 2017-08-23 06:55
@dhatawesomedude It seems it is disappeared in the latest Angular 4+, I was using newest Angular CLI to create the projects.
