### ISSUE TITLE
devServer.hot not working.

### ISSUE THREAD

**Issue by oimmc** [webpack/webpack-dev-server#2779] opened 2020-10-19 01:51 UTC
- Operating System: OSX
- Node Version: 10.22.0
- "webpack": "^5.1.0",
- "webpack-cli": "^4.0.0",
- "webpack-dev-server": "^3.11.0",

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
devServer: {
  historyApiFallback: true,
  host: '0.0.0.0',
  port: 8989,
  compress: true,
  noInfo: true,
  useLocalIp: true,
  hot: true,
  open: false
}
```

```js
"start": "cross-env NODE_ENV=development webpack serve --progress --config webpack.dev.js"
```
  run npm start, hot not working.

**Comment by geart891** [comment] 2020-10-19 09:23
Set `target: "web"` will fix your problem.
```
module.exports = {
  // ...
  target: "web"
};

```

**Comment by ylemkimon** [comment] 2020-10-19 10:13
Duplicate of #2758.

**Comment by evilebottnawi** [comment] 2020-10-19 11:42
Duplicate

**Closed by evilebottnawi** 2020-10-19 11:42 UTC
