### ISSUE TITLE
Deprecation Warning for Setup Always Appears

### ISSUE THREAD

**Issue by bdwain** [webpack/webpack-dev-server#1120] opened 2017-09-27 16:35 UTC
* Operating System: Mac Sierra
* Node Version: 8.6
* NPM Version: 5
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.9.0

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
any config will work
```

### Expected Behavior
I should not see the deprecation warning when running webpack dev server via the command line if I don't have a setup hook in my config.

### Actual Behavior
I see the message 'Using "setup" is deprecated and will be removed in the next major version. Please use the "before" and "after" hooks instead.'

### For Bugs; How can we reproduce the behavior?
Just run webpack-dev-server with any config.

This seems to have been introduced in #1108. The code to log the warning is always run, even if you specified no setup hook.

I can open a PR to fix this if desired.

**Comment by shellscape** [comment] 2017-09-27 16:53
Duplicate of #1118. Please comment there.

**Closed by shellscape** 2017-09-27 16:53 UTC
