### ISSUE TITLE
Issue with new SHA256 certificates on Windows

### ISSUE THREAD

**Issue by thrandre** [webpack/webpack-dev-server#648] opened 2016-10-11 11:48 UTC
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
webpack: 2.1.0.beta-25 
webpack-dev-server: 2.1.0-beta8

**Please tell us about your environment:**
Windows 10
Running server via CLI (`https` enabled)

**Config:**
```
	devServer: {
		publicPath: "http://localhost:8080/assets/",
		https: true,
		inline: true,
		contentBase: "https://localhost:44392"
	}
```

**Current behavior:**
New SHA256 certificates are reported as being invalid (`The signature of the certificate cannot be verified.`) on Windows 10. Browsers refuse to connect.

** Result after verification by `certutil` **

```
Issuer:
    CN=localhost
    O=webpack
    S=Some-State
    C=US
  Name Hash(sha1): c09e932a57991f558ce9c1356054b21339ebeea8
  Name Hash(md5): d385876d7cf158cfc6e6bacc097efd90
Subject:
    CN=localhost
    O=webpack
    S=Some-State
    C=US
  Name Hash(sha1): c09e932a57991f558ce9c1356054b21339ebeea8
  Name Hash(md5): d385876d7cf158cfc6e6bacc097efd90
Cert Serial Number: 8dca6301d73b9c66

dwFlags = CA_VERIFY_FLAGS_CONSOLE_TRACE (0x20000000)
dwFlags = CA_VERIFY_FLAGS_DUMP_CHAIN (0x40000000)
ChainFlags = CERT_CHAIN_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT (0x40000000)
HCCE_LOCAL_MACHINE
CERT_CHAIN_POLICY_BASE
-------- CERT_CHAIN_CONTEXT --------
ChainContext.dwErrorStatus = CERT_TRUST_IS_NOT_SIGNATURE_VALID (0x8)
ChainContext.dwErrorStatus = CERT_TRUST_IS_UNTRUSTED_ROOT (0x20)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_NOT_SIGNATURE_VALID (0x8)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_UNTRUSTED_ROOT (0x20)

CertContext[0][0]: dwInfoStatus=c dwErrorStatus=28
  Issuer: CN=localhost, O=webpack, S=Some-State, C=US
  NotBefore: 27.08.2016 17.31
  NotAfter: 09.01.2018 17.31
  Subject: CN=localhost, O=webpack, S=Some-State, C=US
  Serial: 8dca6301d73b9c66
  Cert: 5117f06a1d761f80eabb34f7385e3d86721effed
  Element.dwInfoStatus = CERT_TRUST_HAS_NAME_MATCH_ISSUER (0x4)
  Element.dwInfoStatus = CERT_TRUST_IS_SELF_SIGNED (0x8)
  Element.dwErrorStatus = CERT_TRUST_IS_NOT_SIGNATURE_VALID (0x8)
  Element.dwErrorStatus = CERT_TRUST_IS_UNTRUSTED_ROOT (0x20)

Exclude leaf cert:
  Chain: da39a3ee5e6b4b0d3255bfef95601890afd80709
Full chain:
  Chain: 5117f06a1d761f80eabb34f7385e3d86721effed
  Issuer: CN=localhost, O=webpack, S=Some-State, C=US
  NotBefore: 27.08.2016 17.31
  NotAfter: 09.01.2018 17.31
  Subject: CN=localhost, O=webpack, S=Some-State, C=US
  Serial: 8dca6301d73b9c66
  Cert: 5117f06a1d761f80eabb34f7385e3d86721effed
The signature of the certificate cannot be verified. 0x80096004 (-2146869244 TRUST_E_CERT_SIGNATURE)
------------------------------------
CertUtil: -verify command FAILED: 0x80096004 (-2146869244 TRUST_E_CERT_SIGNATURE)
CertUtil: The signature of the certificate cannot be verified.
```

**Comment by SpaceK33z** [comment] 2016-10-14 08:54
So to be clear, this prevents you from connecting at all? Even if you click "Next" (or something like that) and continue "unsecure"?

**Comment by thrandre** [comment] 2016-10-14 08:58
That is correct. Neither Chrome or IE even provides such an option.

**Comment by jdiapps** [comment] 2016-10-24 20:30
I can get firefox to proceed by adding an exception. This will get me over the hurdle for now until it is fixed.

**Comment by SpaceK33z** [comment] 2016-10-29 14:57
Reproduced the problem in Windows, and verified that it was fixed with e97741c84ca69913283ae5d48cc3f4e0cf8334e3. Fix released in `2.1.0-beta.10`!

**Closed by SpaceK33z** 2016-10-29 14:57 UTC
Labels: bug, P2: Very Important, S4: Broken

**Comment by stoffeastrom** [comment] 2016-11-04 10:53
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:53
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:54
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:54
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:54
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:54
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:54
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:54
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:54
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:54
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by stoffeastrom** [comment] 2016-11-04 10:54
I just tried this but I get ` NET::ERR_CERT_AUTHORITY_INVALID`. Do I have to do something more?

**Comment by SpaceK33z** [comment] 2016-11-04 11:20
But you can click on something like continue, right? The cert authority is invalid because it's a fake cert.

**Comment by stoffeastrom** [comment] 2016-11-04 11:33
Oh yes, I forgot that I have to click Advanced -> continue to unsecure.. bl bla thanks
